# This file is protected by Copyright. Please refer to the COPYRIGHT file
# distributed with this source distribution.
#
# This file is part of OpenCPI <http://www.opencpi.org>
#
# OpenCPI is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# OpenCPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.


import os
import hashlib
from _opencpi.assets.abstract2 import *
from _opencpi.assets.abstract2 import AssetBase


apps_dir_rst_template = """.. Application directory index page


Applications
============
Available applications.

.. toctree::
   :maxdepth: 2
   :glob:

   */*-application
   */*

.. Make sure that any subsidiary files that are included into an asset document,
   whether or not they are local, are named with the suffix .inc, not .rst.
   Using the .inc suffix for subsidiary included files is currently necessary
   to prevent them from being mistakenly generated by the asset documentation
   system during a documentation build operation.

.. The search path "*/*-application" is for backward compatibility with older
   application document naming schemes.\n
"""  # nopep8

app_rst_template = """.. {{asset.name}} documentation


.. _{{asset.name}}-application:


SKELETON NAME (``{{asset.name}}``)
==================================
Skeleton outline: Optional short summary of this application.

Description
-----------
Skeleton outline: Functional description of **what** the application achieves.

Hardware Portability
--------------------
Skeleton outline: Description of **which** platforms the application is intended to be run on.

Execution
---------

Prerequisites
~~~~~~~~~~~~~
Skeleton outline: A list of steps that need to be taken before the application can be executed.

Command(s)
~~~~~~~~~~
Skeleton outline: A list of commands to run in order to execute the application.

Verification
------------
Skeleton outline: Possible outputs of the application.

Troubleshooting
---------------
Skeleton outline: List any known issues and and potential fixes here.

**If the above template is not appropriate, consider replacing sections "Execution", "Verification" and "Troubleshooting" with the following:**

Building the App
----------------
Skeleton outline: Include dependencies and any prerequisite steps that need to be taken to build the application.

Testing the App
---------------
Skeleton outline: Information on sample test setups, required artifacts, executable arguments and expected results. Also include any known issues here, if any.

Worker Properties
-----------------
Skeleton outline: A list of the configurable properties for each of the workers in the application.

Worker Artifacts
----------------
Skeleton outline: Any artifacts that are produced by the application.\n
"""  # nopep8

app_cc_template = """#include <iostream>
#include <string>
#include "OcpiApi.hh"

namespace OA = OCPI::API;

int main(/*int argc, char **argv*/) {
  // For an explanation of the ACI, see:
  // https://opencpi.gitlab.io/releases/develop/docs/OpenCPI_Application_Development_Guide.pdf

  try {
    OA::Application app("{{asset.name}}.xml");
    app.initialize(); // all resources have been allocated
    app.start();      // execution is started

    // Do work here.

    // Must use either wait()/finish() or stop(). The finish() method must
    // always be called after wait(). The start() method can be called
    // again after stop().
    app.wait();       // wait until app is "done"
    app.finish();     // do end-of-run processing like dump properties
    // app.stop();

  } catch (std::string &e) {
    std::cerr << "app failed: " << e << std::endl;
    return 1;
  }
  return 0;
}\n
"""  # nopep8


class ApplicationsDirectory(AssetBase):
    """ Reference Application Development Guide section 10.2 """

    def __init__(self, dir_abs_path, enable_path_existence_check=True,
                 cli_dict=None):
        self.root_tags = ['Applications']
        AssetBase.__init__(self, dir_abs_path, enable_path_existence_check)
        if enable_path_existence_check:
            self.parse(cli_dict)

    def get_templates(self, applications=False):
        templates = {}
        templates['applications.rst'] = apps_dir_rst_template
        templates['applications.xml'] = g_asset_template
        return templates


# TODO iherit from, and consolidate functionality from, AssetBase
class Application(AssetBase):
    """ Reference Application Development Guide section 3 """

    def __init__(self, abs_path, enable_path_existence_check=True,
                 cli_dict=None):
        """ abs_path can be xml type OR dir type! see ADG section 10.2 """
        self.root_tags = ['Application']
        AssetBase.__init__(self, abs_path, enable_path_existence_check)
        self.file_name = self.name + '.cc'
        # TODO investigate whether below line is necessary
        # if not os.path.isfile(self.get_xml_abs_path()):
        #     self.raise_abs_path_does_not_exist()
        if enable_path_existence_check:
            if not os.path.isfile(self.get_xml_abs_path()):
                tmp = self.get_dir_abs_path() + '/' + self.name
                if not os.path.isfile(tmp + '.cc'):
                    if not os.path.isfile(tmp + '.c'):
                        if not os.path.isfile(tmp + '.cxx'):
                            if not os.path.isfile(tmp + '.cpp'):
                                tag = self.get_root_tags()[0]
                                msg = self.abs_path + ' is not a ' + tag
                                raise InvalidAssetError(msg)
            self.parse(cli_dict)
        if cli_dict is not None:
            if cli_dict.get('xmldirapp'):
                self.file_name = None

    def get_type(self):
        return 'application'

    def get_templates(self, applications=False):
        templates = {}
        templates[self.name + '.rst'] = app_rst_template
        if (self.get_dir_abs_path().split('/')[-1] != 'applications' and
                self.file_name is not None):
            # TODO prevent application named 'applications'?
            templates[self.file_name] = app_cc_template
        templates[self.name + '.xml'] = g_asset_template

        return templates
