# This file is protected by Copyright. Please refer to the COPYRIGHT file
# distributed with this source distribution.
#
# This file is part of OpenCPI <http://www.opencpi.org>
#
# OpenCPI is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# OpenCPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.


import os
import hashlib
from _opencpi.assets.abstract2 import *
from _opencpi.assets.abstract2 import AssetBase


apps_dir_xml_template = """<applications>
    <!-- To restrict the applications that are built or run, you can set the Applications
    attribute to the specific list of which ones you want to build and run, e.g.:
    <libraries Applications='app1 app3'/>
    Otherwise all applications will be built and run -->
</applications>\n
"""

apps_dir_rst_template = """.. Application directory index page


Applications
============
Available applications.

.. toctree::
   :maxdepth: 2
   :glob:

   */*-application
   */*

.. Make sure that any subsidiary files that are included into an asset document,
   whether or not they are local, are named with the suffix .inc, not .rst.
   Using the .inc suffix for subsidiary included files is currently necessary
   to prevent them from being mistakenly generated by the asset documentation
   system during a documentation build operation.

.. The search path "*/*-application" is for backward compatibility with older
   application document naming schemes.\n
"""

app_rst_template = """.. {{asset.name}} documentation


.. _{{asset.name}}-application:


SKELETON NAME (``{{asset.name}}``)
==================================
Skeleton outline: Optional short summary of this application.

Description
-----------
Skeleton outline: Functional description of **what** the application achieves.

Hardware Portability
--------------------
Skeleton outline: Description of **which** platforms the application is intended to be run on.

Execution
---------

Prerequisites
~~~~~~~~~~~~~
Skeleton outline: A list of steps that need to be taken before the application can be executed.

Command(s)
~~~~~~~~~~
Skeleton outline: A list of commands to run in order to execute the application.

Verification
------------
Skeleton outline: Possible outputs of the application.

Troubleshooting
---------------
Skeleton outline: List any known issues and and potential fixes here.

**If the above template is not appropriate, consider replacing sections "Execution", "Verification" and "Troubleshooting" with the following:**

Building the App
----------------
Skeleton outline: Include dependencies and any prerequisite steps that need to be taken to build the application.

Testing the App
---------------
Skeleton outline: Information on sample test setups, required artifacts, executable arguments and expected results. Also include any known issues here, if any.

Worker Properties
-----------------
Skeleton outline: A list of the configurable properties for each of the workers in the application.

Worker Artifacts
----------------
Skeleton outline: Any artifacts that are produced by the application.\n
"""

app_cc_template = """#include <iostream>
#include <string>
#include "OcpiApi.hh"

namespace OA = OCPI::API;

int main(/*int argc, char **argv*/) {
  // For an explanation of the ACI, see:
  // https://opencpi.gitlab.io/releases/develop/docs/OpenCPI_Application_Development_Guide.pdf

  try {
    OA::Application app("{{asset.name}}.xml");
    app.initialize(); // all resources have been allocated
    app.start();      // execution is started

    // Do work here.

    // Must use either wait()/finish() or stop(). The finish() method must
    // always be called after wait(). The start() method can be called
    // again after stop().
    app.wait();       // wait until app is "done"
    app.finish();     // do end-of-run processing like dump properties
    // app.stop();

  } catch (std::string &e) {
    std::cerr << "app failed: " << e << std::endl;
    return 1;
  }
  return 0;
}\n
"""


def create_templates(name, applications=False):
    app_templates = {}
    # These are files that go at the top-level of the applications directory
    if applications:
        app_templates['applications.xml'] = apps_dir_xml_template
        app_templates['applications.rst'] = apps_dir_rst_template
    # Named application files that go into the named application directory
    else:
        app_templates[name + '.xml'] = g_asset_template
        app_templates[name + '.rst'] = app_rst_template
        app_templates[name + '.cc'] = app_cc_template
    return app_templates


# TODO iherit from, and consolidate functionality from, AssetBase
class Application(AssetBase):
    """ Reference Application Development Guide section 3 """

    def __init__(self, dir_abs_path, enable_path_existence_check=True, cli_dict=None):
        self.root_tags = ['Application']
        AssetBase.__init__(self, dir_abs_path, enable_path_existence_check)
        # TODO investigate whether below line is necessary
        # if not os.path.isfile(self.get_xml_abs_path()):
        #     self.raise_abs_path_does_not_exist()
        if enable_path_existence_check:
            if not os.path.isfile(self.get_xml_abs_path()):
                tmp = self.get_dir_abs_path() + '/' + self.name
                if not os.path.isfile(tmp + '.cc'):
                    if not os.path.isfile(tmp + '.c'):
                        if not os.path.isfile(tmp + '.cxx'):
                            if not os.path.isfile(tmp + '.cpp'):
                                tag = self.get_root_tags()[0]
                                msg = self.abs_path + ' is not a ' + tag
                                raise InvalidAssetError(msg)
        self.parse(cli_dict)

    def get_type(self):
        return 'application'

    def create(self, xmlapp, xmldirapp):
        """ Creates dir/files at the top-level applications directory, and
            creates dir/files within the named application directory """
        apps_dir = '/'.join(self.abs_path.split('/')[:-1])
        apps_templates = create_templates(self.name, applications=True)
        AssetBase.create_files(self, apps_templates, apps_dir, duplicate=True)
        if xmlapp:
            app_templates = create_templates(self.name)
            app_templates.pop(self.name + '.cc')
            AssetBase.create_files(self, app_templates, apps_dir, duplicate=True)
        elif xmldirapp:
            app_templates = create_templates(self.name)
            app_templates.pop(self.name + '.cc')
            AssetBase.create_files(self, app_templates, self.abs_path)
        else:
            app_templates = create_templates(self.name, applications=False)
            AssetBase.create_files(self, app_templates, self.abs_path)

    def parse(self, cli_dict=None):
        AssetBase.parse(self, cli_dict)

def test_Application_create(ret):
    fs = TemporaryFilesystem()
    test_name = 'test_Application_create: '
    name = 'app1'
    app_dir = fs.abs_path + '/foo/applications'
    abs_path = app_dir + '/' + name
    xmlapp = False
    xmldirapp = False
    try:
        Application(
            abs_path, False, None
        ).create(xmlapp, xmldirapp)
        passed = True
    except Exception as e:
        Logger().debug(test_name + str(e))
    # Test for file existence
    apps_files = ['applications.xml', 'applications.rst']
    app_files = ['app1.xml', 'app1.rst', 'app1.cc']
    for apps_file in apps_files:
        path = app_dir + '/' + apps_file
        if not os.path.exists(path):
            passed = False
    for app_file in app_files:
        path = abs_path + '/' + app_file
        if not os.path.exists(path):
            passed = False
    # Test for file integrity
    msg = 'invalid expected md5sum for file: '
    apps_xml = app_dir + '/' + apps_files[0]
    apps_xml_md5 = hashlib.md5(open(apps_xml, 'rb').read()).hexdigest()
    if apps_xml_md5 != '69897555db79c40e9de4d95924f9a80f':
        passed = False
        Logger().error(test_name + str(msg + app_dir + '/' + apps_files[0]))
    apps_rst = app_dir + '/' + apps_files[1]
    apps_rst_md5 = hashlib.md5(open(apps_rst, 'rb').read()).hexdigest()
    if apps_rst_md5 != '6d026d7f0cf86224a15f5c109ea0f623':
        passed = False
        Logger().error(test_name + str(msg + app_dir + '/' + apps_files[1]))
    app_xml = abs_path + '/' + app_files[0]
    app_xml_md5 = hashlib.md5(open(app_xml, 'rb').read()).hexdigest()
    if app_xml_md5 != 'ff70b39eebf96026ac86bba42e9b2fe8':
        passed = False
        Logger().error(test_name + str(msg + abs_path + '/' + app_files[0]))
    app_rst = abs_path + '/' + app_files[1]
    app_rst_md5 = hashlib.md5(open(app_rst, 'rb').read()).hexdigest()
    if app_rst_md5 != '44ea7c3b1017a490baea7b8986cac2a8':
        passed = False
        Logger().error(test_name + str(msg + abs_path + '/' + app_files[1]))
    app_cc = abs_path + '/' + app_files[2]
    app_cc = hashlib.md5(open(app_cc, 'rb').read()).hexdigest()
    if app_cc != 'd372382ffd06a892846b6da8f35b304a':
        passed = False
        Logger().error(test_name + str(msg + abs_path + '/' + app_files[2]))
    os.system('rm -rf ' + app_dir)
    #os.system('tree ' + app_dir)
    log_pass_fail('testing Application create()', passed)
    if passed is False:
        ret = False
    return ret
