################################
# Jobs - Build-Primitives-Core #
################################
build-primitives-core:centos7:isim:
  extends:
    - .build-primitives-core
    - .centos7
    - .isim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7


##################################
# Jobs - Build-Primitives-Assets #
##################################
build-primitives-assets:centos7:isim:
  extends:
    - .build-primitives-assets
    - .centos7
    - .isim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim


####################################
# Jobs - Build-Primitives-Inactive #
####################################
build-primitives-inactive:centos7:isim:
  extends:
    - .build-primitives-inactive
    - .centos7
    - .isim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-primitives-assets:centos7:isim


###########################
# Jobs - Build-Components #
###########################
build-components-core:centos7:isim:
  extends: 
    - .build-components-core
    - .centos7
    - .isim
  needs: 
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim

build-components-assets:centos7:isim:
  extends: 
    - .build-components-assets
    - .centos7
    - .isim
  needs:
    - job: prereq:centos7 
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-primitives-assets:centos7:isim

build-components-assets_ts:centos7:isim:
  extends: 
    - .build-components-assets_ts
    - .centos7
    - .isim
  needs:
    - job: prereq:centos7
      artifacts: true 
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-primitives-assets:centos7:isim

build-components-inactive:centos7:isim:
  extends: 
    - .build-components-inactive
    - .centos7
    - .isim
  needs:
    - job: prereq:centos7
      artifacts: true 
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-primitives-assets:centos7:isim
    - build-primitives-inactive:centos7:isim


#########################
# Jobs - Build-Adapters #
#########################
build-adapters-core:centos7:isim:
  extends: 
    - .build-adapters-core
    - .centos7
    - .isim
  needs: 
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim

build-adapters-assets:centos7:isim:
  extends: 
    - .build-adapters-assets
    - .centos7
    - .isim
  needs:
    - job: prereq:centos7 
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-primitives-assets:centos7:isim


########################
# Jobs - Build-Devices #
########################
build-devices-core:centos7:isim:
  extends: 
    - .build-devices-core
    - .centos7
    - .isim
  needs: 
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim

build-devices-assets:centos7:isim:
  extends: 
    - .build-devices-assets
    - .centos7
    - .isim
  needs:
    - job: prereq:centos7 
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-primitives-assets:centos7:isim

build-devices-assets_ts:centos7:isim:
  extends: 
    - .build-devices-assets_ts
    - .centos7
    - .isim
  needs:
    - job: prereq:centos7
      artifacts: true 
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-primitives-assets:centos7:isim

build-devices-inactive:centos7:isim:
  extends: 
    - .build-devices-inactive
    - .centos7
    - .isim
  needs:
    - job: prereq:centos7
      artifacts: true 
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-primitives-assets:centos7:isim


######################
# Jobs - Build-Cards #
######################
build-cards-core:centos7:isim:
  extends: 
    - .build-cards-core
    - .centos7
    - .isim
  needs: 
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim

build-cards-assets:centos7:isim:
  extends: 
    - .build-cards-assets
    - .centos7
    - .isim
  needs:
    - job: prereq:centos7 
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-primitives-assets:centos7:isim

build-cards-inactive:centos7:isim:
  extends: 
    - .build-cards-inactive
    - .centos7
    - .isim
  needs:
    - job: prereq:centos7 
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-primitives-assets:centos7:isim


##########################
# Jobs - Build-Platforms #
##########################
build-platforms-core:centos7:isim:
  extends: 
    - .build-platforms-core
    - .centos7
    - .isim
  needs: 
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-devices-core:centos7:isim
    - build-cards-core:centos7:isim
    - build-adapters-core:centos7:isim
    - build-components-core:centos7:isim

build-platforms-assets:centos7:isim:
  extends: 
    - .build-platforms-assets
    - .centos7
    - .isim
  needs: 
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-assets:centos7:isim
    - build-devices-assets:centos7:isim
    - build-cards-assets:centos7:isim
    - build-adapters-assets:centos7:isim
    - build-components-assets:centos7:isim
    - build-primitives-core:centos7:isim
    - build-devices-core:centos7:isim

build-platforms-inactive:centos7:isim:
  extends: 
    - .build-platforms-inactive
    - .centos7
    - .isim
  needs: 
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-inactive:centos7:isim
    - build-devices-inactive:centos7:isim
    - build-cards-inactive:centos7:isim
    - build-components-inactive:centos7:isim
    - build-primitives-core:centos7:isim
    - build-primitives-assets:centos7:isim


#####################
# Jobs - Assemblies #
#####################
build-assemblies-assets:centos7:isim:
  extends: 
    - .build-assemblies-assets
    - .centos7
    - .isim
  needs:
    - job: prereq:centos7 
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-platforms-core:centos7:isim
    - build-primitives-assets:centos7:isim
    - build-platforms-assets:centos7:isim

build-assemblies-assets_ts:centos7:isim:
  extends: 
    - .build-assemblies-assets_ts
    - .centos7
    - .isim
  needs:
    - job: prereq:centos7 
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-platforms-core:centos7:isim
    - build-primitives-assets:centos7:isim
    - build-components-assets_ts:centos7:isim

build-assemblies-inactive:centos7:isim:
  extends: 
    - .build-assemblies-inactive
    - .centos7
    - .isim
  needs:
    - job: prereq:centos7 
      artifacts: true
    - build:centos7
    - build-platforms-inactive:centos7:isim
    - build-primitives-core:centos7:isim
    - build-primitives-assets:centos7:isim


###############
# Jobs - Test #
###############
test-core:centos7:isim:
  extends:
    - .test-core
    - .centos7
    - .isim
  needs: 
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-platforms-core:centos7:isim
  script:
    - source ./cdk/opencpi-setup.sh -e
    - ocpidev build test -d projects/core --$MODEL-platform $PLATFORM
    - ocpidev run test backpressure -d projects/core --only-platform isim
    - ocpidev run test metadata_stressor -d projects/core --only-platform isim

test-assets-base:centos7:isim:
  extends:
    - .test-assets-base
    - .centos7
    - .isim
  needs: 
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-platforms-core:centos7:isim
    - build-primitives-assets:centos7:isim
    - build-platforms-assets:centos7:isim

test-assets-comms:centos7:isim:
  extends:
    - .test-assets-comms
    - .centos7
    - .isim
  needs: 
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-platforms-core:centos7:isim
    - build-primitives-assets:centos7:isim
    - build-platforms-assets:centos7:isim

test-assets-dsp:centos7:isim:
  extends:
    - .test-assets-dsp
    - .centos7
    - .isim
  needs: 
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-platforms-core:centos7:isim
    - build-primitives-assets:centos7:isim
    - build-platforms-assets:centos7:isim

test-assets-misc:centos7:isim:
  extends:
    - .test-assets-misc
    - .centos7
    - .isim
  needs: 
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-platforms-core:centos7:isim
    - build-primitives-assets:centos7:isim
    - build-platforms-assets:centos7:isim
  script:
    - source ./cdk/opencpi-setup.sh -e
    - ocpidev build test -d projects/assets/components/misc_comps --$MODEL-platform $PLATFORM
    - >
      for f in $(find projects/assets/components/misc_comps/ -maxdepth 1 -type d -name "*.test" -not -name "cdc_*"); do 
        ocpidev run test "$(basename "$f" .test)" -d projects/assets/components/misc_comps --only-platform isim; 
      done

test-assets-util:centos7:isim:
  extends:
    - .test-assets-util
    - .centos7
    - .isim
  needs: 
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-platforms-core:centos7:isim
    - build-primitives-assets:centos7:isim
    - build-platforms-assets:centos7:isim

test-assets_ts:centos7:isim:
  extends:
    - .test-assets_ts
    - .centos7
    - .isim
  needs: 
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-platforms-core:centos7:isim
    - build-primitives-assets:centos7:isim
    - build-components-assets_ts:centos7:isim
  script:
    - source ./cdk/opencpi-setup.sh -e
    - ocpidev build test -d projects/assets_ts --$MODEL-platform $PLATFORM
    - >
      for f in $(find opencpi/projects/assets_ts/components -maxdepth 1 -type d -name "*.test" -not -name "complex_mixer_ts.test"); do 
        ocpidev run test "$(basename "$f" .test)" -d projects/assets_ts/components --only-platform isim; 
      done

test-inactive:centos7:isim:
  extends:
    - .test-inactive
    - .centos7
    - .isim
  needs: 
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:isim
    - build-primitives-assets:centos7:isim
    - build-platforms-inactive:centos7:isim