################################
# Jobs - Build-Primitives-Core #
################################
build-primitives:centos7:matchstiq_z1:
  extends:
    - .build-primitives
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7


###########################
# Jobs - Build-Components #
###########################
build-components-core:centos7:matchstiq_z1:
  extends:
    - .build-components-core
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1

build-components-assets:centos7:matchstiq_z1:
  extends:
    - .build-components-assets
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1

build-components-assets_ts:centos7:matchstiq_z1:
  extends:
    - .build-components-assets_ts
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1

build-components-inactive:centos7:matchstiq_z1:
  extends:
    - .build-components-inactive
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1


#########################
# Jobs - Build-Adapters #
#########################
build-adapters-core:centos7:matchstiq_z1:
  extends:
    - .build-adapters-core
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1

build-adapters-assets:centos7:matchstiq_z1:
  extends:
    - .build-adapters-assets
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1


########################
# Jobs - Build-Devices #
########################
build-devices-core:centos7:matchstiq_z1:
  extends:
    - .build-devices-core
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1

build-devices-platform:centos7:matchstiq_z1:
  extends: 
    - .build-devices-platform
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7 
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1

build-devices-assets:centos7:matchstiq_z1:
  extends:
    - .build-devices-assets
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1

build-devices-assets_ts:centos7:matchstiq_z1:
  extends:
    - .build-devices-assets_ts
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1

build-devices-inactive:centos7:matchstiq_z1:
  extends:
    - .build-devices-inactive
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1


######################
# Jobs - Build-Cards #
######################
build-cards-core:centos7:matchstiq_z1:
  extends:
    - .build-cards-core
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1

build-cards-platform:centos7:matchstiq_z1:
  extends: 
    - .build-cards-platform
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7 
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1

build-cards-assets:centos7:matchstiq_z1:
  extends:
    - .build-cards-assets
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1

build-cards-inactive:centos7:matchstiq_z1:
  extends:
    - .build-cards-inactive
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1


##########################
# Jobs - Build-Platforms #
##########################
build-platforms-core:centos7:matchstiq_z1:
  extends:
    - .build-platforms-core
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1
    - build-devices-core:centos7:matchstiq_z1
    - build-cards-core:centos7:matchstiq_z1
    - build-adapters-core:centos7:matchstiq_z1
    - build-components-core:centos7:matchstiq_z1

build-platforms-platform:centos7:matchstiq_z1:
  extends: 
    - .build-platforms-platform
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs: 
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-devices-platform:centos7:matchstiq_z1
    - build-cards-platform:centos7:matchstiq_z1
    - build-primitives:centos7:matchstiq_z1
    - build-devices-core:centos7:matchstiq_z1

build-platforms-assets:centos7:matchstiq_z1:
  extends:
    - .build-platforms-assets
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-devices-platform:centos7:matchstiq_z1
    - build-cards-platform:centos7:matchstiq_z1
    - build-primitives:centos7:matchstiq_z1
    - build-devices-assets:centos7:matchstiq_z1
    - build-cards-assets:centos7:matchstiq_z1
    - build-adapters-assets:centos7:matchstiq_z1
    - build-components-assets:centos7:matchstiq_z1
    - build-devices-core:centos7:matchstiq_z1

build-platforms-inactive:centos7:matchstiq_z1:
  extends:
    - .build-platforms-inactive
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1
    - build-devices-inactive:centos7:matchstiq_z1
    - build-cards-inactive:centos7:matchstiq_z1
    - build-components-inactive:centos7:matchstiq_z1


#####################
# Jobs - Assemblies #
#####################
build-assemblies-platform:centos7:matchstiq_z1:
  extends: 
    - .build-assemblies-platform
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7 
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1
    - build-platforms-core:centos7:matchstiq_z1
    - build-platforms-platform:centos7:matchstiq_z1

build-assemblies-assets:centos7:matchstiq_z1:
  extends:
    - .build-assemblies-assets
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1
    - build-platforms-core:centos7:matchstiq_z1
    - build-platforms-platform:centos7:matchstiq_z1
    - build-platforms-assets:centos7:matchstiq_z1

build-assemblies-assets_ts:centos7:matchstiq_z1:
  extends:
    - .build-assemblies-assets_ts
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1
    - build-platforms-core:centos7:matchstiq_z1
    - build-platforms-platform:centos7:matchstiq_z1
    - build-platforms-assets:centos7:matchstiq_z1
    - build-components-assets_ts:centos7:matchstiq_z1
    - build-devices-assets_ts:centos7:matchstiq_z1

build-assemblies-inactive:centos7:matchstiq_z1:
  extends:
    - .build-assemblies-inactive
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1
    - build-platforms-core:centos7:matchstiq_z1
    - build-platforms-platform:centos7:matchstiq_z1
    - build-platforms-assets:centos7:matchstiq_z1
    - build-platforms-inactive:centos7:matchstiq_z1


#####################
# Jobs - Build-Test #
#####################
test-core:centos7:matchstiq_z1:
  extends:
    - .test-core
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1
    - build-platforms-core:centos7:matchstiq_z1
    - build-platforms-assets:centos7:matchstiq_z1

test-assets-base:centos7:matchstiq_z1:
  extends:
    - .test-assets-base
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1
    - build-platforms-core:centos7:matchstiq_z1
    - build-platforms-platform:centos7:matchstiq_z1
    - build-platforms-assets:centos7:matchstiq_z1

test-assets-comms:centos7:matchstiq_z1:
  extends:
    - .test-assets-comms
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1
    - build-platforms-core:centos7:matchstiq_z1
    - build-platforms-platform:centos7:matchstiq_z1
    - build-platforms-assets:centos7:matchstiq_z1

test-assets-dsp:centos7:matchstiq_z1:
  extends:
    - .test-assets-dsp
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1
    - build-platforms-core:centos7:matchstiq_z1
    - build-platforms-platform:centos7:matchstiq_z1
    - build-platforms-assets:centos7:matchstiq_z1

test-assets-misc:centos7:matchstiq_z1:
  extends:
    - .test-assets-misc
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1
    - build-platforms-core:centos7:matchstiq_z1
    - build-platforms-platform:centos7:matchstiq_z1
    - build-platforms-assets:centos7:matchstiq_z1

test-assets-util:centos7:matchstiq_z1:
  extends:
    - .test-assets-util
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1
    - build-platforms-core:centos7:matchstiq_z1
    - build-platforms-platform:centos7:matchstiq_z1
    - build-platforms-assets:centos7:matchstiq_z1

test-assets_ts:centos7:matchstiq_z1:
  extends:
    - .test-assets_ts
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1
    - build-platforms-core:centos7:matchstiq_z1
    - build-platforms-platform:centos7:matchstiq_z1
    - build-platforms-assets:centos7:matchstiq_z1
    - build-components-assets_ts:centos7:matchstiq_z1
    - build-devices-assets_ts:centos7:matchstiq_z1

test-inactive:centos7:matchstiq_z1:
  extends:
    - .test-inactive
    - .centos7
    - .matchstiq_z1-xilinx13_3
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives:centos7:matchstiq_z1
    - build-platforms-inactive:centos7:matchstiq_z1
