################################
# Jobs - Build-Primitives-Core #
################################
build-primitives-core:centos7:xsim:
  extends:
    - .build-primitives-core
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7


##################################
# Jobs - Build-Primitives-Assets #
##################################
build-primitives-assets:centos7:xsim:
  extends:
    - .build-primitives-assets
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim


####################################
# Jobs - Build-Primitives-Inactive #
####################################
build-primitives-inactive:centos7:xsim:
  extends:
    - .build-primitives-inactive
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-primitives-assets:centos7:xsim


###########################
# Jobs - Build-Components #
###########################
build-components-core:centos7:xsim:
  extends:
    - .build-components-core
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim

build-components-assets:centos7:xsim:
  extends:
    - .build-components-assets
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-primitives-assets:centos7:xsim

build-components-assets_ts:centos7:xsim:
  extends:
    - .build-components-assets_ts
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-primitives-assets:centos7:xsim

build-components-inactive:centos7:xsim:
  extends:
    - .build-components-inactive
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-primitives-assets:centos7:xsim
    - build-primitives-inactive:centos7:xsim


#########################
# Jobs - Build-Adapters #
#########################
build-adapters-core:centos7:xsim:
  extends:
    - .build-adapters-core
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim

build-adapters-assets:centos7:xsim:
  extends:
    - .build-adapters-assets
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-primitives-assets:centos7:xsim


########################
# Jobs - Build-Devices #
########################
build-devices-core:centos7:xsim:
  extends:
    - .build-devices-core
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim

build-devices-assets:centos7:xsim:
  extends:
    - .build-devices-assets
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-primitives-assets:centos7:xsim

build-devices-assets_ts:centos7:xsim:
  extends:
    - .build-devices-assets_ts
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-primitives-assets:centos7:xsim

build-devices-inactive:centos7:xsim:
  extends:
    - .build-devices-inactive
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-primitives-assets:centos7:xsim


######################
# Jobs - Build-Cards #
######################
build-cards-core:centos7:xsim:
  extends:
    - .build-cards-core
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim

build-cards-assets:centos7:xsim:
  extends:
    - .build-cards-assets
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-primitives-assets:centos7:xsim

build-cards-inactive:centos7:xsim:
  extends:
    - .build-cards-inactive
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-primitives-assets:centos7:xsim


##########################
# Jobs - Build-Platforms #
##########################
build-platforms-core:centos7:xsim:
  extends:
    - .build-platforms-core
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-devices-core:centos7:xsim
    - build-cards-core:centos7:xsim
    - build-adapters-core:centos7:xsim
    - build-components-core:centos7:xsim

build-platforms-assets:centos7:xsim:
  extends:
    - .build-platforms-assets
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-assets:centos7:xsim
    - build-devices-assets:centos7:xsim
    - build-cards-assets:centos7:xsim
    - build-adapters-assets:centos7:xsim
    - build-components-assets:centos7:xsim
    - build-primitives-core:centos7:xsim
    - build-devices-core:centos7:xsim

build-platforms-inactive:centos7:xsim:
  extends:
    - .build-platforms-inactive
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-inactive:centos7:xsim
    - build-devices-inactive:centos7:xsim
    - build-cards-inactive:centos7:xsim
    - build-components-inactive:centos7:xsim
    - build-primitives-core:centos7:xsim
    - build-primitives-assets:centos7:xsim


#####################
# Jobs - Assemblies #
#####################
build-assemblies-assets:centos7:xsim:
  extends:
    - .build-assemblies-assets
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-platforms-core:centos7:xsim
    - build-primitives-assets:centos7:xsim
    - build-platforms-assets:centos7:xsim

build-assemblies-assets_ts:centos7:xsim:
  extends:
    - .build-assemblies-assets_ts
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-platforms-core:centos7:xsim
    - build-primitives-assets:centos7:xsim
    - build-components-assets_ts:centos7:xsim

build-assemblies-inactive:centos7:xsim:
  extends:
    - .build-assemblies-inactive
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-platforms-inactive:centos7:xsim
    - build-primitives-core:centos7:xsim
    - build-primitives-assets:centos7:xsim


#####################
# Jobs - Build-Test #
#####################
test-core:centos7:xsim:
  extends:
    - .test-core
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-platforms-core:centos7:xsim

test-assets-base:centos7:xsim:
  extends:
    - .test-assets-base
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-platforms-core:centos7:xsim
    - build-primitives-assets:centos7:xsim
    - build-platforms-assets:centos7:xsim

test-assets-comms:centos7:xsim:
  extends:
    - .test-assets-comms
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-platforms-core:centos7:xsim
    - build-primitives-assets:centos7:xsim
    - build-platforms-assets:centos7:xsim

test-assets-dsp:centos7:xsim:
  extends:
    - .test-assets-dsp
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-platforms-core:centos7:xsim
    - build-primitives-assets:centos7:xsim
    - build-platforms-assets:centos7:xsim

test-assets-misc:centos7:xsim:
  extends:
    - .test-assets-misc
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-platforms-core:centos7:xsim
    - build-primitives-assets:centos7:xsim
    - build-platforms-assets:centos7:xsim

test-assets-util:centos7:xsim:
  extends:
    - .test-assets-util
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-platforms-core:centos7:xsim
    - build-primitives-assets:centos7:xsim
    - build-platforms-assets:centos7:xsim

test-assets_ts:centos7:xsim:
  extends:
    - .test-assets_ts
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-platforms-core:centos7:xsim
    - build-primitives-assets:centos7:xsim
    - build-components-assets_ts:centos7:xsim

test-inactive:centos7:xsim:
  extends:
    - .test-inactive
    - .centos7
    - .xsim
  needs:
    - job: prereq:centos7
      artifacts: true
    - build:centos7
    - build-primitives-core:centos7:xsim
    - build-primitives-assets:centos7:xsim
    - build-platforms-inactive:centos7:xsim