# This file is protected by Copyright. Please refer to the COPYRIGHT file
# distributed with this source distribution.
#
# This file is part of OpenCPI <http://www.opencpi.org>
#
# OpenCPI is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# OpenCPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

# Specified cases so unit test will pass. Remove when cases are reworked/fixed
Cases=case00.00 case00.01 case00.02 case00.03 case00.04 case00.05 case00.06 case00.07 case00.08 case00.09 case00.10 case00.11 case00.12 case01.00 case01.01 case01.02 case01.03 case01.04 case01.06 case01.07 case01.08 case01.09 case01.11 case01.12

include $(OCPI_CDK_DIR)/include/test.mk
