workflow:
  rules:
    - if: '$CI_COMMIT_TAG' 
    # Always run pipelines for tags
      when: always
    - if: '$CI_COMMIT_REF_NAME == "develop"' 
    # Always run pipelines for develop
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push"' 
    # Never run pipelines for pushes (except for develop and tags)
      when: never
    - when: always # Run for all other conditions

include:
  - .gitlab-ci/yaml/docs.yml
  - .gitlab-ci/yaml/report.yml

stages:
  - packages
  - prereqs
  - build
  - test
  - deploy
  - generate-projects
  - trigger-projects
  - generate-children
  - trigger-children
  - report

variables:
  GIT_STRATEGY: none
  CI_OCPI_ROOT_PIPELINE_ID: $CI_PIPELINE_ID
  CI_OCPI_ARTIFACTS_DIR : "${CI_PROJECT_DIR}/.gitlab-ci/artifacts"
  CI_OCPI_HOST:
    description: 'Host platform to install opencpi onto. The base docker image used in pipelines.'
    value: 'centos7'
  CI_OCPI_PLATFORMS: 
    description: 'Platforms to build and test OpenCPI for. Separated by comma and/or space.'
    value: 'zed, xsim, xilinx19_2_aarch32'
  CI_OCPI_PROJECTS: 
    description: 'Package IDs of projects to include when installing OpenCPI. Separated by comma and/or space.'
    value: ''

.build:
  image: "${CI_OCPI_CONTAINER_REGISTRY}/${CI_OCPI_HOST}.packages:${CI_PIPELINE_ID}"
  tags: ['eks', 'aws', 'opencpi']
  variables:
    KUBERNETES_CPU_REQUEST: '4'
    KUBERNETES_CPU_LIMIT: '4'
    KUBERNETES_MEMORY_REQUEST: '8Gi'
    KUBERNETES_MEMORY_LIMIT: '8Gi'
  before_script:
    - source ./cdk/opencpi-setup.sh -r

.deploy:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  tags: ['eks', 'aws', 'opencpi']
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    KUBERNETES_CPU_REQUEST: '4'
    KUBERNETES_CPU_LIMIT: '4'
    KUBERNETES_MEMORY_REQUEST: '8Gi'
    KUBERNETES_MEMORY_LIMIT: '8Gi'
  before_script:
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $CI_OCPI_CONTAINER_REGISTRY

install-packages:
  extends: .deploy
  stage: packages
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 1
  script:
  - > 
    docker build . -f ".gitlab-ci/dockerfiles/${CI_OCPI_HOST}.dockerfile" 
    -t "${CI_OCPI_CONTAINER_REGISTRY}/${CI_OCPI_HOST}.packages:${CI_PIPELINE_ID}"
  - docker push "${CI_OCPI_CONTAINER_REGISTRY}/${CI_OCPI_HOST}.packages:${CI_PIPELINE_ID}"
  rules:
    - if: '$CI_PIPELINE_SOURCE != "web"'
      when: manual
    - if: $CI_OCPI_HOST
      when: on_success
    - when: never
  allow_failure: false

install-prereqs:
  extends: .build
  stage: prereqs
  variables:
    GIT_STRATEGY: clone
  before_script: []
  script:
    - scripts/install-prerequisites.sh
  rules:
    - if: $CI_OCPI_HOST
      when: on_success
    - when: never

build-opencpi:
  extends: .build
  stage: build
  before_script: []
  script:
    - scripts/build-opencpi.sh
  rules:
    - if: $CI_OCPI_HOST
      when: on_success
    - when: never

test-opencpi:
  extends: .build
  stage: test
  before_script: []
  script:
    - scripts/test-opencpi.sh --no-hdl
  rules:
    - if: $CI_OCPI_HOST
      when: on_success
    - when: never

deploy:
  extends: .deploy
  stage: deploy
  variables:
    CI_OCPI_PUBLIC_IMAGE: "${CI_REGISTRY_IMAGE}/${CI_OCPI_HOST}.framework:${CI_COMMIT_REF_SLUG}"
    CI_OCPI_PRIVATE_IMAGE: "${CI_OCPI_CONTAINER_REGISTRY}/${CI_OCPI_HOST}.framework:${CI_PIPELINE_ID}"
    CI_OCPI_FROM_IMAGE: "${CI_OCPI_CONTAINER_REGISTRY}/${CI_OCPI_HOST}.packages:${CI_PIPELINE_ID}"
  script:
    - >
      docker build . -f .gitlab-ci/dockerfiles/deploy.dockerfile 
      -t "${CI_OCPI_PRIVATE_IMAGE}"
      --build-arg IMAGE="${CI_OCPI_FROM_IMAGE}"
      --build-arg TAG="$CI_PIPELINE_ID"
    - docker push "${CI_OCPI_PRIVATE_IMAGE}"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag "${CI_OCPI_PRIVATE_IMAGE}" "${CI_OCPI_PUBLIC_IMAGE}"
    - docker push "${CI_OCPI_PUBLIC_IMAGE}"
  rules:
    - if: $CI_OCPI_HOST != "" && ($CI_COMMIT_TAG || $CI_COMMIT_REF_SLUG == "develop")
      when: on_success
    - when: never

generate-projects:
  extends: .build
  stage: generate-projects
  dependencies: ['test-opencpi']
  script:
    - python3 .gitlab-ci/scripts/generate_pipeline.py projects
  artifacts:
    paths:
      - $CI_OCPI_ARTIFACTS_DIR
  rules:
    - if: $CI_OCPI_PROJECTS && $CI_OCPI_PROJECTS != "" && $CI_OCPI_HOST != ""
      when: on_success
    - when: never

trigger-projects:
  stage: trigger-projects
  variables: 
    CI_OCPI_ROOT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger:
    include:
      - artifact: "${CI_OCPI_ARTIFACTS_DIR}/projects.yml"
        job: generate-projects
    forward:
      yaml_variables: true
      pipeline_variables: true
    strategy: depend
  rules:
    - if: $CI_OCPI_PROJECTS && $CI_OCPI_PROJECTS != "" && $CI_OCPI_HOST != ""
      when: on_success
    - when: never

generate-children:
  extends: .build
  stage: generate-children
  dependencies: ['test-opencpi']
  script:
    - python3 .gitlab-ci/scripts/generate_pipeline.py children
  artifacts:
    paths:
      - $CI_OCPI_ARTIFACTS_DIR
  rules:
    - if: $CI_OCPI_PLATFORMS != "" && $CI_OCPI_HOST != ""
      when: on_success
    - when: never

trigger-children:
  stage: trigger-children
  variables: 
    CI_OCPI_ROOT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger:
    include:
      - artifact: "${CI_OCPI_ARTIFACTS_DIR}/children.yml"
        job: generate-children
    forward:
      yaml_variables: true
      pipeline_variables: true
    strategy: depend
  rules:
    - if: $CI_OCPI_PLATFORMS != "" && $CI_OCPI_HOST != ""
      when: on_success
    - when: never
