build:pages:
  stage: build
  tags:
    - docker
  image: $CI_REGISTRY_IMAGE/build-pages:latest
  dependencies: []
  before_script: []
  script:
    - make doc
    - mkdir -p .public/releases/${CI_COMMIT_REF_NAME//\//-}/docs/
    - mv doc/pdfs/* .public/releases/${CI_COMMIT_REF_NAME//\//-}/docs/
  after_script: []
  artifacts:
    paths:
      - .public/

trigger-downstream:
  stage: deploy
  tags:
    - docker
  image: $CI_REGISTRY_IMAGE/build-pages:latest
  only:
    - develop
    - tags
  dependencies: []
  before_script: []
  script:
    - >
      curl --request POST 
      --form token=$CI_JOB_TOKEN
      --form ref=develop
      --form "variables[JOB_ID]=$CI_JOB_ID"
      https://gitlab.com/api/v4/projects/16024285/trigger/pipeline
  after_script: []
  artifacts:
    paths:
      - .public/

# This just redirects gitlab.com/opencpi to opencpi.gitlab.io/releases/develop
pages:
  stage: deploy
  tags:
   - docker
  image: centos:latest
  only:
   - develop
  dependencies: []
  before_script: []
  script:
    - mv .gitlab/public/ .
  after_script: []
  artifacts:
    paths:
      - public/
