build:pages:
  stage: build
  tags:
    - docker
  image: $CI_REGISTRY_IMAGE/build-pages:latest
  artifacts:
    paths:
      - .public/
  # Overwrite default before and after script
  before_script: []
  after_script: []
  dependencies:
  script:
    - make doc
    - mkdir -p .public/releases/${CI_COMMIT_REF_NAME//\//-}/docs/
    - mv doc/pdfs/* .public/releases/${CI_COMMIT_REF_NAME//\//-}/docs/


trigger-downstream:
  stage: deploy
  tags:
    - docker
  image: $CI_REGISTRY_IMAGE/build-pages:latest
  artifacts:
    paths:
      - .public/
  before_script: []
  after_script: []
  only:
    - develop
    - tags
  script:
    - >
      curl --request POST 
      --form token=$CI_JOB_TOKEN
      --form ref=develop
      --form "variables[JOB_ID]=$CI_JOB_ID"
      https://gitlab.com/api/v4/projects/16024285/trigger/pipeline

