build:pages:
  stage: build
  tags:
    - docker
  image: $CI_REGISTRY_IMAGE/build-pages:latest
  artifacts:
    paths:
      - .public/
  # Overwrite default before and after script
  before_script: []
  after_script: []
  dependencies:
  script:
    - make doc
    - mkdir -p .public/releases/${CI_COMMIT_REF_NAME//\//-}/docs/
    - mv doc/pdfs/* .public/releases/${CI_COMMIT_REF_NAME//\//-}/docs/

# Trigger downstream pipeline in opencpi.gitlab.io project
trigger:opencpi.gitlab.io:
  stage: deploy
  only:
    - develop
    - master
    - tags
  trigger:
    project: opencpi/opencpi.gitlab.io
    branch: develop
    strategy: depend
  variables:
    JOB_NAME: 'build:pages'
    REF_NAME: $CI_COMMIT_REF_NAME
    PIPELINE_ID: $CI_PIPELINE_ID
    PROJECT_ID: $CI_PROJECT_ID
    PROJECT_PATH: $CI_PROJECT_PATH
