centos7:e31x:
  rules:
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PLATFORMS =~ /(^| |:|,)(e31x)( |:|,|$)/i && $CI_PIPELINE_SOURCE == "schedule" '
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PLATFORMS =~ /(^| |:|,)(e31x)( |:|,|$)/i && $CI_PIPELINE_SOURCE == "web" '
  - if: '$CI_MR_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_MR_PLATFORMS =~ /(^| |:|,)(e31x)( |:|,|$)/i && $CI_PIPELINE_SOURCE == "merge_request_event" '
  - if: '$CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)* +(centos7)( \S*)*\]/i && $CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)*( +|:|,)(e31x)(( |:|,)\S*)*\]/i && $CI_PIPELINE_SOURCE == "push" '
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PLATFORMS =~ /(^| |:|,)(e31x)( |:|,|$)/i && $CI_COMMIT_MESSAGE !~ /\[ *ci.*\]/i && $CI_PIPELINE_SOURCE == "push" '
  stage: trigger-children
  trigger:
    include:
    - artifact: .gitlab-ci/yaml-downstream
      job: generate-children:centos7:e31x
    strategy: depend
generate-children:centos7:e31x:
  artifacts:
    paths:
    - .gitlab-ci/yaml-downstream
  before_script:
  - yum install git -y
  - if [ -z "$CI_UPSTREAM_ID" ]; then export REF_NAME="1347-osp-yaml-generator"; fi
  - git clone --depth 1 --single-branch --branch "$REF_NAME" "https://gitlab.com/opencpi/opencpi.git" opencpi
  - git clone --depth 1 --single-branch --branch "$CI_COMMIT_REF_NAME" "$CI_REPOSITORY_URL" "opencpi/projects/osps/${CI_PROJECT_NAME}"
  - cd opencpi
  image: centos:7
  rules:
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PLATFORMS =~ /(^| |:|,)(e31x)( |:|,|$)/i && $CI_PIPELINE_SOURCE == "schedule" '
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PLATFORMS =~ /(^| |:|,)(e31x)( |:|,|$)/i && $CI_PIPELINE_SOURCE == "web" '
  - if: '$CI_MR_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_MR_PLATFORMS =~ /(^| |:|,)(e31x)( |:|,|$)/i && $CI_PIPELINE_SOURCE == "merge_request_event" '
  - if: '$CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)* +(centos7)( \S*)*\]/i && $CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)*( +|:|,)(e31x)(( |:|,)\S*)*\]/i && $CI_PIPELINE_SOURCE == "push" '
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PLATFORMS =~ /(^| |:|,)(e31x)( |:|,|$)/i && $CI_COMMIT_MESSAGE !~ /\[ *ci.*\]/i && $CI_PIPELINE_SOURCE == "push" '
  script:
  - yum install epel-release -y
  - yum install python36-PyYAML -y
  - .gitlab-ci/scripts/ci_yaml_generator.py centos7 e31x
  stage: generate-children
  tags:
  - docker
stages:
- generate-children
- trigger-children
