build:centos7:
  after_script:
  - if [ ! -f "opencpi/.success" ]; then opencpi/.gitlab-ci/scripts/ci_artifacts.py upload "$CI_PIPELINE_ID" "$CI_JOB_NAME" -t "failed-job"; fi
  - rm -rf ./*
  before_script:
  - rm -rf ./*
  - if [ -z "$CI_UPSTREAM_ID" ]; then export CI_UPSTREAM_REF="develop"; fi
  - git clone --depth 1 --single-branch --branch "$CI_UPSTREAM_REF" "https://gitlab.com/opencpi/opencpi.git" opencpi
  - git clone --depth 1 --single-branch --branch "$CI_COMMIT_REF_NAME" "$CI_REPOSITORY_URL" "opencpi/projects/osps/${CI_PROJECT_NAME}"
  - cd opencpi
  - touch .timestamp
  - .gitlab-ci/scripts/ci_artifacts.py download "$CI_PIPELINE_ID" -i "*centos7.tar.gz" -e "build:*" "test:*" "generate-children:*" "trigger-children:*"
  - sleep 2
  - touch .timestamp
  dependencies: []
  rules:
  - if: '$CI_PIPELINE_SOURCE =~ "cross_project_pipeline|api" '
    when: never
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PIPELINE_SOURCE =~ "web|schedule" '
  - if: '$CI_MR_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PIPELINE_SOURCE == "merge_request_event" '
  - if: '$CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)* +(centos7)( \S*)*\]/i && $CI_PIPELINE_SOURCE =~ "push" '
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_COMMIT_MESSAGE !~ /\[ *ci.*\]/i && $CI_PIPELINE_SOURCE =~ "push" '
  script:
  - scripts/build-opencpi.sh centos7
  - .gitlab-ci/scripts/ci_artifacts.py upload "$CI_PIPELINE_ID" "$CI_JOB_NAME" -s .timestamp -t "successful-job"
  - touch .success
  stage: build
  tags:
  - centos7
  - shell
  - opencpi
  variables:
    GIT_STRATEGY: none
centos7:e31x:
  rules:
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PLATFORMS =~ /(^| |:|,)(e31x)( |:|,|$)/i && $CI_PIPELINE_SOURCE =~ "web|schedule" '
  - if: '$CI_MR_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_MR_PLATFORMS =~ /(^| |:|,)(e31x)( |:|,|$)/i && $CI_PIPELINE_SOURCE == "merge_request_event" '
  - if: '$CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)* +(centos7)( \S*)*\]/i && $CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)*( +|:|,)(e31x)(( |:|,)\S*)*\]/i && $CI_PIPELINE_SOURCE == "push" '
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PLATFORMS =~ /(^| |:|,)(e31x)( |:|,|$)/i && $CI_COMMIT_MESSAGE !~ /\[ *ci.*\]/i && $CI_PIPELINE_SOURCE == "push" '
  - if: '$CI_PIPELINE_SOURCE =~ "cross_project_pipeline|api" '
  stage: trigger-children
  trigger:
    include:
    - artifact: opencpi/.gitlab-ci/yaml-children/centos7-e31x.yml
      job: generate-children:centos7:e31x
    strategy: depend
generate-children:centos7:e31x:
  artifacts:
    paths:
    - opencpi/.gitlab-ci/yaml-children/centos7-e31x.yml
  before_script:
  - yum install git -y
  - if [ -z "$CI_UPSTREAM_ID" ]; then export CI_UPSTREAM_REF="develop"; fi
  - git clone --depth 1 --single-branch --branch "$CI_UPSTREAM_REF" "https://gitlab.com/opencpi/opencpi.git" opencpi
  - git clone --depth 1 --single-branch --branch "$CI_COMMIT_REF_NAME" "$CI_REPOSITORY_URL" "opencpi/projects/osps/${CI_PROJECT_NAME}"
  - cd opencpi
  image: centos:7
  rules:
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PLATFORMS =~ /(^| |:|,)(e31x)( |:|,|$)/i && $CI_PIPELINE_SOURCE =~ "web|schedule" '
  - if: '$CI_MR_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_MR_PLATFORMS =~ /(^| |:|,)(e31x)( |:|,|$)/i && $CI_PIPELINE_SOURCE == "merge_request_event" '
  - if: '$CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)* +(centos7)( \S*)*\]/i && $CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)*( +|:|,)(e31x)(( |:|,)\S*)*\]/i && $CI_PIPELINE_SOURCE == "push" '
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PLATFORMS =~ /(^| |:|,)(e31x)( |:|,|$)/i && $CI_COMMIT_MESSAGE !~ /\[ *ci.*\]/i && $CI_PIPELINE_SOURCE == "push" '
  - if: '$CI_PIPELINE_SOURCE =~ "cross_project_pipeline|api" '
  script:
  - yum install epel-release -y
  - yum install python36-PyYAML -y
  - .gitlab-ci/scripts/ci_yaml_generator.py centos7 e31x
  stage: generate-children
  tags:
  - docker
  variables:
    GIT_STRATEGY: none
prereqs:centos7:
  after_script:
  - if [ ! -f "opencpi/.success" ]; then opencpi/.gitlab-ci/scripts/ci_artifacts.py upload "$CI_PIPELINE_ID" "$CI_JOB_NAME" -t "failed-job"; fi
  - rm -rf ./*
  before_script:
  - rm -rf ./*
  - if [ -z "$CI_UPSTREAM_ID" ]; then export CI_UPSTREAM_REF="develop"; fi
  - git clone --depth 1 --single-branch --branch "$CI_UPSTREAM_REF" "https://gitlab.com/opencpi/opencpi.git" opencpi
  - git clone --depth 1 --single-branch --branch "$CI_COMMIT_REF_NAME" "$CI_REPOSITORY_URL" "opencpi/projects/osps/${CI_PROJECT_NAME}"
  - cd opencpi
  - touch .timestamp
  dependencies: []
  rules:
  - if: '$CI_PIPELINE_SOURCE =~ "cross_project_pipeline|api" '
    when: never
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PIPELINE_SOURCE =~ "web|schedule" '
  - if: '$CI_MR_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PIPELINE_SOURCE == "merge_request_event" '
  - if: '$CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)* +(centos7)( \S*)*\]/i && $CI_PIPELINE_SOURCE =~ "push" '
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_COMMIT_MESSAGE !~ /\[ *ci.*\]/i && $CI_PIPELINE_SOURCE =~ "push" '
  script:
  - scripts/install-prerequisites.sh centos7
  - .gitlab-ci/scripts/ci_artifacts.py upload "$CI_PIPELINE_ID" "$CI_JOB_NAME" -s .timestamp -t "successful-job"
  - touch .success
  stage: prereqs
  tags:
  - centos7
  - shell
  - opencpi
  variables:
    GIT_STRATEGY: none
stages:
- prereqs
- build
- test
- generate-children
- trigger-children
test:centos7:
  after_script:
  - if [ ! -f "opencpi/.success" ]; then opencpi/.gitlab-ci/scripts/ci_artifacts.py upload "$CI_PIPELINE_ID" "$CI_JOB_NAME" -t "failed-job"; fi
  - rm -rf ./*
  before_script:
  - rm -rf ./*
  - if [ -z "$CI_UPSTREAM_ID" ]; then export CI_UPSTREAM_REF="develop"; fi
  - git clone --depth 1 --single-branch --branch "$CI_UPSTREAM_REF" "https://gitlab.com/opencpi/opencpi.git" opencpi
  - git clone --depth 1 --single-branch --branch "$CI_COMMIT_REF_NAME" "$CI_REPOSITORY_URL" "opencpi/projects/osps/${CI_PROJECT_NAME}"
  - cd opencpi
  - touch .timestamp
  - .gitlab-ci/scripts/ci_artifacts.py download "$CI_PIPELINE_ID" -i "*centos7.tar.gz" -e "test:*" "generate-children:*" "trigger-children:*"
  - sleep 2
  - touch .timestamp
  - source cdk/opencpi-setup.sh -e
  dependencies: []
  rules:
  - if: '$CI_PIPELINE_SOURCE =~ "cross_project_pipeline|api" '
    when: never
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PIPELINE_SOURCE =~ "web|schedule" '
  - if: '$CI_MR_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PIPELINE_SOURCE == "merge_request_event" '
  - if: '$CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)* +(centos7)( \S*)*\]/i && $CI_PIPELINE_SOURCE =~ "push" '
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_COMMIT_MESSAGE !~ /\[ *ci.*\]/i && $CI_PIPELINE_SOURCE =~ "push" '
  script:
  - scripts/test-opencpi.sh --no-hdl
  - .gitlab-ci/scripts/ci_artifacts.py upload "$CI_PIPELINE_ID" "$CI_JOB_NAME" -s .timestamp -t "successful-job"
  - touch .success
  stage: test
  tags:
  - centos7
  - shell
  - opencpi
  variables:
    GIT_STRATEGY: none
