centos7:adi_plutosdr0_32:
  rules:
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PLATFORMS =~ /(^| |:|,)(adi_plutosdr0_32)( |:|,|$)/i && $CI_PIPELINE_SOURCE =~ "web|schedule" '
  - if: '$CI_MR_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_MR_PLATFORMS =~ /(^| |:|,)(adi_plutosdr0_32)( |:|,|$)/i && $CI_PIPELINE_SOURCE == "merge_request_event" '
  - if: '$CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)* +(centos7)( \S*)*\]/i && $CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)*( +|:|,)(adi_plutosdr0_32)(( |:|,)\S*)*\]/i && $CI_PIPELINE_SOURCE =~ "push|cross_project_pipeline|api" '
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PLATFORMS =~ /(^| |:|,)(adi_plutosdr0_32)( |:|,|$)/i && $CI_COMMIT_MESSAGE !~ /\[ *ci.*\]/i && $CI_PIPELINE_SOURCE =~ "push|cross_project_pipeline|api" '
  stage: trigger-children
  trigger:
    include:
    - artifact: opencpi/.gitlab-ci/yaml-children/centos7-adi_plutosdr0_32.yml
      job: generate-children:centos7:adi_plutosdr0_32
    strategy: depend
centos7:plutosdr:
  rules:
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PLATFORMS =~ /(^| |:|,)(plutosdr)( |:|,|$)/i && $CI_PIPELINE_SOURCE =~ "web|schedule" '
  - if: '$CI_MR_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_MR_PLATFORMS =~ /(^| |:|,)(plutosdr)( |:|,|$)/i && $CI_PIPELINE_SOURCE == "merge_request_event" '
  - if: '$CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)* +(centos7)( \S*)*\]/i && $CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)*( +|:|,)(plutosdr)(( |:|,)\S*)*\]/i && $CI_PIPELINE_SOURCE =~ "push|cross_project_pipeline|api" '
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PLATFORMS =~ /(^| |:|,)(plutosdr)( |:|,|$)/i && $CI_COMMIT_MESSAGE !~ /\[ *ci.*\]/i && $CI_PIPELINE_SOURCE =~ "push|cross_project_pipeline|api" '
  stage: trigger-children
  trigger:
    include:
    - artifact: opencpi/.gitlab-ci/yaml-children/centos7-plutosdr.yml
      job: generate-children:centos7:plutosdr
    strategy: depend
generate-children:centos7:adi_plutosdr0_32:
  artifacts:
    paths:
    - opencpi/.gitlab-ci/yaml-children/centos7-adi_plutosdr0_32.yml
  before_script:
  - yum install git -y
  - if [ -z "$CI_UPSTREAM_ID" ]; then export REF_NAME="1347-osp-yaml-generator"; fi
  - git clone --depth 1 --single-branch --branch "$REF_NAME" "https://gitlab.com/opencpi/opencpi.git" opencpi
  - git clone --depth 1 --single-branch --branch "$CI_COMMIT_REF_NAME" "$CI_REPOSITORY_URL" "opencpi/projects/osps/${CI_PROJECT_NAME}"
  - cd opencpi
  image: centos:7
  rules:
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PLATFORMS =~ /(^| |:|,)(adi_plutosdr0_32)( |:|,|$)/i && $CI_PIPELINE_SOURCE =~ "web|schedule" '
  - if: '$CI_MR_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_MR_PLATFORMS =~ /(^| |:|,)(adi_plutosdr0_32)( |:|,|$)/i && $CI_PIPELINE_SOURCE == "merge_request_event" '
  - if: '$CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)* +(centos7)( \S*)*\]/i && $CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)*( +|:|,)(adi_plutosdr0_32)(( |:|,)\S*)*\]/i && $CI_PIPELINE_SOURCE =~ "push|cross_project_pipeline|api" '
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PLATFORMS =~ /(^| |:|,)(adi_plutosdr0_32)( |:|,|$)/i && $CI_COMMIT_MESSAGE !~ /\[ *ci.*\]/i && $CI_PIPELINE_SOURCE =~ "push|cross_project_pipeline|api" '
  script:
  - yum install epel-release -y
  - yum install python36-PyYAML -y
  - .gitlab-ci/scripts/ci_yaml_generator.py centos7 adi_plutosdr0_32
  stage: generate-children
  tags:
  - docker
generate-children:centos7:plutosdr:
  artifacts:
    paths:
    - opencpi/.gitlab-ci/yaml-children/centos7-plutosdr.yml
  before_script:
  - yum install git -y
  - if [ -z "$CI_UPSTREAM_ID" ]; then export REF_NAME="1347-osp-yaml-generator"; fi
  - git clone --depth 1 --single-branch --branch "$REF_NAME" "https://gitlab.com/opencpi/opencpi.git" opencpi
  - git clone --depth 1 --single-branch --branch "$CI_COMMIT_REF_NAME" "$CI_REPOSITORY_URL" "opencpi/projects/osps/${CI_PROJECT_NAME}"
  - cd opencpi
  image: centos:7
  rules:
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PLATFORMS =~ /(^| |:|,)(plutosdr)( |:|,|$)/i && $CI_PIPELINE_SOURCE =~ "web|schedule" '
  - if: '$CI_MR_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_MR_PLATFORMS =~ /(^| |:|,)(plutosdr)( |:|,|$)/i && $CI_PIPELINE_SOURCE == "merge_request_event" '
  - if: '$CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)* +(centos7)( \S*)*\]/i && $CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)*( +|:|,)(plutosdr)(( |:|,)\S*)*\]/i && $CI_PIPELINE_SOURCE =~ "push|cross_project_pipeline|api" '
  - if: '$CI_PLATFORMS =~ /(^| )(centos7)( |$)/i && $CI_PLATFORMS =~ /(^| |:|,)(plutosdr)( |:|,|$)/i && $CI_COMMIT_MESSAGE !~ /\[ *ci.*\]/i && $CI_PIPELINE_SOURCE =~ "push|cross_project_pipeline|api" '
  script:
  - yum install epel-release -y
  - yum install python36-PyYAML -y
  - .gitlab-ci/scripts/ci_yaml_generator.py centos7 plutosdr
  stage: generate-children
  tags:
  - docker
stages:
- generate-children
- trigger-children
