# Additional data for a platform at discovery as well as overrides of 
# job values. Overrides apply to all jobs for a platform by default,
# To apply overrides to only a specific job, nest the values under the
# job name like done for 'centos7' below.
centos7:
  overrides:
    packages:centos7:
        image: centos:7
modelsim:
  overrides:
    variables:
      OCPI_MODELSIM_DIR: '/opt/Mentor/modelsim_dlx'
      OCPI_MODELSIM_LICENSE_FILE: '2103@sembach.opencpi.net'