# Additional data for a platform at discovery as well as overrides of 
# job values. Overrides apply to all jobs for a platform by default,
# To apply overrides to only a specific job, nest the values under the
# job name like done for 'centos7' below. A platform or a specific job
# can be skipped by setting its value to 'skip'.
centos7:
  overrides:
    packages:centos7:
      image: centos:7
      tags: [docker]
      script: scripts/install-packages.sh centos7
      before_script: []
      after_script: []
modelsim:
  overrides:
    variables:
      OCPI_MODELSIM_DIR: '/opt/Mentor/modelsim_dlx'
      OCPI_MODELSIM_LICENSE_FILE: '2103@sembach.opencpi.net'
isim:
  overrides:

xsim:
  overrides:


# hdl
e31x:
  ip: 10.1.0.248
  port: 1000
matchstiq_z1:
  ip: 10.1.0.203
  port: 1000
plutosdr:
  overrides:
    build-assemblies:centos7:assets_ts:assemblies:plutosdr:
      variables:
        OCPI_PROJECT_PATH: '$CI_PROJECT_DIR/opencpi/projects/assets:$CI_PROJECT_DIR/opencpi/projects/platform'
    build-tests:centos7:core:components:plutosdr:
      variables:
        OCPI_PROJECT_PATH: '$CI_PROJECT_DIR/opencpi/projects/assets:$CI_PROJECT_DIR/opencpi/projects/platform'
    build-tests:centos7:assets_ts:components:plutosdr:
      variables:
        OCPI_PROJECT_PATH: '$CI_PROJECT_DIR/opencpi/projects/assets:$CI_PROJECT_DIR/opencpi/projects/platform'
zed_ise:
  overrides:
    variables:
      OCPI_XILINX_LICENSE_FILE: '2101@sembach.opencpi.net'
