# Additional data for platforms. Supported keys:
# ip: IP address of device for HWIL
# port: port of device for HWIL
# password: ssh password of device for HWIL
# user: ssh user of device for HWIL
# variables: extra variables for jobs specific to device

# ci
ci:
  runners:
    1274481: # Centos7-01
      socket_interface: em2
    2337867: # Centos7-02
      socket_interface: ens224
    2337550: # Centos7-03
      socket_interface: ens224
    2938106: # Centos7-04
      socket_interface: ens224
    11873118: # Centos7-05
      socket_interface: ens224
    11873200: # Centos7-06
      socket_interface: ens224

# rcc
centos7:
  overrides: # deprecated
    packages:centos7:
      image: centos:7
      tags: [docker]
      script: scripts/install-packages.sh centos7
      before_script: []
      after_script: []

# sim
modelsim:
  variables:
    OCPI_MODELSIM_DIR: '/opt/Mentor/modelsim_dlx'
    OCPI_MODELSIM_LICENSE_FILE: '2103@sembach.opencpi.net'
  overrides: # deprecated; use 'variables'
    variables:
      OCPI_MODELSIM_DIR: '/opt/Mentor/modelsim_dlx'
      OCPI_MODELSIM_LICENSE_FILE: '2103@sembach.opencpi.net'

# hdl
adrv9361:
  variables:
    OCPI_XILINX_LICENSE_FILE: '2100@sembach.opencpi.net'
  overrides: # deprecated; use 'variables'
    variables:
      OCPI_XILINX_LICENSE_FILE: '2100@sembach.opencpi.net'
e31x:
  ip: 10.1.0.42
  port: 1000
matchstiq_z1:
  ip: 10.1.0.203
  port: 1000
plutosdr:
  ip: 10.1.0.102
  port: 1000
  password: analog
  deploy: False # deprecated
  variables:
    OCPI_PROJECT_PATH: '/opencpi/projects/assets:/opencpi/projects/platform'
  overrides: # deprecated; use 'variables'
    build-assemblies:centos7:assets_ts:assemblies:plutosdr:
      variables:
        OCPI_PROJECT_PATH: '$CI_PROJECT_DIR/projects/assets:$CI_PROJECT_DIR/projects/platform'
    build-tests:centos7:core:components:plutosdr:
      variables:
        OCPI_PROJECT_PATH: '$CI_PROJECT_DIR/projects/assets:$CI_PROJECT_DIR/projects/platform'
    build-tests:centos7:assets_ts:components:plutosdr:
      variables:
        OCPI_PROJECT_PATH: '$CI_PROJECT_DIR/projects/assets:$CI_PROJECT_DIR/projects/platform'
zcu104:
  ip: 10.1.0.208
  port: 1000
zed:
  ip: 10.1.0.242
  port: 1000
zed_ise:
  variables:
    OCPI_XILINX_LICENSE_FILE: '2101@sembach.opencpi.net'
  overrides: # deprecated; use 'variables'
    variables:
      OCPI_XILINX_LICENSE_FILE: '2101@sembach.opencpi.net'