# Whitelist of host platforms and platforms to cross-build
centos7:
  xilinx13_3:
  xilinx13_4:
  isim:
  modelsim:
  xsim:
  matchstiq_z1:
  zcu104:
  zed:
  - xilinx13_4
  zed_ise:
  plutosdr:
  e31x:
  adi_plutosdr0_32:
  adrv9361: