#!/bin/bash
# This file is protected by Copyright. Please refer to the COPYRIGHT file
# distributed with this source distribution.
#
# This file is part of OpenCPI <http://www.opencpi.org>
#
# OpenCPI is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# OpenCPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

Target=$1
VendorDir=$2
LicenseFile=$3
XilinxCoreName="clk_wiz"
XilinxClockPrimitives="mmcm pll"

AlteraClockPrimitive="altera_pll"
AlteraPllName="pll"
AlteraDeviceFamily="Cyclone V"
AlteraFileSet="QUARTUS_SYNTH"

if [[ "$Target" == "zynq" ]]; then
  XilinxPartNumber="xc7z020-clg484-1"
  XilinxPrimVer="e2"
elif [[ "$Target" == "zynq_ultra" ]]; then
  XilinxPartNumber="xczu3cg-sbva484-1-e"
  XilinxPrimVer="e4"
fi
if [[ "$Target" == "zynq" || "$Target" == "zynq_ultra" ]]; then
  for prim in $XilinxClockPrimitives; do 
    cd vivado_ip && rm -r -f tmp && mkdir tmp &&
    cd tmp && vivado -mode batch -source ../vivado-gen-clk_wiz.tcl -tclargs $XilinxCoreName $prim ${prim}$XilinxPrimVer $XilinxPartNumber &> ../${Target}_${prim}_${XilinxCoreName}.log && cd ../ &&
    patch -F 5 < ${prim}$XilinxPrimVer.patch &&
		cp ${prim}$XilinxPrimVer.v ../../$Target/${prim}$XilinxPrimVer.v && mv ${prim}$XilinxPrimVer.v ../../xsim/${prim}$XilinxPrimVer.v &&
		rm -f ${prim}$XilinxPrimVer.v.orig && cd ../;
  done
  cd vivado_ip && date > timestamp-${Target}_${XilinxCoreName} && rm -r -f tmp;
elif [[ "$Target" == "zynq_ise" ]]; then
  for prim in $XilinxClockPrimitives; do 
    cd ise_ip && rm -r -f tmp && mkdir tmp &&
    cd tmp && coregen -b ../ise-gen-clk_wiz-${prim}-coregen-commands &> ../${Target}_${prim}_${XilinxCoreName}.log && cd ../ &&
    cp tmp/managed_ip_project/${prim}e2.vhd . && patch < ${prim}e2.patch && cp ${prim}e2.vhd ../../isim/${prim}e2.vhd &&
		mv ${prim}e2.vhd ../../$Target/${prim}e2.vhd && cd ../;
  done
  cd ise_ip && date > timestamp-${Target}_${XilinxCoreName} && rm -r -f tmp;
elif [[ "$Target" == "cyclone5" ]]; then
  export LM_LICENSE_FILE=$LicenseFile && cd quartus_ip && rm -r -f tmp && mkdir tmp &&
  cd tmp &&  $VendorDir/sopc_builder/bin/ip-generate --verbose --language=vhdl --output-directory=. --file-set=$AlteraFileSet \
  --component-name=$AlteraClockPrimitive --output-name=$AlteraPllName --system-info=DEVICE_FAMILY="$AlteraDeviceFamily" \
  --component-param=gui_reference_clock_frequency="100.0 MHz" --component-param=gui_output_clock_frequency0="100.0 MHz" \
  --component-param=gui_phase_shift0="0 ps" --component-param=gui_duty_cycle0="50" &> ../${Target}_${AlteraClockPrimitive}.log &&
  find . -name ${AlteraPllName}.v -exec mv {} ../${AlteraPllName}.v \; && cd ../ && patch -F 5 < pll.patch && rm -f ${AlteraPllName}.vhd.orig &&
  cp  ${AlteraPllName}.v ../../modelsim/${AlteraPllName}.v && mv ${AlteraPllName}.v ../../$Target/${AlteraPllName}.v &&
  date > timestamp-${Target}_${AlteraClockPrimitive} && rm -r -f tmp cyclone5_altera_pll.log &&
  #  Following what was done here to remove the sopc folders that were generated by ip-generate and not cleaned up:
  #  https://github.com/Nuand/bladeRF/blob/master/hdl/quartus/build_bladerf.sh
  find ~ -maxdepth 1 -type d -empty -iname "sopc_altera_pll*" -delete;
fi




