gitlab.io:
  stage: trigger-projects
  trigger: $CI_PROJECT_NAMESPACE/opencpi.gitlab.io
  rules:
    - !reference [.rules, docs_always]
    - when: never

# This just redirects opencpi.gitlab.io/opencpi to opencpi.gitlab.io/releases/latest
pages:
  stage: deploy
  tags:
    - docker
  image: centos:latest
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 1
  dependencies: []
  before_script: []
  script:
    - mv .gitlab/public/ .
  after_script: []
  artifacts:
    paths:
      - public/
  rules:
    - if: "$CI_COMMIT_BRANCH == 'develop'"
