workflow:
  rules:
    - when: always

stages:
  - trigger-opencpi

.bridge:
  stage: trigger-opencpi
  variables:
    CI_SOURCE_COMMIT_REF_NAME: "$CI_COMMIT_REF_NAME"
    CI_SOURCE_PROJECT_NAME: "$CI_PROJECT_NAME"

# non-tag pipeline
trigger-opencpi:
  extends: .bridge
  trigger:
    project: opencpi/opencpi
    branch: '$CI_OCPI_REF_NAME'
    strategy: depend
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - when: always

# tag pipeline
trigger-opencpi-tag:
  extends: .bridge
  trigger:
    project: opencpi/opencpi
    branch: '$CI_COMMIT_TAG'
    strategy: depend
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always
    - when: never