workflow:
  rules:
    - when: always

trigger-opencpi:
  stage: trigger-opencpi
  trigger:
    branch: 2402-ci-pipeline-reorg
    project: opencpi/opencpi
  variables:
    CI_SOURCE_REPOSITORY_URL: "$CI_REPOSITORY_URL"
    CI_SOURCE_COMMIT_REF_NAME: "$CI_COMMIT_REF_NAME"
    CI_SOURCE_PROJECT_NAME: "$CI_PROJECT_NAME"

stages:
- trigger-opencpi