workflow:
  rules:
    - when: always

stages:
  - trigger-opencpi

trigger-opencpi:
  stage: trigger-opencpi
  trigger:
    project: opencpi/opencpi
    branch: '$CI_OCPI_REF_NAME'
    strategy: depend
  variables:
    CI_SOURCE_COMMIT_REF_NAME: "$CI_COMMIT_REF_NAME"
    CI_SOURCE_PROJECT_NAME: "$CI_PROJECT_NAME"
  rules:
    - if: '$CI_COMMIT_TAG'
      variables: 
          CI_OCPI_REF_NAME: '$CI_COMMIT_TAG'
    - if: ('$CI_OCPI_REF_NAME' == null || '$CI_OCPI_REF_NAME' == '')
      variables:
          CI_OCPI_REF_NAME: develop