workflow:
  rules:
    - when: always

stages:
  - trigger-opencpi

trigger-opencpi:
  stage: trigger-opencpi
  trigger:
    branch: ${CI_COMMIT_TAG:-${CI_OCPI_REF_NAME:-develop}}
    project: opencpi/opencpi
    strategy: depend
  variables:
    CI_SOURCE_COMMIT_REF_NAME: "$CI_COMMIT_REF_NAME"
    CI_SOURCE_PROJECT_NAME: "$CI_PROJECT_NAME"