stages:
  - opencpi

opencpi:
  stage: opencpi
  variables:
    CI_OCPI_SOURCE_REF_NAME: "$CI_COMMIT_REF_NAME"
    CI_OCPI_SOURCE_COMMIT_SHA: "$CI_COMMIT_SHORT_SHA"
    PLATFORMS: $PLATFORMS
    OSPS: $CI_PROJECT_NAME
    DO_SIM: 'False'
  trigger:
    project: opencpi/opencpi
    branch: '$CI_OCPI_REF_NAME'
    strategy: depend
    forward:
      yaml_variables: true
      pipeline_variables: true