.changes:
  docs: &changes_docs
    paths:
      - ".gitlab-ci/yaml/docs.yml" # CI/CD doc jobs
      - "doc/**/*" # Everything in the doc dir
      - "tools/ocpidoc/**/*" # Everything in the ocpidoc tool
      - "**/*.rst" # All .rst files
  packages: &changes_packages
    paths: # Paths related to installing packages
      - projects/core/rcc/platforms/${CI_OCPI_HOST}/${CI_OCPI_HOST}-packages.sh
      - build/install-packages.sh
      - ".gitlab-ci/dockerfiles/*"
  framework: &changes_framework
    paths: # Paths considered framework code + .gitlab-ci
      - ".gitlab-ci.yml"
      - ".gitlab-ci/**/*"
      - bootstrap/**/*
      - build/**/*
      - os/**/*
      - packaging/**/*
      - platforms/**/*
      - project-registry/**/*
      - runtime/**/*
      - scripts/**/*
      - tests/**/*
      - tools/**/*
      - "Framework.exports"
      - "Makefile"
  platforms: &changes_platforms
    paths: # Framework code + projects + .gitlab-ci/scripts
      - ".gitlab-ci/scripts/**"
      - bootstrap/**/*
      - build/**/*
      - os/**/*
      - packaging/**/*
      - platforms/**/*
      - project-registry/**/*
      - runtime/**/*
      - scripts/**/*
      - tests/**/*
      - tools/**/*
      - projects/**/*
      - "Framework.exports"
      - "Makefile"

.conditions:
  tag_or_develop: &condition_tag_or_develop
    if: $CI_COMMIT_TAG || $CI_COMMIT_REF_SLUG == "develop"
  no_host: &condition_no_host
    if: $CI_OCPI_HOST == null || $CI_OCPI_HOST == ''
  projects: &condition_projects
    if: $CI_OCPI_PROJECTS != null && $CI_OCPI_PROJECTS != ''
  # Platforms
  platforms: &condition_platforms_true
    if: $CI_OCPI_INSTALL_PLATFORMS == 'true' && $CI_OCPI_PLATFORMS != null && $CI_OCPI_PLATFORMS != ''
  platforms_changes: &condition_platforms_changes
    if: $CI_OCPI_INSTALL_PLATFORMS != 'false' && $CI_OCPI_PLATFORMS != null && $CI_OCPI_PLATFORMS != ''
    changes:
      <<: *changes_platforms
  platforms_mr: &condition_platforms_true_mr
    if: $CI_OCPI_INSTALL_PLATFORMS == 'true' && $CI_OCPI_PLATFORMS != null && $CI_OCPI_PLATFORMS != '' && $CI_PIPELINE_SOURCE == 'merge_request_event'
  platforms_changes_mr: &condition_platforms_changes_mr
    if: $CI_OCPI_INSTALL_PLATFORMS != 'false' && $CI_OCPI_PLATFORMS != null && $CI_OCPI_PLATFORMS != '' && $CI_PIPELINE_SOURCE == 'merge_request_event'
    changes:
      <<: *changes_platforms
  # Packages
  packages_changes: &condition_packages_changes
    if: $CI_OCPI_INSTALL_PACKAGES != 'false'
    changes: 
      <<: *changes_packages
  packages_true: &condition_packages_true
    if: "$CI_OCPI_INSTALL_PACKAGES == 'true'"
  packages_changes_mr: &condition_packages_changes_mr
    if: $CI_OCPI_INSTALL_PACKAGES != 'false' && $CI_PIPELINE_SOURCE == 'merge_request_event'
    changes: 
      <<: *changes_packages
  packages_true_mr: &condition_packages_true_mr
    if: $CI_OCPI_INSTALL_PACKAGES == 'true' && $CI_PIPELINE_SOURCE == 'merge_request_event'
  # Framework
  framework_changes: &condition_framework_changes
    if: $CI_OCPI_INSTALL_FRAMEWORK != 'false'
    changes:
      <<: *changes_framework
  framework_true: &condition_framework_true
    if: "$CI_OCPI_INSTALL_FRAMEWORK == 'true'"
  framework_true_image_develop_mr: &condition_framework_true_image_develop_mr
    if: $CI_OCPI_INSTALL_FRAMEWORK == 'true' && $CI_OCPI_IMAGE_TAG == 'develop' && $CI_PIPELINE_SOURCE == 'merge_request_event'
  framework_changes_image_develop_mr: &condition_framework_changes_image_develop_mr
    if: $CI_OCPI_INSTALL_FRAMEWORK != 'false' && $CI_OCPI_IMAGE_TAG == 'develop' && $CI_PIPELINE_SOURCE == 'merge_request_event'
    changes: 
      <<: *changes_framework

.rules:
  packages_success:
  # If package job should execute, only run job using this rule on_success
    - <<: *condition_no_host
      when: never
    - <<: *condition_packages_true
      when: on_success
    - <<: *condition_packages_changes
      when: on_success
  packages_manual:
  # If package job should execute, only run job using this rule manually
    - <<: *condition_no_host
      when: never
    - <<: *condition_packages_true_mr
      when: manual
    - <<: *condition_packages_changes_mr
      when: manual
  packages_never:
  # If package job should execute, never run job using this rule
    - <<: *condition_no_host
      when: never
    - <<: *condition_packages_true
      when: never
    - <<: *condition_packages_changes
      when: never
  framework_success:
  # If framework jobs should execute, only run job using this rule on_success
    - <<: *condition_no_host
      when: never
    - <<: *condition_framework_true
      when: on_success
    - <<: *condition_framework_changes
      when: on_success
  framework_never:
  # If framework jobs should execute, never run job using this rule
    - <<: *condition_no_host
      when: never
    - <<: *condition_framework_true
      when: never
    - <<: *condition_framework_changes
      when: never
  framework_manual:
  # If framework job should execute but packages shouldn't, run job using this rule manually
    - <<: *condition_no_host
      when: never
    - <<: *condition_framework_true_image_develop_mr
      when: manual
    - <<: *condition_framework_changes_image_develop_mr
      when: manual
  platforms_always:
  # If platforms are to be built for, always run job using this rule
    - <<: *condition_no_host
      when: never
    - <<: *condition_platforms_true
      when: always
    - <<: *condition_platforms_changes
      when: always
  platforms_manual:
  # If platforms are to be built for, run job using this rule manually
    - <<: *condition_no_host
      when: never
    - <<: *condition_platforms_true_mr
      when: manual
    - <<: *condition_platforms_changes_mr
      when: manual
  projects_always:
  # If projects are to be built for, always run job using this rule
    - <<: *condition_no_host
      when: never
    - <<: *condition_projects
      when: always
  image_tag:
  # Set jobs to use the image created by the packages job
    - <<: *condition_packages_true
      variables:
        CI_OCPI_IMAGE_TAG: $CI_PIPELINE_ID
    - <<: *condition_packages_changes
      variables:
        CI_OCPI_IMAGE_TAG: $CI_PIPELINE_ID
  deploy_framework_success:
  # If the framework is to be deployed, run job using this rule on success
    - <<: *condition_no_host
      when: never
    - <<: *condition_tag_or_develop
      when: on_success
  docs_always:
  # If docs are to be built, always run job using this rule
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables: # Tell docs job to use MR source project (may be external)
        CI_UPSTREAM_COMMIT_REF: "$CI_COMMIT_REF_NAME"
        CI_UPSTREAM_PROJECT_URL: "$CI_MERGE_REQUEST_SOURCE_PROJECT_URL"
        CI_UPSTREAM_COMMIT_TAG: "$CI_COMMIT_TAG"
      changes:
        <<: *changes_docs
      when: always
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"
      variables:
        CI_UPSTREAM_COMMIT_REF: "$CI_COMMIT_REF_NAME"
        CI_UPSTREAM_PROJECT_URL: "$CI_PROJECT_URL"
        CI_UPSTREAM_COMMIT_TAG: "$CI_COMMIT_TAG"
      changes:
        <<: *changes_docs
      when: always
