.zed-centos6:
  extends:
    - .zed
  tags:
    - opencpi
    - centos6
    - zed
    - shell

################################
# Jobs - Build-Primitives-Core #
################################
build-primitives:centos6:zed:
  extends:
    - .build-primitives
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6


###########################
# Jobs - Build-Components #
###########################
build-components-core:centos6:zed:
  extends:
    - .build-components-core
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed

build-components-assets:centos6:zed:
  extends:
    - .build-components-assets
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed

build-components-assets_ts:centos6:zed:
  extends:
    - .build-components-assets_ts
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed

build-components-inactive:centos6:zed:
  extends:
    - .build-components-inactive
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed


#########################
# Jobs - Build-Adapters #
#########################
build-adapters-core:centos6:zed:
  extends:
    - .build-adapters-core
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed

build-adapters-assets:centos6:zed:
  extends:
    - .build-adapters-assets
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed


########################
# Jobs - Build-Devices #
########################
build-devices-core:centos6:zed:
  extends:
    - .build-devices-core
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed

build-devices-platform:centos6:zed:
  extends: 
    - .build-devices-platform
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed

build-devices-assets:centos6:zed:
  extends:
    - .build-devices-assets
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed

build-devices-assets_ts:centos6:zed:
  extends:
    - .build-devices-assets_ts
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed

build-devices-inactive:centos6:zed:
  extends:
    - .build-devices-inactive
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed


######################
# Jobs - Build-Cards #
######################
build-cards-core:centos6:zed:
  extends:
    - .build-cards-core
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed

build-cards-assets:centos6:zed:
  extends:
    - .build-cards-assets
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed

build-cards-inactive:centos6:zed:
  extends:
    - .build-cards-inactive
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed


##########################
# Jobs - Build-Platforms #
##########################
build-platforms-core:centos6:zed:
  extends:
    - .build-platforms-core
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed
    - build-devices-core:centos6:zed
    - build-cards-core:centos6:zed
    - build-adapters-core:centos6:zed
    - build-components-core:centos6:zed

build-platforms-platform:centos6:zed:
  extends: 
    - .build-platforms-platform
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-devices-platform:centos6:zed
    - build-primitives:centos6:zed
    - build-devices-core:centos6:zed

build-platforms-assets:centos6:zed:
  extends:
    - .build-platforms-assets
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-devices-platform:centos6:zed
    - build-primitives:centos6:zed
    - build-devices-assets:centos6:zed
    - build-cards-assets:centos6:zed
    - build-adapters-assets:centos6:zed
    - build-components-assets:centos6:zed
    - build-devices-core:centos6:zed

build-platforms-inactive:centos6:zed:
  extends:
    - .build-platforms-inactive
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed
    - build-devices-inactive:centos6:zed
    - build-cards-inactive:centos6:zed
    - build-components-inactive:centos6:zed


#####################
# Jobs - Assemblies #
#####################
build-assemblies-platform:centos6:zed:
  extends:
    - .build-assemblies-platform
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed
    - build-platforms-core:centos6:zed
    - build-platforms-platform:centos6:zed

build-assemblies-assets:centos6:zed:
  extends:
    - .build-assemblies-assets
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed
    - build-platforms-core:centos6:zed
    - build-platforms-platform:centos6:zed
    - build-platforms-assets:centos6:zed

build-assemblies-assets_ts:centos6:zed:
  extends:
    - .build-assemblies-assets_ts
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed
    - build-platforms-core:centos6:zed
    - build-platforms-platform:centos6:zed
    - build-platforms-assets:centos6:zed
    - build-components-assets_ts:centos6:zed
    - build-devices-assets_ts:centos6:zed

build-assemblies-inactive:centos6:zed:
  extends:
    - .build-assemblies-inactive
    - .zed-centos6
  needs:
    - job: prereq:centos6
      artifacts: true
    - build:centos6
    - build-primitives:centos6:zed
    - build-platforms-core:centos6:zed
    - build-platforms-platform:centos6:zed
    - build-platforms-assets:centos6:zed
    - build-platforms-inactive:centos6:zed


#####################
# Jobs - Build-Test #
#####################
test-core:centos6:zed:
  extends:
    - .test-core
    - .zed-centos6
    - .ocpiremote
  dependencies:
    - prereq:centos6
    - build:centos6
    - build-primitives:centos6:zed
    - build-platforms-core:centos6:zed
    - build-platforms-platform:centos6:zed
    - build-platforms-assets:centos6:zed
    - prereq:centos6:xilinx13_4
    - build-rcc:centos6:xilinx13_4
    - build-assemblies-assets:centos6:zed
  resource_group: zed

test-assets-base:centos6:zed:
  extends:
    - .test-assets-base
    - .zed-centos6
    - .ocpiremote
  dependencies:
    - prereq:centos6
    - build:centos6
    - build-primitives:centos6:zed
    - build-platforms-core:centos6:zed
    - build-platforms-platform:centos6:zed
    - build-platforms-assets:centos6:zed
    - prereq:centos6:xilinx13_4
    - build-rcc:centos6:xilinx13_4
    - build-assemblies-assets:centos6:zed
  resource_group: zed

test-assets-comms:centos6:zed:
  extends:
    - .test-assets-comms
    - .zed-centos6
    - .ocpiremote
  dependencies:
    - prereq:centos6
    - build:centos6
    - build-primitives:centos6:zed
    - build-platforms-core:centos6:zed
    - build-platforms-platform:centos6:zed
    - build-platforms-assets:centos6:zed
    - prereq:centos6:xilinx13_4
    - build-rcc:centos6:xilinx13_4
    - build-assemblies-assets:centos6:zed
  resource_group: zed

test-assets-dsp:centos6:zed:
  extends:
    - .test-assets-dsp
    - .zed-centos6
    - .ocpiremote
  dependencies:
    - prereq:centos6
    - build:centos6
    - build-primitives:centos6:zed
    - build-platforms-core:centos6:zed
    - build-platforms-platform:centos6:zed
    - build-platforms-assets:centos6:zed
    - prereq:centos6:xilinx13_4
    - build-rcc:centos6:xilinx13_4
    - build-assemblies-assets:centos6:zed
  resource_group: zed

test-assets-misc:centos6:zed:
  extends:
    - .test-assets-misc
    - .zed-centos6
    - .ocpiremote
  dependencies:
    - prereq:centos6
    - build:centos6
    - build-primitives:centos6:zed
    - build-platforms-core:centos6:zed
    - build-platforms-platform:centos6:zed
    - build-platforms-assets:centos6:zed
    - prereq:centos6:xilinx13_4
    - build-rcc:centos6:xilinx13_4
    - build-assemblies-assets:centos6:zed
  resource_group: zed

test-assets-util:centos6:zed:
  extends:
    - .test-assets-util
    - .zed-centos6
    - .ocpiremote
  dependencies:
    - prereq:centos6
    - build:centos6
    - build-primitives:centos6:zed
    - build-platforms-core:centos6:zed
    - build-platforms-platform:centos6:zed
    - build-platforms-assets:centos6:zed
    - prereq:centos6:xilinx13_4
    - build-rcc:centos6:xilinx13_4
    - build-assemblies-assets:centos6:zed
  resource_group: zed

test-assets_ts:centos6:zed:
  extends:
    - .test-assets_ts
    - .zed-centos6
    - .ocpiremote
  dependencies:
    - prereq:centos6
    - build:centos6
    - build-primitives:centos6:zed
    - build-platforms-core:centos6:zed
    - build-platforms-platform:centos6:zed
    - build-platforms-assets:centos6:zed
    - build-components-assets_ts:centos6:zed
    - build-devices-assets_ts:centos6:zed
    - prereq:centos6:xilinx13_4
    - build-rcc:centos6:xilinx13_4
    - build-assemblies-assets:centos6:zed
  resource_group: zed

test-inactive:centos6:zed:
  extends:
    - .test-inactive
    - .zed-centos6
    - .ocpiremote
  dependencies:
    - prereq:centos6
    - build:centos6
    - build-primitives:centos6:zed
    - build-platforms-platform:centos6:zed
    - build-platforms-inactive:centos6:zed
    - prereq:centos6:xilinx13_4
    - build-rcc:centos6:xilinx13_4
    - build-assemblies-assets:centos6:zed
  resource_group: zed
