FROM centos:7

RUN yum -y distro-sync
RUN yum -y install epel-release
RUN yum -y --setopt=skip_missing_names_on_install=False install ghostscript git libreoffice-headless make python34 python34-jinja2 rubber texlive texlive-appendix texlive-latex texlive-multirow texlive-placeins texlive-titlesec texlive-xstring unoconv https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm

CMD ["bash"]
