stages:
  - install


workflow:
  rules:
    - when: always


variables:
  KUBERNETES_MEMORY_REQUEST: "240Gi"
  KUBERNETES_MEMORY_LIMIT: "240Gi"
  KUBERNETES_CPU_REQUEST: "30"
  KUBERNETES_CPU_LIMIT: "30"
  BASE_IMAGE: ${CI_OCPI_CONTAINER_REGISTRY}/${HOST}/packages:${CI_COMMIT_SHORT_SHA}


.install:
  stage: install
  image: $BASE_IMAGE
  tags: ['aws', 'opencpi', 'cache']
  before_script:
    - git reset --hard # Overwrite cache with commit
    - find . -exec touch -ht $(date +"%Y%m%d%H%M.%S") {} + # Update timestamps
    # Update timestamps of changes since cache was created
    - test -e ${TARGET_TYPE}.cachestamp && sleep 1 && git diff --name-only HEAD $(cat ${TARGET_TYPE}.cachestamp) | xargs -r touch
    - if [[ $CI_COMMIT_SHA != $(cat build.cachestamp) ]] ; then echo "framework build cache was not updated for commit $COMMIT_SHA" && exit 1 ; fi
    - source ./cdk/opencpi-setup.sh -r
  artifacts:
    when: always
    expire_in: "7 days"
    paths:
      - build-report.xml
    reports:
      junit: build-report.xml


rcc_platforms:
  extends: .install
  timeout: 3h
  script:
    - ./.gitlab-ci/scripts/build.py --platform $RCC_PLATFORM --report-path build-report.xml --dependencies ${GIT_SUBMODULE_PATHS}
  after_script:
    - echo $CI_COMMIT_SHA > ${TARGET_TYPE}.cachestamp
    # Attempt to reduce size of cache while maintaining necessities for make recipes
    - find projects -type d -wholename */gen/inputs -exec rm -rf -- {} +
  variables:
    TARGET_TYPE: rcc_platform
    FALLBACK_KEY:  install-platform-${HOST}-${RCC_PLATFORM}-${CI_DEFAULT_BRANCH}
    CACHE_KEY: install-platform-${HOST}-${RCC_PLATFORM}-${CACHE_KEY_SUFFIX}
  cache:
    - key: build-${HOST}-${CACHE_KEY_SUFFIX}
      policy: pull
      untracked: true
    - key: $CACHE_KEY
      fallback_keys:
        - $FALLBACK_KEY
      policy: pull
      paths:
        - projects/
        - project-registry/
        - prerequisites/
        - build/autotools/
        - os/linux/driver/
        - cdk/${RCC_PLATFORM}/
        - ${TARGET_TYPE}.cachestamp
    - key: install-platform-${HOST}-${RCC_PLATFORM}-${CACHE_KEY_SUFFIX}
      policy: push
      when: on_success
      paths:
        - projects/
        - project-registry/
        - prerequisites/
        - build/autotools/
        - os/linux/driver/
        - cdk/${RCC_PLATFORM}/
        - ${TARGET_TYPE}.cachestamp


hdl_platforms:
  extends: .install
  timeout: 15h
  needs:
    - job: hdl_targets
      artifacts: false
  script:
    # Test that the cache for the prerequisite hdl_target was updated for this commit
    - if [[ $CI_COMMIT_SHA != $(cat hdl_target.cachestamp) ]] ; then echo "hdl_target cache was not updated for commit $COMMIT_SHA" && exit 1 ; fi
    - ./.gitlab-ci/scripts/build.py --platform $HDL_PLATFORM --report-path build-report.xml --dependencies ${GIT_SUBMODULE_PATHS}
  after_script:
    - echo $CI_COMMIT_SHA > ${TARGET_TYPE}.cachestamp
    # Attempt to reduce size of cache while maintaining necessities for make recipes
    - find projects -type d -wholename */gen/inputs -exec rm -rf -- {} +
    - find projects -type d \( -name ".Xil" -o -name *.dir \) -exec rm -rf -- {} +
    - find projects -type f \( -name *.log -o -name *.out -o -name *.jou -o -name *.pb -o -name *.dcp -o -name *.rpx -o -name *.bit \) -exec rm -- {} +
  variables:
    TARGET_TYPE: hdl_platform
    FALLBACK_KEY: install-platform-${HOST}-${HDL_PLATFORM}-${CI_DEFAULT_BRANCH}
    CACHE_KEY: install-platform-${HOST}-${HDL_PLATFORM}-${CACHE_KEY_SUFFIX}
  cache:
    - key: build-${HOST}-${CACHE_KEY_SUFFIX}
      policy: pull
      untracked: true
    - key: install-target-${HOST}-${HDL_TARGET}-${CACHE_KEY_SUFFIX}
      policy: pull
      paths:
        - projects/
    - key: $CACHE_KEY
      fallback_keys:
        - $FALLBACK_KEY
      policy: pull
      paths:
        - projects/
        - project-registry/
        - cdk/${HDL_PLATFORM}/
        - ${TARGET_TYPE}.cachestamp
    - key: install-platform-${HOST}-${HDL_PLATFORM}-${CACHE_KEY_SUFFIX}
      policy: push
      when: on_success
      paths:
        - projects/
        - project-registry/
        - cdk/${HDL_PLATFORM}/
        - ${TARGET_TYPE}.cachestamp


hdl_targets:
  extends: .install
  timeout: 8h
  script:
    - ./.gitlab-ci/scripts/build.py --hdl-target $HDL_TARGET --report-path build-report.xml --dependencies ${GIT_SUBMODULE_PATHS}
  after_script:
    - echo $CI_COMMIT_SHA > ${TARGET_TYPE}.cachestamp
  variables:
    TARGET_TYPE: hdl_target
    CACHE_KEY: install-target-${HOST}-${HDL_TARGET}-${CACHE_KEY_SUFFIX}
    FALLBACK_KEY: install-target-${HOST}-${HDL_TARGET}-${CI_DEFAULT_BRANCH}
  cache:
    - key: build-${HOST}-${CACHE_KEY_SUFFIX}
      policy: pull
      untracked: true
    - key: $CACHE_KEY
      fallback_keys:
        - $FALLBACK_KEY
      policy: pull
      paths:
        - projects/
        - project-registry/
        - ${TARGET_TYPE}.cachestamp
    - key: install-target-${HOST}-${HDL_TARGET}-${CACHE_KEY_SUFFIX}
      policy: push
      when: on_success
      paths:
        - projects/
        - project-registry/
        - ${TARGET_TYPE}.cachestamp
