stages:
  - test


workflow:
  rules:
    - when: always


.test:
  stage: test
  timeout: 6h
  variables:
    KUBERNETES_MEMORY_REQUEST: "16Gi"
    KUBERNETES_MEMORY_LIMIT: "16Gi"
    KUBERNETES_CPU_REQUEST: "4"
    KUBERNETES_CPU_LIMIT: "4"
    GIT_STRATEGY: none
    IMAGE_REPO: ${CI_OCPI_CONTAINER_REGISTRY}
    IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}
  before_script:
    - cd /home/user/opencpi
    - source ./cdk/opencpi-setup.sh -r
  artifacts:
    when: always
    paths:
      - test-report.xml
    reports:
      junit: test-report.xml
