trigger-downstream:plutosdr:
  stage: 'trigger-children'
  extends:
    - .centos7
    - .docker
  before_script: []
  script:
    - echo "$CI_COMMIT_MESSAGE"
    - export REF_NAME="opencpi-${CI_COMMIT_REF_NAME//\//%2F}"
    - >
      curl --fail
      "https://gitlab.com/api/v4/projects/15332497/repository/branches/$REF_NAME" 2> /dev/null
      && export REF_NAME="opencpi-$CI_COMMIT_REF_NAME"
      || export REF_NAME=develop
    - echo "kicking off plutosdr - $REF_NAME"
    - >
      curl --request POST
      --form token=$CI_JOB_TOKEN
      --form ref="$REF_NAME"
      --form "variables[CI_UPSTREAM_ID]=$CI_PIPELINE_ID"
      --form "variables[CI_UPSTREAM_REF]=$CI_COMMIT_REF_NAME"
      https://gitlab.com/api/v4/projects/15332497/trigger/pipeline
  after_script: [] 
  artifacts:
    paths: []
  rules:
  - if: '$CI_PLATFORMS =~ /(^| |:|,)(plutosdr)( |:|,|$)/i && $CI_PIPELINE_SOURCE =~ "web|schedule" '
  - if: '$CI_MR_PLATFORMS =~ /(^| |:|,)(plutosdr)( |:|,|$)/i && $CI_PIPELINE_SOURCE == "merge_request_event" '
  - if: '$CI_COMMIT_MESSAGE =~ /\[ *ci *( \S*)*( +|:|,)(plutosdr)(( |:|,)\S*)*\]/i && $CI_PIPELINE_SOURCE == "push" '
  - if: '$CI_PLATFORMS =~ /(^| |:|,)(plutosdr)( |:|,|$)/i && $CI_COMMIT_MESSAGE !~ /\[ *ci.*\]/i && $CI_PIPELINE_SOURCE == "push" '