# FIXME:  these are referenced in the source tree and thus would not work for an RPM installation.
# I.e. they are currently internal framework libraries
RccIncludeDirs+=$(OCPI_ROOT_DIR)/runtime/drc/base/include $(OCPI_ROOT_DIR)/runtime/drc/ad9361/include
include $(OCPI_CDK_DIR)/include/worker.mk
