.\"     Title: ocpidev-utilization
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 05/28/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "OCPIDEV\-UTILIZATION" "1" "05/28/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ocpidev-utilization \- displays or records FPGA resource use for HDL OpenCPI assets\&.
.SH "SYNOPSIS"
.sp
\fBocpidev\fR [\fI<options>\fR] \fButilization\fR [\fI<noun>\fR [\fI<name>\fR ]]
.SH "DESCRIPTION"
.sp
The \fButilization\fR verb invokes the OpenCPI tool that displays or records FPGA resource use for HDL OpenCPI assets\&. In order to display usage information about an HDL asset for a given platform, the asset needs to be built for that platform\&.
.sp
Asset types to be specified in the \fI<noun>\fR argument are:
.PP
\fBhdl\fR
.RS 4
A prefix to indicate an HDL asset in the
\fBhdl\fR
subdirectory of a project\&. Possible HDL assets are:
.PP
\fBassembly\fR|\fBies\fR
.RS 4
Display usage information for all built assemblies contained in the current project or a for specified built HDL assembly contained in the current project\&.
.RE
.PP
\fBplatform\fR|\fBs\fR
.RS 4
Display usage information for all built platforms or for a specified built HDL platform contained in the current project\&.
.RE
.RE
.PP
\fBlibrary\fR
.RS 4
Display usage information for all built workers contained in a component library\&.
.RE
.PP
\fBproject\fR
.RS 4
Display usage information for all built workers, platforms, and assemblies contained in a project\&.
.RE
.PP
\fBworker\fR
.RS 4
Display usage information for the specified worker\&.
.RE
.PP
\fBworkers\fR
.RS 4
Display usage information for all built workers contained in the current project\&.
.RE
.SH "OPTIONS"
.sp
In the description below, a plus sign (+) after the option indicates that it can be specified more than once on the command line\&.
.PP
\fB\-\-format=table\fR|\fBlatex\fR
.RS 4
Specify how to output the usage information\&. Specifying
\fBtable\fR
sends the information to stdout in tabular format\&. Specifying
\fBlatex\fR
bypasses
\fBstdout\fR
and writes all output to
\fButilization\&.inc\fR
files in the directories for the assets on which it operates\&.
.RE
.PP
\fB\-\-hdl\-library=\fR\fI<hdl\-primitive\-library>\fR
.RS 4
Specify the HDL primitive library in which this operation is to be performed\&.
.RE
.PP
\fB\-\-hdl\-platform=\fR\fI<platform>\fR+
.RS 4
Specify the buildable HDL platform for which to display usage information\&.
.RE
.PP
\fB\-\-hdl\-target=\fR\fI<target>\fR+
.RS 4
Specify the HDL target for which to display worker (not assembly) usage information\&.
.RE
.PP
\fB\-\-library=\fR\fI<library>\fR, \fB\-l\fR \fI<library>\fR
.RS 4
Specify the component library in which the utilization operation is to be performed\&.
.RE
.PP
\fB\-P\fR \fI<hdl\-platform\-directory>\fR
.RS 4
Specify the HDL platform subdirectory in which the utilization operation is to be performed\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Show usage information for the worker named
\fBcomplex_mixer\fR
using build results from all platforms:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev utilization worker complex_mixer
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Show usage information for the worker named
\fBcomplex_mixer\fR
using build results from the
\fBxsim\fR
platform:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev utilization worker complex_mixer \-\-hdl\-platform=xsim
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Show usage information for all workers in the current location (project, library, etc\&.):
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev utilization workers
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Show usage information for the
\fBfir_real_sse\fR
worker in the
\fB/components/dsp_comps\fR
library:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev utilization worker fir_real_sse \-l dsp_comps
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 5.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  5." 4.2
.\}
Show usage information for the
\fBxsim\fR
platform:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev utilization hdl\-platform=xsim
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 6.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  6." 4.2
.\}
Show usage information for all HDL platforms in the current project:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev utilization hdl\-platforms
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 7.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  7." 4.2
.\}
Show usage information for an HDL assembly named
\fBmy_assy\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev utilization hdl assembly my_assy
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 8.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  8." 4.2
.\}
Show usage information for all HDL assemblies in the current project:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev utilization hdl assemblies
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 9.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  9." 4.2
.\}
Record usage information for an HDL assembly named
\fBmy_assy\fR
in LaTeX format:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev utilization hdl assembly my_assy \-\-format=latex
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'10.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "10." 4.2
.\}
Show usage information for all supported assets in a project:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev utilization project
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'11.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "11." 4.2
.\}
Record usage information for all supported assets in a project in LaTeX format:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev utilization project \-\-format=latex
.fi
.if n \{\
.RE
.\}
.RE
.SH "BUGS"
.sp
See https://www\&.opencpi\&.org/report\-defects
.SH "RESOURCES"
.sp
See the main web site: https://www\&.opencpi\&.org
.SH "SEE ALSO"
.sp
ocpidev(1) ocpidev\-build(1) ocpidev\-clean(1) ocpidev\-create(1) ocpidev\-delete(1) ocpidev\-refresh(1) ocpidev\-register(1) ocpidev\-run(1) ocpidev\-set(1) ocpidev\-show(1) ocpidev\-unregister(1) ocpidev\-unset(1)
.SH "COPYING"
.sp
Copyright (C) 2020 OpenCPI www\&.opencpi\&.org\&. OpenCPI is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
