.\"     Title: ocpiview
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/20/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "OCPIVIEW" "1" "08/20/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ocpiview \- command\-line tool for viewing the results of simulation runs on HDL (FPGA) simulator platforms
.SH "SYNOPSIS"
.sp
\fBocpiview\fR [\fI<options>\fR] [\fI<directory>\fR]
.SH "DESCRIPTION"
.sp
The \fBocpiview(1)\fR tool displays the results of a simulation run on an HDL (FPGA) simulator platform using the simulation viewer provided by the simulator platform associated with that run\&. OpenCPI application developers generally run \fBocpiview\fR after application execution if they need to examine the simulation results in detail\&. OpenCPI component developers can also use \fBocpiview\fR to examine the results of component unit test executions on simulator platforms\&.
.sp
In a project, the results of FPGA simulator runs for OpenCPI applications reside in the the \fBsimulations/\fR subdirectory of the \fBapplications/\fR directory\&. Each time a simulator runs under \fBocpirun\fR (or \fBocpidev run\fR with the \fB\-\-keep\-simulations\fR option), it executes in a new subdirectory within the \fBsimulations/\fR subdirectory created for that simulation run with the name \fI<assembly\-name>\fR\fB\&.\fR\fI<sim\-platform>\fR\fB\&.\fR\fI<date\-time>\fR\&. Thus, running OpenCPI applications that use simulators results in one or more subdirectories that hold the simulation results for each simulation run\&.
.sp
The results of an FPGA simulator run for a component unit test reside in a \fI<sim\-platform>\fR\fB/\fR subdirectory of the component unit test\(cqs \fBrun/\fR directory with the name \fI<test\-case\-name>\fR\fB\&.\fR\fI<unit\-test\-name>\fR\fB\&.hdl\&.simulation\fR\&.
.sp
The \fI<directory>\fR argument specifies the directory that contains a particular simulation run\&. If it is not used, the tool runs the most recent simulation run in the \fBsimulations/\fR subdirectory\&.
.sp
The chapter "Execution of Simulation Bitstreams and Containers" in the \fIOpenCPI HDL Development Guide\fR provides more information about using FPGA simulators to run OpenCPI applications\&. The chapter "Unit Testing of Workers" in the \fIOpenCPI Component Development Guide\fR provides more information about developing component unit tests, as does ocpidev\-test(1)\&.
.SH "VERBS"
.sp
None\&.
.SH "NOUNS"
.sp
None\&.
.SH "OPTIONS"
.PP
\fB\-h\fR
.RS 4
Display help information about the tool\&.
.RE
.PP
\fB\-v\fR
.RS 4
Describe what is happening in command execution in more detail\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Inside the project, display the results of running an HDL assembly named
\fBmyassembly\fR
on the
\fBxsim\fR
FPGA simulator:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpiview simulations/myassembly\&.xsim\&.20200815143505
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Inside the project, display the results of the most recent simulation run with verbose command output:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpiview \-v
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Inside the component unit test\(cqs directory in the project, display the results of running a component unit test named
\fBmytest\fR
on the
\fBxsim\fR
FPGA simulator platform using the default test case:
.sp
.if n \{\
.RS 4
.\}
.nf
$ ocpiview run/xsim/case00\&.00\&.mytest\&.hdl\&.simulation
.fi
.if n \{\
.RE
.\}
.RE
.SH "BUGS"
.sp
See https://www\&.opencpi\&.org/report\-defects
.SH "RESOURCES"
.sp
See the main web site: https://www\&.opencpi\&.org
.SH "SEE ALSO"
.sp
ocpidev(1) ocpidev\-application(1) ocpidev\-assembly(1) ocpidev\-run(1) ocpidev\-test(1) ocpirun(1)
.SH "COPYING"
.sp
Copyright (C) 2020 OpenCPI www\&.opencpi\&.org\&. OpenCPI is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
