.\"     Title: ocpiremote
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/20/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "OCPIREMOTE" "1" "08/20/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ocpiremote \- command\-line tool for remotely managing an OpenCPI container server
.SH "SYNOPSIS"
.sp
\fBocpiremote\fR [\fI<options>\fR] [\fI<verb>\fR]
.SH "DESCRIPTION"
.sp
The \fBocpiremote(1)\fR command\-line tool can be used on a local system to load, start, and control an \fBocpiserve(1)\fR container server on a remote system\&. The target remote system requires the Secure Shell (SSH), the \fBbash\fR shell and the \fBtar\fR command in addition to an OpenCPI\-supported software (RCC) platform\&. No additional installation is necessary\&.
.sp
The \fBocpiremote\fR tool loads an \fBocpiserve\fR executable "package" with Secure Copy Protocol (SCP) over an SSH connection into a "sandbox" directory (by default, \fB~/sandbox/\fR) on the remote system and can subsequently be used to start it\&. When started, the \fBocpiserve\fR container server makes its local containers available to any and all remote clients through the local network interfaces on the remote system\&. See the ocpiserve(1) tool for details\&. The \fBocpiremote\fR tool manages the container server in the sandbox directory without affecting the rest of the remote system\(cqs installation and provides a convenient way to set up and operate container servers remotely\&.
.sp
The \fBocpiremote\fR command\-line tool is part of OpenCPI\(cqs \fB\fIremote containers\fR\fR feature, which allows for the addition of containers available in other systems on the network to the set of containers considered for application execution\&. See the chapter "Using Remote Containers: Network\-Connected Processors" in the \fIOpenCPI Application Development Guide\fR for information on how to set up and use this feature\&.
.SH "VERBS"
.sp
The \fBocpiremote\fR command operates on the remote system whose IP address and TCP port are listed first in the OCPI_SERVER_ADDRESSES environment variable or whose IP address and (optional) TCP port are specified as options on the command line\&.
.sp
The verbs supported by \fBocpiremote\fR are:
.PP
\fBdeploy\fR
.RS 4
Copy an OpenCPI bootable media directory tree (also called a "deployment package" or "SD card contents") to a remote system (usually to an SD card inserted into that system) and then reboot it\&. See the
\fIOpenCPI Installation Guide\fR, the
\fIOpenCPI Platform Development Guide\fR, and the
ocpiadmin(1)
tool for more information about creating bootable media directory trees for embedded systems\&.
.RE
.PP
\fBload\fR
.RS 4
Create a sandbox directory on a remote system and then send an
\fBocpiserve\fR
container server package to that directory\&.
.RE
.PP
\fBlog\fR
.RS 4
Interactively view
\fBocpiserve\fR
container server logging\&.
.RE
.PP
\fBreboot\fR
.RS 4
Reboot a remote system\&.
.RE
.PP
\fBreload\fR
.RS 4
Delete an
\fBocpiserve\fR
container server sandbox directory and then reload it\&.
.RE
.PP
\fBrestart\fR
.RS 4
Stop and then start an
\fBocpiserve\fR
container server on a remote system\&.
.RE
.PP
\fBstart\fR
.RS 4
Start an
\fBocpiserve\fR
container server on a remote system\&.
.RE
.PP
\fBstatus\fR
.RS 4
Get the status of an
\fBocpiserve\fR
container server on a remote system\&.
.RE
.PP
\fBstop\fR
.RS 4
Stop an
\fBocpiserve\fR
container server on a remote system\&.
.RE
.PP
\fBtest\fR
.RS 4
Test the basic connectivity between the local system and an
\fBocpiserve\fR
container server on a remote system\&.
.RE
.PP
\fBunload\fR
.RS 4
Delete a container server sandbox directory\&.
.RE
.sp
None of these verbs take any arguments\&.
.SH "NOUNS"
.sp
There are no nouns for \fBocpiremote\fR\&.
.SH "OPTIONS"
.sp
In the descriptions below, a plus sign (+) after the option indicates that it can be specified more than once on the command line\&.
.SS "Options Common to All Operations on a Container Server or Remote System"
.PP
\fB\-\-ip_addr=\fR\fI<ip\-address>\fR, \fB\-i\fR \fI<ip\-address>\fR
.RS 4
Specify the IP address of the target remote system\&. If this option is not specified, the first IP address in the OCPI_SERVER_ADDRESSES environment variable is used\&.
.RE
.PP
\fB\-\-password=\fR\fI<password>\fR, \fB\-p\fR \fI<password>\fR
.RS 4
Specify the password associated with the username used for login to the target remote system\&. The default password is
\fBroot\fR\&.
.RE
.PP
\fB\-\-remote_dir=\fR\fI<directory\-name>\fR, \fB\-d\fR \fI<directory\-name>\fR
.RS 4
Specify the name of a directory on the target remote system in which to create and use a container server sandbox\&. If this option is not used, the default directory name
\fBsandbox/\fR
is created in the home directory of the specified user\&.
.RE
.PP
\fB\-\-ssh_opts=\fR\fI<options>\fR, \fB\-o\fR \fI<options>\fR
.RS 4
Specify the SSH options for connecting to the target remote system\&. If this option is not used, the SSH options for automatically accepting host keys without notification and for suppressing most warning and diagnostic messages are used\&.
.RE
.PP
\fB\-\-scp_opts=\fR\fI<options>\fR, \fB\-c\fR \fI<options>\fR
.RS 4
Specify the SCP options for connecting to the target remote system\&. If this option is not used, the SCP options for automatically accepting host keys without notification and for suppressing most warning and diagnostic messages are used\&.
.RE
.PP
\fB\-\-user=\fR\fI<username>\fR, \fB\-u\fR \fI<username>\fR
.RS 4
Specify the username used for login to the target remote system\&. The default username is
\fBroot\fR\&.
.RE
.SS "Options When Loading or Reloading a Container Server"
.PP
\fB\-\-\fR\fBhw_platform=\fR\fI<HDL\-platform\-identifier>\fR, \fB\-s\fR \fI<HDL\-platform\-identifier>\fR
.RS 4
Specify the identifier of the HDL (FPGA) platform in use for the container server environment on the target remote system\&. If this option is not used, the default is
\fBzed\fR\&. See the
\fIOpenCPI User Guide\fR
for the possible identifiers for OpenCPI HDL platforms\&.
.RE
.PP
\fB\-\-port=\fR\fI<tcp\-port\-number>\fR, \fB\-r\fR \fI<tcp\-port\-number>\fR
.RS 4
Specify the TCP port of the container server on the target remote system\&. If this option is not specified, the first port number in the OCPI_SERVER_ADDRESSES environment variable is used\&.
.RE
.PP
\fB\-\-sw_platform=\fR\fI<RCC\-platform\-identifier>\fR, \fB\-s\fR \fI<RCC\-platform\-identifier>\fR
.RS 4
Specify the identifier of the RCC (software) platform in use for the container server environment on the target remote system\&. If this option is not used, the default is
\fBxilinx13_4\fR\&. See the
\fIOpenCPI User Guide\fR
for the possible identifiers for OpenCPI RCC platforms\&.
.RE
.SS "Options When Deploying OpenCPI Bootable Media Files to a Remote System"
.PP
\fB\-\-hw_platform=\fR\fI<HDL\-platform\-identifier>\fR, \fB\-s\fR \fI<HDL\-platform\-identifier>\fR
.RS 4
Specify the identifier of the HDL (FPGA) platform in use for the container server environment on the target remote system\&. If this option is not used, the default is
\fBzed\fR\&. See the
\fIOpenCPI User Guide\fR
for the possible identifiers for OpenCPI HDL platforms\&.
.RE
.PP
\fB\-\-sw_platform=\fR\fI<RCC\-platform\-identifier>\fR, \fB\-s\fR \fI<RCC\-platform\-identifier>\fR
.RS 4
Specify the identifier of the RCC (software) platform in use for the container server environment on the target remote system\&. If this option is not used, the default is
\fBxilinx13_4\fR\&. See the
\fIOpenCPI User Guide\fR
for the possible identifiers for OpenCPI RCC platforms\&.
.RE
.SS "Options When Starting or Restarting a Container Server"
.PP
\fB\-\-log\-level=\fR\fI<value>\fR, \fB\-l\fR\fI<value>\fR
.RS 4
Specify the OpenCPI log level to be used during container server execution\&. See the description of the OCPI_LOG_LEVEL environment variable in the
\fIOpenCPI User Guide\fR
for a description of possible values\&. Using this option overrides the level set in the OCPI_LOG_LEVEL environment variable\&. The default log level is 0 (no logging)\&.
.RE
.SH "ENVIRONMENT VARIABLES"
.sp
The following OpenCPI environment variables affect \fBocpiremote\fR execution:
.PP
\fBOCPI_ENABLE_REMOTE_DISCOVERY\fR
.RS 4
Whether (set to
\fB1\fR) or not (set to
\fB0\fR) multicast User Datagram Protocol (UDP) discovery of remote systems running
\fBocpiserve\fR
is enabled\&.
.RE
.PP
\fBOCPI_SERVER_ADDRESSES\fR
.RS 4
A comma\- or space\-separated list of IP addresses/TCP ports of remote systems to contact, where each IP/TCP address is in the format
\fI<ip\-address>\fR\fB:\fR\fI<tcp\-port>\fR\&. For example, 192\&.168\&.1\&.102:12345\&. Starting
\fBocpiserve\fR
with the
\fB\-\-verbose\fR
option directs it to output its IP addresses/TCP ports\&.
.RE
.PP
\fBOCPI_SERVER_ADDRESSES_FILE\fR
.RS 4
The name of a file that contains remote system IP addresses/TCP ports, one per line\&. Each IP address is in the format
\fI<ip\-address>\fR\fB:\fR\fI<tcp\-port>\fR\&. For example, 192\&.168\&.1\&.102:12345\&.
.RE
.PP
\fBOCPI_OCPI_SOCKET_INTERFACE\fR
.RS 4
The name of the network interface (from the list of network interfaces returned by the Linux
\fBifconfig\fR
command) to be used for contacting remote systems running
\fBocpiserve\fR
container servers\&. Set this variable to the interface with the same network address (IP address anded with the netmask) as the container servers being used\&.
.RE
.sp
The chapter "Using Remote Containers: Network\-Connected Processors" in the \fIOpenCPI Application Development Guide\fR provides more information about when to use these environment variables and why\&.
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Load an
\fBocpiserve\fR
container server on the remote system with IP address 192\&.168\&.1\&.102\&. The operation creates the container server executable in the directory
\fB~/sandbox/\&.\fR
.sp
.if n \{\
.RS 4
.\}
.nf
ocpiremote \-\-ip_addr=192\&.168\&.1\&.102 load
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Start a previously loaded
\fBocpiserve\fR
container server on the remote system with IP address 192\&.168\&.1\&.102:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpiremote \-\-ip_addr=192\&.168\&.1\&.102 start
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Stop the
\fBocpiserve\fR
container server on the remote system with IP address 192\&.168\&.1\&.102:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpiremote \-\-ip_addr=192\&.168\&.1\&.102 stop
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Observe logging on the
\fBocpiserve\fR
container server on the remote system with IP address 192\&.168\&.1\&.102:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpiremote \-\-ip_addr=192\&.168\&.1\&.102 log
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 5.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  5." 4.2
.\}
Load an
\fBocpiserve\fR
container server into the
\fB~/myserver/\fR
directory on the remote system listed first in the OCPI_SERVER_ADDRESSES environment variable:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpiremote \-\-remote_dir=myserver load
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 6.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  6." 4.2
.\}
Delete and then load an
\fBocpiserve\fR
container server on the remote system with the IP address 192\&.168\&.1\&.102 and the TCP port 9233:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpiremote \-\-ip_addr=192\&.168\&.1\&.102 \-\-port=9233 reload
.fi
.if n \{\
.RE
.\}
.RE
.SH "BUGS"
.sp
See https://www\&.opencpi\&.org/report\-defects
.SH "RESOURCES"
.sp
See the main web site: https://www\&.opencpi\&.org
.SH "SEE ALSO"
.sp
ocpiadmin(1) ocpidev(1) ocpidev\-application(1) ocpidev\-assembly(1) ocpidev\-worker(1) ocpiserve(1) ocpirun(1)
.SH "COPYING"
.sp
Copyright (C) 2020 OpenCPI www\&.opencpi\&.org\&. OpenCPI is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
