.\"     Title: ocpidev-primitive
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 07/14/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "OCPIDEV\-PRIMITIVE" "1" "07/14/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ocpidev-primitive \- manage an OpenCPI HDL primitive\&.
.SH "SYNOPSIS"
.sp
\fBocpidev\fR [\fI<options>\fR] \fI<verb>\fR \fBhdl primitive\fR {\fBcore\fR|\fBlibrary\fR} \fI<name>\fR
.SH "DESCRIPTION"
.sp
The \fBhdl primitive\fR noun represents an OpenCPI primitive, which is an HDL asset at a level that is lower than an HDL worker and that can be used as a building block for the worker\&. HDL primitives are useful when there is lower\-level code that is reused or shared in different HDL workers or when workers import non\-OpenCPI code modules that should be left untouched\&.
.sp
An HDL primitive is either:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
An
\fBHDL primitive core\fR, which is a single primitive module that can be built and/or synthesized from source code, imported from a third party presynthesized and possibly encrypted, or generated by vendor\-specific FPGA synthesis tools like Xilinx CoreGen and Altera MegaWizard\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
An
\fBHDL primitive library\fR, which is a collection of HDL primitive modules compiled from source code into a library from which individual modules can be used as needed by HDL workers\&.
.RE
.sp
The exported/installed library or core that results from building the HDL primitive can be referenced in HDL worker Makefiles, in a component library Makefile (\fBLibrary\&.mk\fR) to make it available to all HDL workers in the component library, or a project Makefile (\fBProject\&.mk\fR) to make it available to all HDL workers in the project\&.
.sp
An HDL primitive is described by its \fBMakefile\fR and its source and binary forms, but does not have an XML definition\&.
.sp
In a project, an HDL primitive resides in its own directory \fI<name>\fR in the \fB/hdl/primitives/\fR subdirectory\&. An HDL primitive cannot have the same name as a worker\&. The directory contains the HDL primitive \fBMakefile\fR and its source code (Verilog or VHDL, with possible pre\-built files for HDL primitive cores)\&. The \fBocpidev create\fR operation for an HDL primitive creates an initial version of the \fBMakefile\fR that can then be edited as necessary to implement the HDL primitive\&.
.sp
The \fBocpidev build\fR operation generates the exportable results in a \fB/lib\fR subdirectory\&. The \fBocpidev clean\fR operation removes this subdirectory and the generated results\&.
.sp
For details on how to develop an HDL primitive, see the chapter "HDL Primitives" in the \fIOpenCPI HDL Development Guide\fR\&.
.sp
Verbs that can operate on an HDL primitive are:
.PP
\fBbuild\fR
.RS 4
Compile the HDL primitive source code, creating files and directories as required\&.
.RE
.PP
\fBclean\fR
.RS 4
Remove all generated and compiled files for the HDL primitive\&.
.RE
.PP
\fBcreate\fR
.RS 4
Create the named HDL primitive, creating files and directories as required\&.
.RE
.PP
\fBdelete\fR
.RS 4
Remove all directories and files associated with the named HDL primitive\&.
.RE
.sp
Note that an asset\(cqs name is implied by the directory you\(cqre in when you issue the \fBocpidev\fR command\&. For an HDL primitive, this means that you can perform operations (verbs) on the HDL primitive without having to specify its name when you issue the \fBocpidev\fR command from inside the HDL primitive directory\&.
.sp
The \fBocpidev\fR tool can also operate on a plural \fBprimitives\fR noun\&. The syntax is:
.sp
\fBocpidev\fR [\fI<options>\fR] [\fBbuild\fR|\fBclean\fR] \fBprimitives\fR
.sp
where the \fBbuild\fR and \fBclean\fR operations and any specified options are applied to all HDL primitives in a project\&.
.SH "OPTIONS"
.sp
In the descriptions below, a plus sign (+) after the option indicates that it can be specified more than once on the command line\&.
.sp
Keywords for platforms supported by OpenCPI that can be specified in the \fI<platform>\fR argument to an option can be found in the tables of supported platforms in the \fIOpenCPI User Guide\fR\&.
.sp
Keywords for architectures supported by OpenCPI that can be specified in the \fI<target>\fR argument to an option include \fBisim\fR, \fBmodelsim\fR, \fBxsim\fR, \fBstratix4\fR, \fBstratix5\fR, \fBvirtex5\fR, \fBvirtex6\fR, \fBzynq\fR, \fBzynq_is\fR, \fBspartan3adsp\fR\&.
.SS "Options That Apply to All Operations (Verbs) on HDL Primitives"
.PP
\fB\-d\fR \fI<directory>\fR
.RS 4
Specify the directory in which the command should be run\&. Analogous to the
\fB\-C\fR
option in the POSIX
\fBmake\fR
command\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Describe what is happening in command execution in more detail\&.
.RE
.SS "Options When Creating HDL Primitives"
.PP
\fB\-\-exclude\-platform=\fR\fI<platform>\fR, \fB\-Q\fR \fI<platform>\fR+
.RS 4
Do not build the HDL primitive for the specified HDL platform\&.
.RE
.PP
\fB\-\-only\-platform=\fR\fI<platform>\fR, \fB\-G\fR \fI<platform>\fR+
.RS 4
Only build the HDL primitive for the specified HDL platform\&.
.RE
.PP
\fB\-T\fR \fI<target>\fR+
.RS 4
Only build the HDL primitive for the specified HDL architecture\&.
.RE
.PP
\fB\-Z\fR \fI<target>\fR+
.RS 4
Do not build the HDL primitive for the specified HDL architecture\&.
.RE
.PP
\fB\-k\fR
.RS 4
Keep files and directories created after an HDL primitive creation fails\&. Normally, all such files and directories are removed on any failure\&.
.RE
.SS "Options When Creating HDL Primitive Cores"
.PP
\fB\-B\fR \fI<file>\fR
.RS 4
Specify the name of a prebuilt core file created by a vendor\-specific core generator tool; for example, a *\&.ngc or *\&.qxp file\&.
.RE
.PP
\fB\-M\fR \fI<module>\fR
.RS 4
Specify the name of the top module at the core\&. If this option is not specified, the default module name used is the name of the core specified in the <name> argument to the
\fBcreate\fR
operation\&.
.RE
.SS "Options When Creating HDL Primitive Libraries"
.PP
\fB\-H\fR
.RS 4
Specify that the HDL primitive library being created does not depend on any other HDL primitive libraries\&. By default, HDL primitive libraries are assumed to depend on the built\-in HDL primitive libraries (currently
\fBbsv\fR,
\fBfixed_float\fR,
\fBocpi\fR
and
\fButil\fR)\&.
.RE
.PP
\fB\-J\fR
.RS 4
Specify that the HDL primitive library being created should not be elaborated when built\&. Using this option results in a slight time savings at the cost of catching elaboration errors in the build process\&.
.RE
.SS "Options When Deleting HDL Primitives"
.PP
\fB\-f\fR
.RS 4
Force deletion: do not ask for confirmation when deleting an HDL primitive\&. Normally, you are asked to confirm a deletion\&.
.RE
.SS "Options When Building HDL Primitives"
.PP
\fB\-\-hdl\-platform=\fR\fI<platform>\fR+
.RS 4
Build the HDL primitive for the specified platform\&.
.RE
.PP
\fB\-\-hdl\-target=\fR\fI<target>\fR+
.RS 4
Build the HDL primitive for the specified HDL architecture\&. If HDL targets are specified and no HDL platforms are specified, containers are not built for HDL assemblies or component unit test suites\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Inside the project or the project\(cqs
\fBhdl/primitives/\fR
directory, create an HDL primitive core named
\fBmyprimcore\fR
where the top module of the core will be
\fBmytopmod\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev \-M mytopmod create hdl primitive core myprimcore
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Inside the project or the project\(cqs
\fBhdl/primitives/\fR
directory, create an HDL primitive library named
\fBmyprimlib\fR
and indicate that it does not depend on any other primitive libraries:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev \-H create hdl primitive library myprimlib
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
In the project that contains the HDL primitive, compile the source code for the HDL primitive core named
\fBmyprimcore\fR
for the Zynq architecture:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev build hdl primitive core myprimcore \-\-hdl\-target=zynq
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Inside the project, remove the compiled HDL primitive code for all HDL primitives in the project:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev clean hdl primitives
.fi
.if n \{\
.RE
.\}
.RE
.SH "BUGS"
.sp
See https://www\&.opencpi\&.org/report\-defects
.SH "RESOURCES"
.sp
See the main web site: https://www\&.opencpi\&.org
.SH "SEE ALSO"
.sp
ocpidev(1) ocpidev\-assembly(1) ocpidev\-build(1) ocpidev\-clean(1) ocpidev\-create(1) ocpidev\-delete(1) ocpidev\-library(1) ocpidev\-platform(1) ocpidev\-project(1) ocpidev\-worker(1)
.SH "COPYING"
.sp
Copyright (C) 2020 OpenCPI www\&.opencpi\&.org\&. OpenCPI is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
