.\"     Title: ocpidev-application
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 07/14/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "OCPIDEV\-APPLICATION" "1" "07/14/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ocpidev-application \- manage an OpenCPI application\&.
.SH "SYNOPSIS"
.sp
\fBocpidev\fR [\fI<options>\fR] \fI<verb>\fR \fBapplication\fR \fI<name>\fR
.SH "DESCRIPTION"
.sp
The \fBapplication\fR noun represents an OpenCPI application, which is a connected and configured assembly of components\&. An application is described by an OpenCPI Application Specification (OAS), which can be a standalone XML text file or an XML document embedded in and manipulated by a C++ or Python program via the OpenCPI Application Control Interface (ACI)\&. The \fIOpenCPI Application Development Guide\fR provides details on the structure, syntax and development process for OpenCPI applications\&.
.sp
In a project, an application resides in the \fBapplications/\fR directory and is either an XML application or an ACI application\&. XML applications reside either directly in the \fBapplications/\fR directory or in their own directory underneath the \fBapplications/\fR directory\&. ACI applications always reside in their own directory within the \fBapplications/\fR directory\&.
.sp
Verbs that can operate on an application are:
.PP
\fBbuild\fR
.RS 4
Build the application, including any custom building specified by a customized Makefile\&. The build operation applies only to an ACI application: it builds the C++ files into an executable\&.
.RE
.PP
\fBclean\fR
.RS 4
Remove all the generated and compiled files for the application, including any cleaning specfied by a customized application Makefile\&.
.RE
.PP
\fBcreate\fR
.RS 4
Create the named application in the
\fBapplications/\fR
directory of the project according to the specified options\&. If the
\fBapplications/\fR
directory does not exist, it is created\&.
.RE
.PP
\fBdelete\fR
.RS 4
Remove all directories and files associated with the named application\&.
.RE
.PP
\fBrun\fR
.RS 4
Run the application\&. For an XML application, the OpenCPI tool
\fBocpirun\fR
is invoked to execute it\&. For an ACI application, the executable is run\&.
.RE
.sp
Note that an asset\(cqs name is implied by the directory you\(cqre in when you issue the \fBocpidev\fR command\&. For applications, this means that you can perform operations (verbs) on the application without having to specify its name when you issue the \fBocpidev\fR command from inside the \fBapplications/\fR directory or the application\(cqs own directory\&.
.sp
The \fBocpidev\fR tool can also operate on a plural \fBapplications\fR noun\&. The syntax is:
.sp
\fBocpidev\fR [\fI<options>\fR] [\fBbuild\fR|\fBclean\fR|\fBrun\fR] \fBapplications\fR
.sp
The verbs that can be performed on the \fBapplications\fR noun are:
.PP
\fBbuild\fR
.RS 4
Build all ACI applications in a project\&. The general\-purpose options and all options for building applications can be used\&.
.RE
.PP
\fBclean\fR
.RS 4
Clean all ACI applications in a project\&. The general\-purpose options can be used\&.
.RE
.PP
\fBrun\fR
.RS 4
Run all the applications in the
\fBapplications/\fR
directory of a project\&. The general\-purpose options and all options for running applications can be used\&.
.RE
.SH "OPTIONS"
.sp
In the descriptions below, a plus sign (+) after the option indicates that it can be specified more than once on the command line\&.
.SS "Options That Apply to All Operations (Verbs) on Applications"
.PP
\fB\-d\fR \fI<directory>\fR
.RS 4
Specify the directory in which the command should be run\&. Analogous to the
\fB\-C\fR
option in the POSIX
\fBmake\fR
command\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Describe what is happening in command execution in more detail\&.
.RE
.SS "Options When Creating Applications"
.PP
\fB\-\-exclude\-platform=\fR\fI<platform>\fR, \fB\-Q\fR \fI<platform>\fR+
.RS 4
Do not build the application for the specified platform\&.
.RE
.PP
\fB\-\-only\-platform=\fR\fI<platform>\fR, \fB\-G\fR \fI<platform>\fR+
.RS 4
Only build the application for the specified platform\&.
.RE
.PP
\fB\-T\fR \fI<target>\fR+
.RS 4
Only build the application for the specified architecture\&.
.RE
.PP
\fB\-X\fR
.RS 4
Create a simple XML OAS file named
\fI<name>\fR\fB\&.xml\fR
in the
\fBapplications/\fR
directory of the project\&. The default (no
\fB\-X\fR
or
\fB\-x\fR
option specified) is to create an ACI application in a file named
\fI<name>\fR\fB\&.cc\fR
that contains the main program in the
\fI<name>\fR
directory underneath the
\fBapplications/\fR
directory\&.
.RE
.PP
\fB\-Z\fR \fI<target>\fR+
.RS 4
Do not build the application for the specified architecture\&.
.RE
.PP
\fB\-k\fR
.RS 4
Keep files and directories created after an application creation fails\&. Normally, all such files and directories are removed on any failure\&.
.RE
.PP
\fB\-x\fR
.RS 4
Create a simple XML OAS file named
\fI<name>\fR\fB\&.xml\fR
in the
\fI<name>\fR
directory under
\fBapplications/\fR\&.
.RE
.SS "Options When Deleting Applications"
.PP
\fB\-f\fR
.RS 4
Force deletion: do not ask for confirmation when deleting an application\&. Normally, you are asked to confirm a deletion\&.
.RE
.SS "Options When Building ACI Applications"
.PP
\fB\-\-hdl\-rcc\-platform=\fR\fI<platform>\fR+
.RS 4
Build ACI assets for the RCC platforms associated with the specified HDL platform\&. If this option is not used (and
\fB\-\-rcc\-platform\fR
\fI<platform>\fR
is also not used), the current development software platform is used as the single RCC platform used for building\&.
.RE
.PP
\fB\-\-rcc\-platform=\fR\fI<platform>\fR+
.RS 4
Build ACI assets for the specified RCC platform\&. If this option is not used (and
\fB\-\-hdl\-rcc\-platform\fR
\fI<platform>\fR
is also not used), the current development software platform is used as the single RCC platform used for building\&.
.RE
.SS "Options When Running ACI Applications"
.PP
\fB\-\-after=\fR\fI<args>\fR+
.RS 4
Specify the argument(s) to insert at the end of the execution command line\&.
.RE
.PP
\fB\-\-before=\fR\fI<args>\fR+
.RS 4
Specify the argument(s) to insert before the ACI executable or the
\fBocpirun\fR
command; for example, environment settings or prefix commands\&.
.RE
.PP
\fB\-\-rcc\-platform=\fR\fI<platform>\fR+
.RS 4
Specify the RCC platform to use to build the ACI application\&.
.RE
.PP
\fB\-\-run\-arg=\fR\fI<args>\fR+
.RS 4
Specify the argument(s) to insert immediately after the ACI executable or the
\fBocpirun\fR
command\&.
.RE
.sp
You can also add \fBrun\-arg\fR arguments after the application \fI<name>\fR; for example, to specify options to \fBocpirun\fR for XML applications\&. Preface these arguments with the double hyphen (\fB\-\-\fR) notation to indicate that they are not options to the \fBocpidev\fR command itself\&. For example, if you want to run an application with a number of \fBrun\-arg\fR arguments, you can use any of the following syntaxes:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev run application myapp \-\- \-v \-d \-Pxsim
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev run application myapp \-\-run\-arg=\-v \-\-run\-arg=\-d \-\-run\-arg=\-Pxsim
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev run application myapp \-\-run\-arg=\(rq\-v \-d \-Pxsim\(rq
.fi
.if n \{\
.RE
.\}
.sp
For an XML application, these command lines perform the command:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpirun \-v \-d \-Pxsim myapp
.fi
.if n \{\
.RE
.\}
.sp
For more information on how to use the \fBbefore\fR, \fBafter\fR and \fBrun\-arg\fR options, see the section "Applications in Projects" in the \fIOpenCPI Application Development Guide\fR\&.
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
From the project\(cqs
\fBapplications/\fR
directory, create an ACI application with the name
\fBMyApp\fR\&. The ACI application
\fBMyApp\&.cc\fR
will be created in the
\fBapplications/MyApp\fR
subdirectory of the project\&.
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev create application MyApp
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
From the project\(cqs top\-level directory, create an XML application named
\fBMyApp\fR\&. The XML application (empty OAS file)
\fBMyApp\&.xml\fR
will be created in the
\fBapplications/\fR
subdirectory of the project\&.
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev \-X create application MyApp
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
From the project\(cqs top\-level directory, delete the XML application named
\fBMyApp\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev delete application MyApp
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Build the application
\fBMyApp\fR
from inside its own directory\&. Since no target platform is specified, the application is built to run on the development system platform; for example, CentOS 7\&.
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev build
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 5.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  5." 4.2
.\}
From inside an ACI application\(cqs directory, build the ACI application for the Avnet Zedboard
\fBxilinx13_4\fR
embedded RCC platform:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev \-\-rcc\-platform xilinx13_4 build
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 6.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  6." 4.2
.\}
From the
\fBapplications/\fR
directory, run the application named
\fBMyApp\fR
that exists in that directory:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev run MyApp
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 7.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  7." 4.2
.\}
From the
\fBapplications/\fR
directory, run all the applications that exist in that directory:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev run
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 8.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  8." 4.2
.\}
Run all applications in the
\fBapplications/\fR
directory of a project:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev run applications
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 9.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  9." 4.2
.\}
Clean all applications in a project:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev clean applications
.fi
.if n \{\
.RE
.\}
.RE
.SH "BUGS"
.sp
See https://www\&.opencpi\&.org/report\-defects
.SH "RESOURCES"
.sp
See the main web site: https://www\&.opencpi\&.org
.SH "SEE ALSO"
.sp
ocpidev(1) ocpidev\-build(1) ocpidev\-component(1) ocpidev\-create(1) ocpidev\-clean(1) ocpidev\-delete(1) ocpidev\-project(1) ocpidev\-run(1)
.SH "COPYING"
.sp
Copyright (C) 2020 OpenCPI www\&.opencpi\&.org\&. OpenCPI is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
