.\"     Title: ocpihdl
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/20/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "OCPIHDL" "1" "08/20/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ocpihdl \- command\-line tool for performing OpenCPI HDL development tasks
.SH "SYNOPSIS"
.sp
\fBocpihdl\fR [\fI<options>\fR] \fI<verb>\fR [\fI<options\fR] [\fI<arguments>\fR]
.SH "DESCRIPTION"
.sp
The \fBocpihdl(1)\fR command\-line tool is used to perform a variety of OpenCPI HDL development tasks, including:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Searching for and listing available HDL devices (via PCI, Ethernet, UDP, simulators, etc\&.)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Testing the existence and availability of a specific HDL device
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Reading and writing specific registers in an HDL device
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Loading bitstreams on an HDL device
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Extracting the XML metadata from a running HDL device
.RE
.sp
An \fIHDL device\fR in this case refers to an instance of an HDL platform (FPGA or FPGA simulator) in an \fIOpenCPI system\fR (and not to a device attached to an FPGA inside the platform) that hosts an HDL container for execution\&. HDL devices have unique names within an OpenCPI system\&. Each name starts with a prefix that indicates how OpenCPI discovers and controls the device\&. See the chapter "HDL Device Naming" in the \fIOpenCPI HDL Development Guide\fR for a description of these prefixes and HDL device naming syntax\&. Also see the \fIOpenCPI HDL Development Guide\fR for detailed information on the OpenCPI HDL development process, including how to develop HDL workers, HDL primitives, HDl assemblies and bitstreams to support the execution of OpenCPI applications on FPGAs\&.
.SH "VERBS"
.sp
The verbs for general operations supported by \fBocpihdl\fR are:
.PP
\fBadmin\fR
.RS 4
Display an HDL device\(cqs administrative information\&.
.RE
.PP
\fBbram\fR
.RS 4
Create a configuration Block Random Access Memory (BRAM) file from an artifact description XML file\&.
.RE
.PP
\fBdeltatime\fR
.RS 4
Perform a time synchronization test on an HDL device\&.
.RE
.PP
\fBemulate\fR
.RS 4
Emulate a network\-based (UDP or Ethernet) HDL device (admin space only)\&.
.RE
.PP
\fBethers\fR
.RS 4
List the available (up and connected) network interfaces\&.
.RE
.PP
\fBgetxml\fR
.RS 4
Retrieve XML metadata from a running HDL device\&.
.RE
.PP
\fBload\fR
.RS 4
Load a bitstream onto an HDL device\&.
.RE
.PP
\fBprobe\fR
.RS 4
Test the existence and availability of an HDL device\&.
.RE
.PP
\fBradmin\fR
.RS 4
Read a specific address in an HDL device\(cqs admin space\&.
.RE
.PP
\fBreset\fR
.RS 4
Perform a soft reset on an HDL device\&.
.RE
.PP
\fBrmeta\fR
.RS 4
Read from addresses in the metadata space of an HDL device\&.
.RE
.PP
\fBsearch\fR
.RS 4
Search for and list all available (discovered and responding) HDL devices\&.
.RE
.PP
\fBsettime\fR
.RS 4
Set an HDL device\(cqs GPS time to the system time\&.
.RE
.PP
\fBunbram\fR
.RS 4
Create an artifact description XML file from a configuration BRAM file\&.
.RE
.PP
\fBwadmin\fR
.RS 4
Write specific addresses in an HDL device\(cqs admin space\&.
.RE
.sp
The verbs for higher\-level operations (operations that rely on embedded metadata) on individual HDL workers supported by \fBocpihdl\fR are:
.PP
\fBcontrol\fR
.RS 4
Change the control state of an HDL worker instance\&.
.RE
.PP
\fBget\fR
.RS 4
Get instance property information for a single HDL worker or all HDL workers\&.
.RE
.PP
\fBset\fR
.RS 4
Set a property value in an HDL worker instance\&.
.RE
.PP
\fBstatus\fR
.RS 4
Display the status of an HDL worker instance\&.
.RE
.sp
The verbs for lower\-level operations (operations that do not use embedded metadata) on individual workers supported by \fBocpihdl\fR are:
.PP
\fBwclear\fR
.RS 4
Clear the error registers of an HDL worker instance or a range of HDL worker instances\&.
.RE
.PP
\fBwdump\fR
.RS 4
Display the control and status registers for an HDL worker instance or a range of HDL worker instances\&.
.RE
.PP
\fBwop\fR
.RS 4
Perform a control operation on an HDL worker instance or a range of HDL worker instances\&.
.RE
.PP
\fBwread\fR
.RS 4
Read a value from the configuration property space of an HDL worker instance or a range of HDL worker instances\&.
.RE
.PP
\fBwreset\fR
.RS 4
Assert reset for an HDL worker instance or a range of HDL worker instances\&.
.RE
.PP
\fBwwctl\fR
.RS 4
Write the control register for an HDL worker instance or a range of HDL worker instances\&.
.RE
.PP
\fBwwpage\fR
.RS 4
Write the window/page register for an HDL worker instance or a range of HDL worker instances to reach full 32\-bit space\&.
.RE
.PP
\fBwwrite\fR
.RS 4
Write a single value into the configuration property space of an HDL worker instance or a range of HDL worker instances\&.
.RE
.sp
See OPERATIONS for a description of each \fBocpihdl\fR verb, its options and arguments\&.
.SH "NOUNS"
.sp
None\&.
.SH "OPTIONS"
.sp
The options described below can be used with many \fBocpihdl\fR operations\&. An option\(cqs effect on an individual \fBocpihdl\fR operation is described in that operation\(cqs description in OPERATIONS\&.
.PP
\fB\-d\fR \fI<hdl\-device>\fR
.RS 4
Specify the name of an HDL device on which to operate\&. The OCPI_HDL_DEVICE environment variable can be used to set a default value for this option\&.
.RE
.PP
\fBi\fR \fI<network\-interface>\fR
.RS 4
Specify the name of the network interface on which to operate\&. Examples:
\fBen0\fR,
\fBeth0\fR\&.
.RE
.PP
\fB\-l\fR \fI<log\-level>\fR
.RS 4
Specify the OpenCPI log level to be applied during execution\&. See the description of the OCPI_LOG_LEVEL environment variable in the
\fIOpenCPI User Guide\fR
for a description of possible values\&. Using this option overrides the level set in the OCPI_LOG_LEVEL environment variable\&.
.RE
.PP
\fB\-P\fR
.RS 4
Produce parseable output for
\fBocpihdl\fR
operations that read registers\&.
.RE
.PP
\fB\-p\fR \fI<hdl\-platform>\fR
.RS 4
Specify the identifier of the HDL platform on which to operate\&. Examples:
\fBml605\fR,
\fBalst4\fR,
\fBzed\fR,
\fBe31x\fR\&. See the
\fIOpenCPI User Guide\fR
for a list of supported HDL platforms and their identifiers\&.
.RE
.PP
\fB\-x\fR
.RS 4
Display numeric values in hexadecimal format\&. If this option is not used, numeric values are displayed in decimal format\&.
.RE
.SH "OPERATIONS"
.sp
The sections below describe each \fBocpihdl\fR operation and its associated options and arguments\&. These operations include:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
General operations that do not operate on individual HDL workers\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Operations on individual HDL workers\&. One set of HDL worker verbs relies on embedded metadata and is thus more user\-friendly, while another more "primitive" set does not rely on embedded metadata\&.
.RE
.SS "General Non\-HDL Worker Operations"
.PP
\fBocpihdl admin \-d\fR \fI<hdl\-device>\fR
.RS 4
Dump all of the information and state in the admin space for the HDL device specified in the
\fB\-d\fR
option\&. Device admin space contains the information for the device and loaded bitstream as a whole\&.
.RE
.PP
\fBocpihdl bram\fR \fI<xml\-file> <bram\-file>\fR
.RS 4
Convert an "artifact description XML" file into a "configuration BRAM" file to be processed (during HDL assembly build) into a read\-only BRAM inside the FPGA bitstream\&. Specify the name of the artifact description file in
\fI<xml\-file>\fR
and the file name for the generated configuration BRAM file in
\fI<bram\-file>\fR\&.
.RE
.PP
\fBocpihdl deltatime \-d\fR \fI<hdl\-device>\fR
.RS 4
Measure and correct the time\-skew between the system time\-of\-day and the specified HDL device time\-of\-day\&.
.RE
.PP
\fBocpihdl\fR [\fB\-i\fR {\fI<network\-interface>\fR | \fBudp\fR}] \fBemulate\fR
.RS 4
Emulate an Ethernet\- or UDP\-based HDL device and respond to discovery and admin space accesses\&. Use the
\fB\-i\fR
option to specify the network interface on which the emulated device should appear\&. If this option is not specified, the first available (up and connected) network interface is used\&. Use the
\fBudp\fR
keyword in the
\fB\-i\fR
option to emulate an OpenCPI HDL device attached to the IP subnet of the host computer implementing discovery and control via UDP\&.
.RE
.PP
\fBocpihdl ethers\fR
.RS 4
List the available Ethernet network interfaces on a system and their status (whether or not they are up and connected), the default network interface used for for verbs that take the
\fB\-i\fR
option (the first listed that is up and connected) and the identity chosen for the system (based on the first network interface with an address and a MAC address)\&.
.RE
.PP
\fBocpihdl getxml\fR {\fB\-d\fR \fI<hdl\-device>\fR | \fI<hdl\-device>\fR} \fI<output\-file>\fR
.RS 4
Retrieve and uncompress the XML metadata stored in the running HDL device specified with the
\fB\-d\fR
option or the
\fI<hdl\-device>\fR
argument and write it to the specified file\&.
.RE
.PP
\fBocpihdl load\fR \fI<bitstream\-file>\fR {\fB\-d\fR \fI<hdl\-device>\fR | \fI<hdl\-device>\fR}
.RS 4
Load the specified bitstream onto the HDL device specified with the
\fB\-d\fR
option or as an argument\&.
.RE
.PP
\fBocpihdl probe\fR {\fB\-d\fR \fI<hdl\-device>\fR | \fI<hdl\-device>\fR}
.RS 4
Contact the HDL device specified with the
\fB\-d\fR
option or as an argument and see if it responds\&. This operation should work regardless of whether or not the HDL device is running an application\&.
.RE
.PP
\fBocpihdl radmin\fR [\fB\-P\fR] \fB\-d\fR \fI<hdl\-device>\fR \fB[0x]\fR\fI<offset>\fR[\fB/\fR\fI<size>\fR]
.RS 4
Read an individual word of data from the specified offset in the admin space of the HDL device specified in the
\fB\-d\fR
option\&. Prepend
\fB0x\fR
to
\fI<offset>\fR
to indicate hexadecimal format; if this notation is not used, the format is decimal\&. Append the
\fB/\fR\fI<size>\fR
notation to
\fI<offset>\fR
to specify the size of the access in bytes; for example, /2, /4, or /8\&. If this notation is not used, the access is a 32\-bit access\&. Use the
\fB\-P\fR
option to return just the value in hexadecimal format\&. If this option is not used, the operation returns a message with the offset and the value\&.
.RE
.PP
\fBocpihdl reset \-d\fR \fI<hdl\-device>\fR
.RS 4
Reset the HDL device specified in the
\fB\-d\fR
option without affecting the control path to the device\&. For example, on a PCI\-Express\-based HDL device, an
\fBocpihdl reset\fR
operation does not damage or reconfigure the PCI\-Express interface\&.
.RE
.PP
\fBocpihdl rmeta\fR [\fB\-P\fR] \fB\-d\fR \fI<hdl\-device>\fR \fB[0x]\fR\fI<offset>\fR[\fB/\fR\fI<size>\fR]
.RS 4
Read an individual word of data from the specified offset in the configuration BRAM space of the HDL device specified in the
\fB\-d\fR
option\&. Prepend
\fB0x\fR
to
\fI<offset>\fR
to indicate hexadecimal format; if this notation is not used, the format is decimal\&. Append the
\fB/\fR\fI<size>\fR
notation to
\fI<offset>\fR
to specify the size of the access in bytes; for example, /2, /4, or /8\&. If this notation is not used, the access is a 32\-bit access\&. Use the
\fB\-P\fR
option to return just the value in hexadecimal format\&. If this option is not used, the operation returns a message with the offset and the value\&.
.RE
.PP
\fBocpihdl\fR [\fB\-i\fR \fI<network\-interface>\fR] \fBsearch\fR
.RS 4
Search for all reachable HDL devices using all the supported control paths (PCI, Ethernet, simulator) and list the results\&. Use the
\fB\-i\fR
option to limit the Ethernet search to the specified network interface\&.
.RE
.PP
\fBocpihdl settime \-d\fR \fI<hdl\-device>\fR
.RS 4
Set the time on the HDL device specified in the
\fB\-d\fR
option from the current system time\&. Use the
\fBocpihdl admin\fR
operation on the target HDL device to get the current time\&.
.RE
.PP
\fBocpihdl unbram\fR \fI<bram\-file> <xml\-file>\fR
.RS 4
Convert a configuration BRAM file (see
\fBocpihdl bram\fR) into an artifact description XML file\&. Specify the file name of the configuration BRAM file in
\fI<bram\-file>\fR
and the name of the artifact description file to be output in
\fI<xml\-file>\fR\&.
.RE
.PP
\fBocpihdl wadmin \-d\fR \fI<hdl\-device>\fR \fB[0x]\fR\fI<offset>\fR[\fB/\fR\fI<size>\fR] \fI<value>\fR
.RS 4
Write a 4\-byte/32\-bit or 8\-byte/64\-bit value at the specified offset in the admin space of the specified device\&. Prepend
\fB0x\fR
to
\fI<offset>\fR
to indicate hexadecimal format\&. Append the
\fB/\fR\fI<size>\fR
notation to
\fI<offset>\fR
to specify the size of the access in bytes; for example, /4 or /8\&. If this notation is not used, the access is a 32\-bit access\&.
.RE
.SS "HDL Worker Operations That Use Embedded Metadata"
.PP
\fBocpihdl get\fR [\fB\-v\fR | \fB\-x\fR] [\fI<worker\-instance\-name>\fR | \fI<worker\-instance\-index>\fR] [\fI<property\-name>\fR]
.RS 4
Display information for all HDL workers or the HDL worker instance specified by its name in the HDL assembly or its index as returned from a previous
\fBocpihdl\fR
operation like
\fBocpihdl get\fR\&. When an HDL worker instance is specified, the name of a property can be supplied as an argument to display the value of that property\&. The operation recognizes the data types of properties and displays the values accordingly\&. Use the
\fB\-v\fR
option to specify all property values; if this option is not used, the operation displays summary information\&. Use the
\fB\-x\fR
option to display all numeric values in hexadecimal format; if this option is not used, the values are displayed in decimal format\&.
.RE
.PP
\fBocpihdl control\fR {\fI<worker\-instance\-name>\fR | \fI<worker\-instance\-index>\fR} \fI<control\-operation\fR>
.RS 4
Perform the specified control operation on the HDL worker instance specified by its name in the HDL assembly or its index as returned from a previous
\fBocpihdl\fR
operation like
\fBocpihdl get\fR\&. Possible identifiers for control operations are the lifecycle operations identifiers
\fBinitialize\fR,
\fBstart\fR,
\fBstop\fR
and
\fBrelease\fR
and the identifiers
\fBreset\fR
and
\fBunreset\fR\&. For more information on OpenCPI worker lifecycle control operations, see the chapter "Authoring Models" in the
\fIOpenCPI Component Development Guide\fR\&.
.RE
.PP
\fBocpihdl set\fR [\fB\-x\fR] {\fI<worker\-instance\-name>\fR | \fI<worker\-instance\-index>\fR} \fI<property\-name>\fR \fI<value>\fR
.RS 4
Set the specified property of the specified HDL worker instance name or index to the specified value\&. When specifying the value, use the same syntax as is used to specify a property\(cqs initial or default value in a component specification (OCS), worker description (OWD) or HDL assembly description (OHAD)\&. For information on property value syntax, see the chapter "Property Values Syntax and Ranges" in the
\fIOpenCPI Component Development Guide\fR\&.
.RE
.PP
\fBocpihdl status\fR {\fI<worker\-instance\-name>\fR | \fI<worker\-instance\-index>\fR}
.RS 4
Display the status of the specified HDL worker instance name or index\&. Status displayed includes the worker control state and the display output of the
\fBwdump\fR
operation\&.
.RE
.SS "HDL Worker Operations That Do Not Use Embedded Metadata"
.PP
\fBocpihdl wclear \-d\fR \fI<hdl\-device>\fR \fI<worker\-instance\-index>\fR[\fB,\fR\&...]
.RS 4
Clear the error and attention bits in the status register in the control plane infrastructure for the HDL worker(s) specified by the instance index(es) on the specified HDL device\&. The
\fBocpihdl get\fR
operation can be used to return HDL worker instance indexes\&.
.RE
.PP
\fBocpihdl wdump \-d\fR \fI<hdl\-device>\fR \fI<worker\-instance\-index>\fR[\fB,\fR\&...]
.RS 4
Display the current status of the control and status registers in the control plane infrastructure for the HDL worker(s) specified by the instance index(es) on the specified HDL device\&.
.RE
.PP
\fBocpihdl wop \-d\fR \fI<hdl\-device>\fR \fI<worker\-instance\-index>\fR[\fB,\fR\&...] \fI<control\-operation>\fR
.RS 4
Execute a control operation for the HDL worker(s) specified by the instance index(es) on the specified HDL device, directly accessing the hardware that makes the control operation request of the worker\&. Possible control operations are:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBafter\fR
\- inform the worker that a batch of property reads has completed
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBbefore\fR
\- inform the worker that a batch of property settings will occur
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBinitialize\fR
\- request that a worker initialize itself after an
\fBocpihdl wunset\fR
operation
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBrelease\fR
\- return the worker to the pre\-initialized state
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBstart\fR
\- put the worker into an operational state after stop or initialize
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBstop\fR
\- suspend operation of the worker
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBtest\fR
\- run the worker\(cqs built\-in test
.sp
The
\fBstart\fR
control operation is the only operation implemented for all workers\&. Other operations have unpredictable or erroneous results when requested for workers that don\(cqt implement them\&.
.RE
.RE
.PP
\fBocpihdl wread \-d\fR \fI<hdl\-device>\fR \fI<worker\-instance\-index>\fR[\fB,\fR\&...] \fB[0x]\fR\fI<offset>\fR[\fB/\fR\fI<size>\fR][\fI<number\-of\-accesses>\fR]
.RS 4
Read a value from the specified offset into the property space of the HDL worker(s) specified by the instance index(es) on the specified HDL device\&. Prepend
\fB0x\fR
to
\fI<offset>\fR
to indicate hexadecimal format\&. Append the
\fB/\fR\fI<size>\fR
notation to
\fI<offset>\fR
to specify the size of the access in bytes; possible sizes are 1, 2, 4 and 8\&. If this optional notation is not used, the default size is 4\&. Use the
\fI<number\-of\-accesses>\fR
argument to specify the number of accesses to make; if this argument is not used, the default is 1\&. See the
\fBocpihdl wwpage\fR
operation for workers whose property space is larger than 1 MByte (2^20)\&.
.RE
.PP
\fBocpihdl wreset \-d\fR \fI<hdl\-device>\fR \fI<worker\-instance\-index>\fR[\fB,\fR\&...]
.RS 4
Assert the control reset signal into the specified HDL worker(s) on the specified HDL device\&. This signal remains asserted until the
\fBocpihdl wunreset\fR
operation is used\&.
.RE
.PP
\fBocpihdl wunreset \-d\fR \fI<hdl\-device>\fR \fI<worker\-instance\-index>\fR[\fB,\fR\&...]
.RS 4
Deassert the control reset signal into the specified HDL worker(s) on the specified HDL device\&. After executing this operation, the "wop initialize" operation (or the "wop start" operation for HDL workers that do not implement an initialize control operation) can be issued\&.
.RE
.PP
\fBocpihdl wwctl \-d\fR \fI<hdl\-device>\fR \fI<worker\-instance\-index>\fR[\fB,\fR\&...] [<value>]
.RS 4
Write the specified value to the control register in the control plane infrastructure for the specified HDL worker(s) on the specified HDL device\&. The
\fI<value>\fR
argument is a 32\-bit value\&. The bit definitions are described in the
\fIOpenCPI Platform Development Guide\fR\&.
.RE
.PP
\fBocpihdl wwpage \-d\fR \fI<hdl\-device>\fR \fI<worker\-instance\-index>\fR[\fB,\fR\&...] \fB[0x]\fR\fI<value>\fR
.RS 4
Set the "window" register in the control plane infrastructure for the HDL worker(s) specified by the instance index(es) on the specified HDL device to the specified value, which sets the high order 12 address bits (31:20) of the effective address when the
\fBocpihdl wread\fR
and
\fBocpihdl wwrite\fR
operations are issued\&. The offset in those operations supplies bits (19:0) of the effective address\&. An HDL worker\(cqs property space can be a full\-32 bit space (4 GBytes)\&. Use this operation to access more than the first 1MByte (2^20 bytes)\&.
.RE
.PP
\fBocpihdl wwrite \-d\fR \fI<hdl\-device>\fR \fI<worker\-instance\-index>\fR[\fB,\fR\&...] \fB[0x]\fR\fI<offset>\fR[\fB/\fR\fI<size>\fR] \fI<value\fR
.RS 4
Write the specified value to the specified offset into the property space of the HDL worker(s) specified by the instance index(es) on the specified HDL device\&. Prepend
\fB0x\fR
to
\fI<offset>\fR
to indicate hexadecimal format\&. Append the
\fB/\fR\fI<size>\fR
notation to
\fI<offset>\fR
to specify the size of the access in bytes; possible sizes are 1, 2, 4 and 8\&. If this optional notation is not used, the default size is 4\&. Use the
\fBocpihdl wwpage\fR
operation before using
\fBocpihdl wwrite\fR
to access more than the first 1MByte (2^20 bytes) for HDL workers with large property spaces\&.
.RE
.SH "ENVIRONMENT VARIABLES"
.sp
The following environment variables affect the \fBocpihdl\fR tool:
.PP
OCPI_DEFAULT_HDL_DEVICE
.RS 4
Sets a default value for the
\fB\-d\fR
\fI<device>\fR
option\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Convert the artifact description XML file named
\fBmyad\&.xml\fR
to a configuration BRAM file named
\fBmybram\&.bin\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpihdl bram myad\&.xml mybram\&.bin
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Emulate the HDL device attached to the IP subnet of the host computer that implements discovery and control via UDP:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpihdl \-i udp emulate
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Perform a two\-byte read of offset 12 on the HDL device named
\fBpci:5\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpihdl \-d pci:5 radmin 12/2
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Convert the configuration BRAM file named
\fBmybram\&.bin\fR
to an artifact description XML file named
\fBmyad\&.xml\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpihdl unbram mybram\&.bin myad\&.xml
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 5.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  5." 4.2
.\}
Write an 8\-byte value at offset 0x20 with the value 12345 on the HDL device named
\fBpci:5\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpihdl wadmin \-d pci:5 0x20/8 12345
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 6.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  6." 4.2
.\}
Display the value of the property named
\fBprop1\fR
of the worker instance named
\fBinstX\fR
in hexadecimal format:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpihdl get \-x instX prop1
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 7.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  7." 4.2
.\}
Set the value of a property named
\fBprop1\fR
that is an array of three shorts:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpihdl set instX prop1 "\-1,0x12,o177"
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 8.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  8." 4.2
.\}
Put the HDL worker instance named
\fBinstX\fR
into a reset condition (assert reset):
.sp
.if n \{\
.RS 4
.\}
.nf
ocpihdl control instX reset
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 9.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  9." 4.2
.\}
Clear the error and attention status for HDL worker instance 5 on the HDL device named
\fBPCI:5\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpihdl wclear \(end PCI:5 5
.fi
.if n \{\
.RE
.\}
.sp
Read three single bytes at offset 6 from HDL worker instance 11 on HDL device 5:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpihdl read \(end 5 11 6/1 3
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'10.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "10." 4.2
.\}
Read location
\fB0x12345678\fR
in HDL worker instance 7 with a full 4GByte property space on the HDL device named
\fBpci:5\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpihdl wwpage \(end pci:5 7 0x123
ocpihdl wread \(end pci:5 7 0x45678
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'11.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "11." 4.2
.\}
Write location
\fB0x20\fR
in HDL worker instance 6 on the HDL device named
\fBpci:5\fR
with the 64\-bit value
\fB0x123456789abc\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpihdl wwrite \(end pci:5 6 0x20 0x123456789abc
.fi
.if n \{\
.RE
.\}
.RE
.SH "BUGS"
.sp
See https://www\&.opencpi\&.org/report\-defects
.SH "RESOURCES"
.sp
See the main web site: https://www\&.opencpi\&.org
.SH "SEE ALSO"
.sp
ocpidev(1) ocpidev\-application(1) ocpidev\-assembly(1) ocpidev\-platform(1) ocpidev\-primitive(1) ocpidev\-worker(1) ocpirun(1)
.SH "COPYING"
.sp
Copyright (C) 2020 OpenCPI www\&.opencpi\&.org\&. OpenCPI is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
