'\" t
.\"     Title: ocpidev
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 07/29/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "OCPIDEV" "1" "07/29/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ocpidev \- command\-line tool for managing OpenCPI assets\&.
.SH "SYNOPSIS"
.sp
\fBocpidev\fR [\fI<options>\fR] \fI<verb>\fR [\fI<noun>\fR [\fI<name>\fR ]]
.SH "DESCRIPTION"
.sp
The \fBocpidev(1)\fR command line tool is used to perform various development\- related tasks inside projects as well as retrieve information about the environment\&. When used in projects, it can be invoked at the top level of the project or in lower\-level directories of the project as appropriate to the particular command being used\&. The \fBocpidev\fR command has full tab completion for its options and arguments\&.
.sp
Options can occur anywhere in the command for the user\(cqs convenience\&. The general usage concept is: perform the \fI<verb>\fR operation on the \fI<noun>\fR asset type whose name is \fI<name>\fR\&.
.SH "VERBS"
.sp
The verbs supported by \fBocpidev\fR are:
.PP
\fBbuild\fR
.RS 4
Build the asset(s), running appropriate tools to create the binary files\&.
.RE
.PP
\fBclean\fR
.RS 4
Remove all the generated and compiled files for the assets\&.
.RE
.PP
\fBcreate\fR
.RS 4
Create the named asset, creating files and directories as required, and creating any skeleton files for future editing\&.
.RE
.PP
\fBdelete\fR
.RS 4
Remove all directories and files associated with the named asset\&.
.RE
.PP
\fBrefresh\fR
.RS 4
Manually regenerate the metadata associated with the project\&.
.RE
.PP
\fBrun\fR
.RS 4
Execute the unit test or application\&.
.RE
.PP
\fBshow\fR
.RS 4
Display information about assets in registered projects and the current build environment (preliminary)\&.
.RE
.PP
\fBregister\fR, \fBunregister\fR
.RS 4
Register/unregister a project in its registry\&.
.RE
.PP
\fBset\fR, \fBunset\fR
.RS 4
Set/unset the registry used by the current project\&.
.RE
.PP
\fButilization\fR
.RS 4
Display or record FPGA resource use for HDL OpenCPI assets\&.
.RE
.SH "NOUNS"
.sp
The assets (nouns) supported by \fBocpidev\fR are:
.PP
\fBapplication\fR
.RS 4
A component application, specified in either XML or C++\&.
.RE
.PP
\fBapplications\fR
.RS 4
All applications in a project\(cqs
\fBapplications\fR
directory\&.
.RE
.PP
\fBcomponent\fR
.RS 4
A component specification XML file (OCS) at a project or a library level\&.
.RE
.PP
\fBlibrary\fR
.RS 4
A component library\&.
.RE
.PP
\fBproject\fR
.RS 4
A project containing all other asset types\&.
.RE
.PP
\fBproperties\fR
.RS 4
A properties XML file at a project or a library level\&.
.RE
.PP
\fBprotocol\fR
.RS 4
A protocol specification XML file (OPS) at a project or a library level\&.
.RE
.PP
\fBregistry\fR
.RS 4
A registry for projects to import/export dependencies from/to\&.
.RE
.PP
\fBtest\fR
.RS 4
A unit test suite for a component specification\&.
.RE
.PP
\fBworker\fR
.RS 4
A worker that implements a component specification\&.
.RE
.sp
Note that the assets \fBapplication\fR, \fBapplications\fR, \fBlibrary\fR, \fBproject\fR and \fBregistry\fR do not reside in libraries\&. The assets \fBproperties\fR, \fBprotocol\fR, \fBcomponent\fR, \fBtest\fR and \fBworker\fR reside in libraries\&.
.sp
The HDL\-specific assets (located under the \fBhdl/\fR subdirectory supported by \fBocpidev\fR are:
.PP
\fBhdl assembly\fR
.RS 4
An assembly of HDL workers used to build HDL containers\&.
.RE
.PP
\fBhdl assemblies\fR
.RS 4
All the assemblies in a project or in an HDL assemblies directory\&.
.RE
.PP
\fBhdl card\fR
.RS 4
A card specification XML file at a project level or an HDL library level\&.
.RE
.PP
\fBhdl device\fR
.RS 4
An HDL device worker in an HDL component library (\fBadapters/\fR,
\fBcards/\fR,
\fBdevices/\fR
or an HDL platform\(cqs
\fBdevices/\fR)\&.
.RE
.PP
\fBhdl platform\fR
.RS 4
An HDL platform worker in an HDL
\fBplatforms/\fR
directory, including its platform configurations\&.
.RE
.PP
\fBhdl platforms\fR
.RS 4
All HDL platforms in a project or in a project\(cqs
\fBhdl/platforms/\fR
directory\&.
.RE
.PP
\fBhdl primitive core\fR
.RS 4
An HDL primitive core in a project or in a project\(cqs
\fBhdl/primitives/\fR
directory\&.
.RE
.PP
\fBhdl primitive library\fR
.RS 4
An HDL primitive library in a project or in a project\(cqs
\fBhdl/primitives/\fR
directory\&.
.RE
.PP
\fBhdl primitives\fR
.RS 4
All HDL primitives (cores or libraries) in a project\&.
.RE
.PP
\fBhdl signals\fR
.RS 4
A signals specification XML file at a project level or an HDL library level\&.
.RE
.PP
\fBhdl slot\fR
.RS 4
A slot type definition XML file at the project level or the HDL library level\&.
.RE
.PP
\fBhdl subdevice\fR
.RS 4
An HDL subdevice worker in an HDL devices library that supports other HDL device workers\&.
.RE
.sp
Note that the HDL assets \fBcard\fR, \fBdevice\fR and \fBsubdevice\fR reside in one of the fixed HDL libraries in a project (\fBhdl/adapters/\fR, \fBhdl/cards/\fR, and \fBhdl/devices/\fR) or the \fBdevices/\fR library within an HDL platform\(cqs directory\&. The remaining HDL assets listed here do not reside in these libraries\&.
.SH "OPTIONS"
.sp
Options are either single letters following one hyphen or complete words or acronyms following two hyphens and separated by hyphens\&. Most options are only valid for specific verbs or nouns\&. The general\-purpose options are:
.PP
\fB\-d\fR \fIdirectory>\fR
.RS 4
Specify the directory in which this command should be run\&. Analogous to the
\fB\-C\fR
option in the POSIX
\fBmake\fR
command\&. This option can be specified more than once on the command line\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display help information\&. This option can be used in conjunction with a verb to display verb\-specific information\&. For example:
\fBocpidev \-\-help show\fR\&.
.RE
.PP
\fB\-\-verbose\fR, \fB\-v\fR
.RS 4
Describe what is happening in command execution in more detail\&.
.RE
.SH "BUGS"
.sp
See https://www\&.opencpi\&.org/report\-defects
.SH "RESOURCES"
.sp
See the main web site: https://www\&.opencpi\&.org
.SH "SEE ALSO"
.sp
ocpidev\-build(1) ocpidev\-clean(1) ocpidev\-create(1) ocpidev\-delete(1) ocpidev\-refresh(1) ocpidev\-register(1) ocpidev\-run(1) ocpidev\-set(1) ocpidev\-show(1) ocpidev\-unregister(1) ocpidev\-unset(1) ocpidev\-utilization(1)
.SH "COPYING"
.sp
Copyright (C) 2020 OpenCPI www\&.opencpi\&.org\&. OpenCPI is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
