.\"     Title: ocpiav
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 09/04/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "OCPIAV" "1" "09/04/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ocpiav \- command\-line tool for managing the OpenCPI AV GUI
.SH "SYNOPSIS"
.sp
\fBocpiav\fR [\fI<options>\fR] \fI<verb>\fR
.SH "DESCRIPTION"
.sp
The \fBocpiav(1)\fR command\-line tool is used to start the OpenCPI AV graphical user interface (GUI) for managing OpenCPI assets\&. It can also be used to set up a desktop shortcut for starting the AV tool from a CentOS7 development host\&.
.sp
The AV tool is a front end to \fBocpidev(1)\fR that can perform most, but not all, of the development tasks that \fBocpidev\fR can perform from within an Eclipse\-based GUI\&.
.SS "Installing AV"
.sp
AV is an optional OpenCPI development tool; the \fIOpenCPI Installation Guide\fR provides instructions on how to install it\&.
.SS "Using AV"
.sp
The \fIOpenCPI AV User Guide\fR describes the AV tool\(cqs menus and dialogs\&. The OpenCPI tutorials demonstrate how to use the AV tool to perform OpenCPI development tasks\&.
.SS "Working with OpenCPI Projects in AV"
.sp
AV is an Eclipse\-based tool and thus operates in a \(lqworkspace\(rq\&. The default workspace for the AV tool is located in the \fBav/workspace/\fR subdirectory of the OpenCPI installation\&. Do not create OpenCPI projects inside the AV tool because they will be created in the default AV workspace and will thus be inaccessible to other OpenCPI tools\&.
.sp
Use the \fBocpidev create project\fR operation to create a project outside of the AV tool and then use the AV tool to import it (do not copy it) into the AV workspace (File > Import > General > Import Existing Project dialog with the \(lqcopy\(rq option NOT checked\&.) The \fIOpenCPI User Guide\fR provides more information about this procedure, as do the OpenCPI tutorials\&.
.SH "VERBS"
.sp
The verbs supported by \fBocpiav\fR are:
.PP
\fBdesktop\fR
.RS 4
Add a selection for starting AV to the Applications > Programming menu bar on a CentOS7 development host\&.
.RE
.PP
\fBremove\fR
.RS 4
Remove the selection for AV from the Applications > Programming menu bar on a CentOS7 development host\&.
.RE
.PP
\fBrun\fR
.RS 4
Start AV from a
\fBbash\fR
shell\&.
.RE
.SH "NOUNS"
.sp
None\&.
.SH "OPTIONS"
.PP
\fB\-\-help\fR, \fB\-h\fR
.RS 4
Display usage information about the command\-line tool\&.
.RE
.SH "FILES/DIRECTORIES"
.sp
The following files and directories are relevant to OpenCPI AV operation:
.PP
\fBav\&.desktop\fR
.RS 4
The file that adds a menu selection for the OpenCPI AV tool to the Applications > Programming desktop environment menu bar on a CentOS7 development host\&. This file is created by the
\fBocpiav desktop\fR
operation in the CentOS7 user\(cqs home directory in the subdirectory
\fBlocal/share/applications/\fR\&.
.RE
.PP
\fBav/workspace/\fR
.RS 4
The subdirectory within the OpenCPI installation that contains the default Eclipse workspace for the AV tool\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Start the OpenCPI AV tool:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpiav run
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Add a menu selection for starting the OpenCPI AV tool from the CentOS7 desktop environment:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpiav desktop
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Remove the menu selection for the OpenCPI AV tool from the CentOS7 desktop environment:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpiav remove
.fi
.if n \{\
.RE
.\}
.RE
.SH "BUGS"
.sp
See https://www\&.opencpi\&.org/report\-defects
.SH "RESOURCES"
.sp
See the main web site: https://www\&.opencpi\&.org
.SH "SEE ALSO"
.sp
ocpidev(1) ocpidev\-project(1) ocpidev\-registry(1)
.SH "COPYING"
.sp
Copyright (C) 2020 OpenCPI www\&.opencpi\&.org\&. OpenCPI is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
