.\"     Title: ocpidev-delete
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 05/21/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "OCPIDEV\-DELETE" "1" "05/21/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ocpidev-delete \- delete OpenCPI assets
.SH "SYNOPSIS"
.sp
\fBocpidev\fR [\fI<options>\fR] \fBdelete\fR \fI<noun>\fR \fI<name>\fR
.SH "DESCRIPTION"
.sp
The \fBdelete\fR verb deletes OpenCPI assets from a project specified by the \fI<noun>\fR argument that follows the verb\&.
.sp
Asset types to be specified in the \fI<noun>\fR argument are:
.PP
\fBproject\fR
.RS 4
Delete a project which holds and organizes OpenCPI assets\&.
.RE
.PP
\fBregistry\fR
.RS 4
Delete a registry that enables projects to depend on each other\&.
.RE
.PP
\fBapplication\fR
.RS 4
Delete an application\&.
.RE
.PP
\fBspec\fR
.RS 4
Delete a component specification in a library or project\&.
.RE
.PP
\fBprotocol\fR
.RS 4
Delete a protocol in a library or project\&.
.RE
.PP
\fBtest\fR
.RS 4
Delete a component unit test in a library\&.
.RE
.PP
\fBlibrary\fR
.RS 4
Delete a component library\&.
.RE
.PP
\fBworker\fR
.RS 4
Delete a worker in a library\&.
.RE
.PP
\fBhdl\fR
.RS 4
A prefix to indicate an HDL asset in the
\fBhdl\fR
subdirectory of a project\&. Possible HDL assets are:
.PP
\fBassembly\fR
.RS 4
Delete an HDL assembly\&.
.RE
.PP
\fBcard\fR
.RS 4
Delete an HDL card definition\&.
.RE
.PP
\fBslot\fR
.RS 4
Delete an HDL slot definition\&.
.RE
.PP
\fBdevice\fR
.RS 4
Create/delete an HDL device worker, possibly in a specified platform\&.
.RE
.PP
\fBplatform\fR
.RS 4
Delete an HDL platform\&.
.RE
.PP
\fBprimitive\fR
.RS 4
Delete an HDL primitive\&. Possible primitive types are:
.PP
\fBlibrary\fR
.RS 4
A set of HDL primitive modules to use in workers as a library\&.
.RE
.PP
\fBcore\fR
.RS 4
A single primitive module, perhaps presynthesized (that is, from coregen or megawizard)\&.
.RE
.RE
.RE
.sp
All HDL assets should avoid having names that are Verilog or VHDL\- reserved identifiers, such as reg, etc\&.
.SH "OPTIONS"
.sp
The options for \fBdelete\fR are usually specific to the asset type that is being deleted\&. When deleting an asset, \fBocpidev\fR will ask for confirmation\&. You can override this with the \fB\-f\fR option to force deletion without confirmation\&.
.SS "Option When Deleting Any Asset Type"
.PP
\fB\-f\fR
.RS 4
Force deletion: do not ask for confirmation when deleting an asset\&. Normally, you are asked to confirm a deletion\&. This option takes no following argument and can only be specified once on the command line\&.
.RE
.SS "Option When Deleting Specs or Protocols"
.PP
\fB\-p\fR
.RS 4
Delete the spec or protocol from the
\fBspecs\fR
directory of the project, not from a library\(cqs
\fBspecs\fR
directory\&. This option takes no following argument and can only be specified once on the command line\&.
.RE
.SS "Options When Deleting Specs, Protocols, Workers or HDL Devices"
.PP
\fB\-l\fR \fI<library>\fR
.RS 4
Delete the asset from the specified library\&. This option can only be specified once on the command line\&.
.RE
.PP
\fB\-\-hdl\-library\fR \fI<hdl\-library>\fR
.RS 4
Delete the asset from the library under the
\fBhdl\fR
directory of the project\&. Valid values are only one of
\fBdevices\fR,
\fBcards\fR
or
\fBadapters\fR\&. This option can only be specified once on the command line\&.
.RE
.SH "EXAMPLES"
.sp
TBD
.SH "BUGS"
.sp
Report bugs to TBD\&.
.SH "AUTHOR"
.sp
TBD
.SH "RESOURCES"
.sp
Main web site: <www\&.opencpi\&.org>
.SH "SEE ALSO"
.sp
ocpidev\-create(1) ocpidev\-build(1) ocpidev\-clean(1) ocpidev\-show(1) ocpidev\-[un]register(1) ocpidev\-[un]set(1) ocpidev\-run(1) ocpidev\-refresh(1)
.SH "COPYING"
.sp
Copyright (C) 2020 OpenCPI www\&.opencpi\&.org\&. OpenCPI is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
