.\"     Title: ocpidev-registry
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 07/14/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "OCPIDEV\-REGISTRY" "1" "07/14/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ocpidev-registry \- manage an OpenCPI project registry\&.
.SH "SYNOPSIS"
.sp
\fBocpidev\fR [\fI<options>\fR] \fI<verb>\fR \fBregistry\fR [\fI<name>\fR]
.SH "DESCRIPTION"
.sp
The \fBregistry\fR noun represents an OpenCPI project registry, which is a directory that contains references to OpenCPI projects\&. An OpenCPI project registry is a way to manage project interdependencies\&. A project is automatically \fIassociated\fR with a registry when it is created, allowing it to view and depend on other projects registered there\&. A project can also be \fIregistered\fR in its associated project registry, allowing it to be visible to other projects associated there\&. Projects are not initially registered; the \fBocpidev register\fR operation for a project can be used to register them\&.
.sp
The OpenCPI installation provides a default project registry at $OCPI_CDK_DIR/\&.\&./project\-registry\&. However, in some project development environments, it can be useful to have an additional "sandbox" project registry for use as an alternative to the OpenCPI default\&.
.sp
The OpenCPI environment variable \fBOCPI_PROJECT_REGISTRY_DIR\fR can be set to point to an alternative project registry; setting this variable allows subsequently created projects to be associated with this registry and not with the OpenCPI default\&.
.sp
For more information about project registries and how to manage them, see the section "The Project Registry: How Projects Depend on and Find Each Other" in the \fIOpenCPI Component Development Guide\fR\&.
.sp
Verbs that can operate on a project registry are:
.PP
\fBcreate\fR
.RS 4
Create the named project registry at the specified location\&.
.RE
.PP
\fBdelete\fR
.RS 4
Remove the named project registry from the specified location\&.
.RE
.PP
\fBset\fR
.RS 4
Manually associate a project with a project registry\&.
.RE
.PP
\fBshow\fR
.RS 4
Display a list of projects registered with a project registry and their locations\&.
.RE
.PP
\fBunset\fR
.RS 4
Manually remove the association between a project and a project registry\&.
.RE
.SH "OPTIONS"
.sp
In the descriptions below, a plus sign (+) after the option indicates that it can be specified more than once on the command line\&.
.SS "Options That Apply to All Operations (Verbs) on Registries"
.PP
\fB\-d\fR \fI<directory>\fR
.RS 4
Specify the directory in which the command should be run\&. Analogous to the
\fB\-C\fR
option in the POSIX
\fBmake\fR
command\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Describe what is happening in command execution in more detail\&.
.RE
.SS "Options When Creating and Setting Registries"
.PP
\fB\-d\fR \fI<directory>\fR
.RS 4
Specify the path to the registry being created or set\&.
.RE
.SS "Options When Deleting Registries"
.PP
\fB\-f\fR
.RS 4
Force deletion: do not ask for confirmation when deleting a project registry\&. Normally, you are asked to confirm a deletion\&.
.RE
.SS "Options When Showing Registries"
.PP
\fB\-\-json\fR
.RS 4
Format the output in Javascript Object Notation (JSON) format for integration with other software\&.
.RE
.PP
\fB\-\-global\-scope\fR
.RS 4
Display information about all project registries\&. This is the default scope used if
\fB\-local\-scope\fR
is not used\&.
.RE
.PP
\fB\-\-local\-scope\fR
.RS 4
Only display information about the local project registry\&.
.RE
.PP
\fB\-\-simple\fR
.RS 4
Format the output as simply as possible\&.
.RE
.PP
\fB\-\-table\fR
.RS 4
Display the output in an easy\-to\-read table\&. This is the default display format used if
\fB\-\-simple\fR
or
\fB\-\-json\fR
are not used\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Create a registry
\fB~/workspace/my\-registry\fR\&. Note that this registry will not have the
\fBcore\fR
project registered, so you must locate and register the core project in
\fBmy\-registry\fR
after creating it\&.
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev create registry my\-registry \-d ~/workspace
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Display information about the projects in the current registry:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev show registry
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Inside the project, associate the project with the default registry:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev set registry
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Inside the project, associate the project with the registry named
\fBmy\-registry\fR
located at ~/workspace/:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev \-d ~/workspace set registry my\-registry
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 5.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  5." 4.2
.\}
Inside the project, remove the association between the project and a registry\&. The next time the project is built, the default project registry will be used:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev unset registry
.fi
.if n \{\
.RE
.\}
.RE
.SH "BUGS"
.sp
See https://www\&.opencpi\&.org/report\-defects
.SH "RESOURCES"
.sp
See the main web site: https://www\&.opencpi\&.org
.SH "SEE ALSO"
.sp
ocpidev(1) ocpidev\-create(1) ocpidev\-delete(1) ocpidev\-project(1) ocpidev\-set(1) ocpidev\-show(1) ocpidev\-unset(1)
.SH "COPYING"
.sp
Copyright (C) 2020 OpenCPI www\&.opencpi\&.org\&. OpenCPI is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
