.\"     Title: ocpixml
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 09/04/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "OCPIXML" "1" "09/04/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ocpixml \- command\-line tool for managing artifact description XML in OpenCPI artifact files
.SH "SYNOPSIS"
.sp
\fBocpixml\fR [\fI<options>\fR] \fI<verb>\fR \fI<artifact\-file>\fR[\fI<artifact\-file>\fR]
.SH "DESCRIPTION"
.sp
The \fBocpixml(1)\fR command\-line tool is used to manage the artifact description XML that exists inside an OpenCPI artifact file generated by the \fBocpidev(1)\fR \fBbuild\fR operation\&. The artifact description XML describes the contents of an executable binary (an artifact resulting from building an RCC or HDL worker or a component unit test) or a "bitstream" executable (an artifact resulting from building an HDL assembly) and is attached during the build process to the generated executable or bitstream (\fB\&.bitz\fR or \fB\&.gz\fR) artifact file\&. The \fBocpixml\fR tool is used to manipulate the artifact description XML attached to an artifact file\&.
.SH "VERBS"
.sp
The verbs supported by \fBocpixml\fR are:
.PP
\fBadd\fR
.RS 4
Add the artifact description XML from the named artifact file or
\fBstdin\fR
(indicated with a hyphen) to another named artifact file\&.
.RE
.PP
\fBget\fR
.RS 4
Extract the artifact description XML from the named artifact file to
\fBstdout\fR\&.
.RE
.PP
\fBstrip\fR
.RS 4
Remove the artifact description XML from the named artifact file and copy it to another named artifact file\&.
.RE
.SH "NOUNS"
.sp
None\&.
.SH "OPTIONS"
.PP
\fB\-\-help\fR, \fB\-h\fR
.RS 4
Display usage information about the tool\&.
.RE
.PP
\fB\-\-log_level=\fR\fI<level>\fR, \fB\-l\fR \fI<level>\fR
.RS 4
Set the OpenCPI log level to the specified level\&. This option can be used to override the logging level set in the
\fBOCPI_LOG_LEVEL\fR
environment variable\&. See ENVIRONMENT VARIABLES in
opencpi(1)
for a description of possible values\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Add the content of the artifact file named
\fBmyartifact2\&.bitz\fR
to the artifact file named
\fBmyartifact1\&.bitz\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpixml add myartifact2\&.bitz myartifact1\&.bitz
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Add standard input to the artifact file named
\fBmyartifact1\&.gz\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpixml add \- myartifact1\&.gz
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Extract the XML metadata from the artifact file named
\fBmyartifact1\&.bitz\fR
and write it to
\fBstdout\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpixml get myartifact1\&.bitz
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Remove the XML metadata from the artifact file named
\fBmyartifact1\&.gz\fR
and copy the results to the artifact file named
\fBmynewartifact1\&.gz\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpixml strip myartifact1\&.gz mynewartifact1\&.gz
.fi
.if n \{\
.RE
.\}
.RE
.SH "BUGS"
.sp
See https://www\&.opencpi\&.org/report\-defects
.SH "RESOURCES"
.sp
See the main web site: https://www\&.opencpi\&.org
.SH "SEE ALSO"
.sp
ocpidev\-assembly(1) ocpidev\-build(1) ocpidev\-platform(1) ocpidev\-test(1) ocpidev\-worker(1)
.SH "COPYING"
.sp
Copyright (C) 2020 OpenCPI www\&.opencpi\&.org\&. OpenCPI is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
