.\"     Title: ocpidev-library
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 07/14/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "OCPIDEV\-LIBRARY" "1" "07/14/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ocpidev-library \- manage an OpenCPI component library\&.
.SH "SYNOPSIS"
.sp
\fBocpidev\fR [\fI<options>\fR] \fI<verb>\fR \fBlibrary\fR \fI<name>\fR
.SH "DESCRIPTION"
.sp
The \fBlibrary\fR noun represents an OpenCPI component library, which is a single directory in a project that holds a collection of specifications, workers and tests that can be built, exported and installed to support applications\&.
.sp
A component library is described by its directory structure and Makefile and has source and binary forms, but does not have an XML definition\&.
.sp
In a project, a component library resides in its own directory\&. The default configuration is a single component library named \fBcomponents\fR that exists at the top level of a project\&. Multiple\-library configurations are also possible; in this configuration, the libraries reside in their own directories underneath a directory named \fBcomponents\fR that exists at the top level of the project\&. Note that none of the sublibraries underneath this directory can be named \fBcomponents\fR\&.
.sp
A component library has the following directory structure:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Component and protocol specifications exist in a
\fBspecs/\fR
directory\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Workers that implement the component exist in their own directories named
\fI<worker\-name>\fR\fB\&.\fR\fI<authoring\-model\-suffix>\fR; for example,
\fBMyWorker\&.rcc\fR
or
\fBMyWorker\&.hdl\fR\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Unit test suites for components in the library exist in their own directories named
\fI<component\-name>\fR\fB\&.test/\fR; for example,
\fBMyWorker\&.test\fR\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
When the library is built, links to the built binaries and metadata files required to use the components in the library from outside the library exist in the
\fBlib/\fR
directory\&.
.RE
.sp
For more information on component library directory structure, its Makefile and forms, see the chapter "Component Libraries" in the \fIOpenCPI Component Development Guide\fR\&.
.sp
Verbs that can operate on a component library are:
.PP
\fBbuild\fR
.RS 4
Build all assets in the library, creating files and directories as required\&.
.RE
.PP
\fBclean\fR
.RS 4
Remove all the generated and compiled files for all assets in the library\&.
.RE
.PP
\fBcreate\fR
.RS 4
Create the named library, creating files and directories as required\&.
.RE
.PP
\fBdelete\fR
.RS 4
Remove all directories and files associated with the named library\&.
.RE
.PP
\fBrun\fR
.RS 4
Run all unit tests in the library, creating files and directories as required\&.
.RE
.PP
\fButilization\fR
.RS 4
Display information about FPGA resource use for all built workers contained in the library\&.
.RE
.sp
Note that an asset\(cqs name is implied by the directory you\(cqre in when you issue the \fBocpidev\fR command\&. For component libraries, this means that you can perform operations (verbs) on the library without having to specify its name when you issue the \fBocpidev\fR command from inside the library\&.
.sp
The \fBocpidev\fR tool can also operate on a plural \fBlibraries\fR noun\&. The syntax is:
.sp
\fBocpidev \-\-local\-scope\fR [\fI<options>\fR] \fBshow libraries\fR
.sp
where \fBshow\fR is the only valid verb and the options that can be specified are \fB\-d\fR \fI<directory>\fR and the \fBshow\fR verb options\&. Note that the default global scope is not valid for the \fBlibraries\fR noun and generates an error\&. When you use the \fBlibraries\fR noun, you must specify the \fB\-\-local\-scope\fR option (or just \fB\-\-local\fR) to override the default\&.
.SH "OPTIONS"
.sp
In the descriptions below, a plus sign (+) after the option indicates that it can be specified more than once on the command line\&.
.sp
Keywords for platforms supported by OpenCPI that can be specified in the \fI<platform>\fR argument to an option can be found in the tables of supported platforms in the \fIOpenCPI User Guide\fR\&.
.sp
Keywords for architectures supported by OpenCPI that can be specified in the \fI<target>\fR argument to an option include \fBisim\fR, \fBmodelsim\fR, \fBstratix4\fR, \fBvirtex6\fR, \fBzynq\fR\&.
.SS "Options That Apply to All Operations (Verbs) on Libraries"
.PP
\fB\-d <directory>\fR
.RS 4
Specify the directory in which the command should be run\&. Analogous to the
\fB\-C\fR
option in the POSIX
\fBmake\fR
command\&.
.RE
.PP
\fB\-v, \-\-verbose\fR
.RS 4
Describe what is happening in command execution in more detail\&.
.RE
.SS "Options When Creating Libraries"
.PP
\fB\-\-exclude\-platform=\fR\fI<platform>\fR, \fB\-Q\fR \fI<platform>\fR+
.RS 4
Do not build the library for the specified platform\&.
.RE
.PP
\fB\-\-only\-platform=\fR\fI<platform>\fR, \fB\-G\fR \fI<platform>\fR+
.RS 4
Only build the library for the specified platform\&.
.RE
.PP
\fB\-A\fR \fI<directory>\fR+
.RS 4
Specify a directory to search for XML include files\&.
.RE
.PP
\fB\-F\fR \fI<package\-prefix>\fR
.RS 4
Specify the package prefix of the created library\&. The default is
\fI<package\-ID\-of\-project>\fR
for libraries\&.
.RE
.PP
\fB\-I\fR \fI<directory>\fR+
.RS 4
Specify a directory to search for include files (C, C++, Verilog)\&.
.RE
.PP
\fB\-K\fR \fI<package\-ID>\fR
.RS 4
Specify the package\-ID directly\&. The default is
\fI<package\-prefix>\fR\fB\&.\fR\fI<package\-name>\fR\&.
.RE
.PP
\fB\-N\fR \fI<package\-name>\fR
.RS 4
Specify the package name of the created library\&. The default is the
\fI<name>\fR
argument given after the
\fBcreate\fR
verb\&.
.RE
.PP
\fB\-T\fR \fI<target>\fR+
.RS 4
Only build the library for the specified architecture\&.
.RE
.PP
\fB\-Y\fR \fI<primitive\-library>\fR+
.RS 4
Specify a primitive library on which the library (or assets it contains) depends\&.
.RE
.PP
\fB\-Z\fR \fI<target>\fR+
.RS 4
Do not build the library for the specified architecture\&.
.RE
.PP
\fB\-k\fR
.RS 4
Keep files and directories created after a library creation fails\&. Normally, all such files and directories are removed on any failure\&.
.RE
.PP
\fB\-y\fR \fI<other\-component\-library>\fR+
.RS 4
Specify a component library to search for workers, devices and/or specs referenced by one or more assets in the created library\&.
.RE
.SS "Options When Deleting Libraries"
.PP
\fB\-f\fR
.RS 4
Force deletion: do not ask for confirmation when deleting a library\&. Normally, you are asked to confirm a deletion\&.
.RE
.SS "Options When Building Libraries"
.PP
\fB\-\-hdl\fR
.RS 4
Limit the assets being built to HDL primitives, workers or platforms\&.
.RE
.PP
\fB\-\-hdl\-platform=\fR\fI<hdl\-platform>\fR+
.RS 4
Build HDL assets in the library for the specified HDL platform\&.
.RE
.PP
\fB\-\-hdl\-rcc\-platform=\fR\fI<platform>\fR+
.RS 4
Build RCC/ACI assets in the library for the RCC platforms associated with the specified HDL platform\&. If this option is not used (and
\fB\-\-rcc\-platform\fR
\fI<platform>\fR
is also not used), the current development software platform is used as the single RCC platform used for building\&.
.RE
.PP
\fB\-\-hdl\-target=\fR\fI<target>\fR+
.RS 4
Build HDL assets in the library for the specified HDL architecture\&. If only HDL targets are specified (and no HDL platforms), containers are not built for HDL assemblies or unit test suites\&.
.RE
.PP
\fB\-\-rcc\fR
.RS 4
Limit the assets being built to RCC workers\&.
.RE
.PP
\fB\-\-rcc\-platform=\fR\fI<platform>\fR+
.RS 4
Build RCC/ACI assets in the library for the specified RCC platform\&. If this option is not used (and
\fB\-\-hdl\-rcc\-platform\fR
\fI<platform>\fR
is also not used), the current development software platform is used as the single RCC platform used for building\&.
.RE
.PP
\fB\-\-worker=\fR\fI<worker>\fR+
.RS 4
Limit the assets being built to the specified worker\&.
.RE
.SS "Options When Running Libraries"
.sp
The options described here, when used in an "ocpidev run library" command, are applied as appropriate to all of the unit tests that reside in the library\&.
.PP
\fB\-\-accumulate\-errors\fR
.RS 4
Report execution or verification errors as they occur rather than ending the test on the first failure detected\&.
.RE
.PP
\fB\-\-exclude\-platform=\fR\fI<platform>\fR, \fBQ\fR \fI<platform>\fR+
.RS 4
Specify the runtime platform to omit from a unit test suite\&.
.RE
.PP
\fB\-\-hdl\-platform=\fR\fI<platform>\fR+
.RS 4
Specify the HDL platform to use with the unit test suite\&. This option is only valid in generate and build phases\&.
.RE
.PP
\fB\-\-keep\-simulations\fR
.RS 4
Keep HDL simulation files regardless of verification results\&. By default, simulation files are removed if the verification is successful\&. Warning: Simulation files can become large!
.RE
.PP
\fB\-\-library=\fR\fI<library>\fR, \fB\-l\fR \fI<library>\fR
.RS 4
Run the unit test suite(s) in the specified library\&.
.RE
.PP
\fB\-\-mode=\fR\fI<mode>\fR[,\fI<mode>\fR[,\fI<mode>\fR\&...]]
.RS 4
Specify which phase(s) of the unit test suite to execute\&. Valid modes are:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBall\fR: execute all five phases (the default if
\fB\-\-mode\fR
is not used)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBgen\fR: execute generate phase
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBgen_build\fR: execute generate and build phases
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBprep_run_verify\fR: execute prepare, run, and verify phases
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBprep\fR: execute prepare phase
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBrun\fR: execute run phase
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBprep_run\fR: execute prepare and run phases
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBverify\fR: execute verify phase
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBview\fR: execute the view script (view\&.sh) on an already executed run
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBclean_all\fR: clean all generated files
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBclean_run\fR: clean all files generated during the run phase
.RE
.RE
.PP
\fB\-\-only\-platform=\fR\fI<platform>\fR, \fBG\fR \fI<platform>\fR+
.RS 4
Specify the runtime platform to use with a unit test suite\&.
.RE
.PP
\fB\-\-rcc\-platform=\fR\fI<platform>\fR+
.RS 4
Specify the RCC platform to use to build and generate the unit tests suite\&.
.RE
.PP
\fB\-\-remotes=\fR\fI<system>\fR
.RS 4
Specify the remote system to run the unit test suite(s) by setting the
\fBOCPI_REMOTE_TEST_SYS\fR
variable\&. See the section "Defining Remote Systems for Executing Tests" in the
\fIOpenCPI Component Development Guide\fR
for more information\&.
.RE
.PP
\fB\-\-view\fR
.RS 4
Run the view script (\fBview\&.sh\fR) for the test at the conclusion of the test suite\(cqs execution\&.
.RE
.SS "Options When Showing Libraries (plural noun only)"
.PP
\fB\-\-json\fR
.RS 4
Format the output in Javascript Object Notation (JSON) format for integration with other software\&.
.RE
.PP
\fB\-\-local\-scope\fR
.RS 4
Only display information about the local library\&.
.RE
.PP
\fB\-\-simple\fR
.RS 4
Format the output as simply as possible\&.
.RE
.PP
\fB\-\-table\fR
.RS 4
Display the output in an easy\-to\-read table\&. This is the default display format used if
\fB\-\-simple\fR
or
\fB\-\-json\fR
are not used\&.
.RE
.SS "Options When Using Utilization on Libraries"
.PP
\fB\-\-hdl=\fR\fI<library>\fR
.RS 4
Display information about FPGA resource use for the built workers contained in the specified HDL library\&.
.RE
.PP
\fB\-\-format=\fR{\fBtable\fR|\fBlatex\fR}
.RS 4
Specify the format in which to output the usage information\&. Specifying
\fBtable\fR
sends the information to stdout in tabular format\&. Specifying
\fBlatex\fR
bypasses
\fBstdout\fR
and writes all output to
\fButilization\&.inc\fR
files in the directories for the assets on which it operates\&.
.RE
.PP
\fB\-\-hdl\-platform=\fR\fI<platform>\fR+
.RS 4
Display information about FPGA resource use for the built workers in the libraries on the specified HDL platform\&.
.RE
.PP
\fB\-\-library=\fR\fI<library>\fR, \fB\-l\fR \fI<library>\fR
.RS 4
Display information about FPGA resource use for the built workers in the specified library\&.
.RE
.PP
\fB\-P\fR \fI<hdl\-platform>\fR
.RS 4
Display information about FPGA resource use for the built workers in the libaries on the specified HDL platform\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Create the default
\fBcomponents\fR
library for a project:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev create library components
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Inside the
\fBassets\fR
project, build the
\fButil_comps\fR
library for the
\fBzed\fR
HDL platform and
\fBxilinx13_3\fR
RCC platform\&.
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev build library util_comps \-\-hdl\-platform zed
                                 \-\-rcc\-platform xilinx13_3
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Inside the
\fBassets\fR
project, clean the
\fButil_comps\fR
library:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev clean library util_comps
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Run all the unit tests in the default
\fBcomponents\fR
library inside the current project:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev run library components
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 5.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  5." 4.2
.\}
Display information about the libraries in the current project:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev show libraries \-\-local\-scope
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 6.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  6." 4.2
.\}
Display FPGA resource usage information for all built workers in the
\fBcomponents\fR
library in the current project:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev utilization library components
.fi
.if n \{\
.RE
.\}
.RE
.SH "BUGS"
.sp
See https://www\&.opencpi\&.org/report\-defects
.SH "RESOURCES"
.sp
See the main web site: https://www\&.opencpi\&.org
.SH "SEE ALSO"
.sp
ocpidev(1) ocpidev\-build(1) ocpidev\-clean(1) ocpidev\-component(1) ocpidev\-create(1) ocpidev\-delete(1) ocpidev\-project(1) ocpidev\-run(1) ocpidev\-show(1) ocpidev\-utilization(1)
.SH "COPYING"
.sp
Copyright (C) 2020 OpenCPI www\&.opencpi\&.org\&. OpenCPI is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
