.\"     Title: ocpidev-project
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 05/24/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "OCPIDEV\-PROJECT" "1" "05/24/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ocpidev-project \- manage an OpenCPI project asset\&.
.SH "SYNOPSIS"
.sp
\fBocpidev\fR [\fI<options>\fR] \fI<verb>\fR \fBproject\fR \fI<name>\fR
.SH "DESCRIPTION"
.sp
The \fBproject\fR noun represents a project asset which holds and organizes OpenCPI assets\&.
.sp
Verbs that can operate on a project are:
.PP
\fBcreate\fR
.RS 4
Create the named project creating files and directories as required\&.
.RE
.PP
\fBdelete\fR
.RS 4
Remove all directories and files associated with the named project\&.
.RE
.PP
\fBbuild\fR
.RS 4
Build all assets in the named project\&.
.RE
.PP
\fBclean\fR
.RS 4
Remove all the generated and compiled files for all assets in the named project\&.
.RE
.PP
\fBrefresh\fR
.RS 4
Manually regenerate the metadata associated with the named project\&.
.RE
.PP
\fBrun\fR
.RS 4
Run all applications and unit tests in the named project\&.
.RE
.PP
\fBshow\fR
.RS 4
Display information associated with the named project\&.
.RE
.PP
\fB[un]register\fR
.RS 4
Register/unregister the named project in a registry\&.
.RE
.PP
\fButilization\fR
.RS 4
Display utilization information for all built workers, platforms, and assemblies contained in the named project\&.
.RE
.sp
Note that an asset\(cqs name is implied by the directory you\(cqre in when you issue the \fBocpidev\fR command\&. For projects, this means that you can perform operations (verbs) on the project without having to specify its name when you issue the \fBocpidev\fR command from inside the project directory\&.
.SH "OPTIONS"
.sp
TODO: Add any verb\-generic information here, if there is any\&.
.SS "Options That Apply to All Operations (Verbs) on Projects"
.PP
\fB\-v, \-\-verbose\fR
.RS 4
Describe what is happening in command execution in more detail\&. This option takes no following argument and can only be specified once on the command line\&.
.RE
.PP
\fB\-d <directory>\fR
.RS 4
Specify the directory in which the command should be run\&. Analogous to the
\fB\-c\fR
option in the POSIX
\fBmake\fR
command\&. This option can be specified more than once on the command line\&.
.RE
.SS "Options When Creating Projects"
.PP
\fB\-k\fR
.RS 4
Keep files and directories created after a project creation fails\&. Normally, all such files and directories are removed on any failure\&. This option takes no following argument and can only be specified once on the command line\&.
.RE
.PP
\fB\-D\fR \fI<pkg\-ID>\fR
.RS 4
Specify the package\-ID of a project on which the project being created depends\&. This option can be specified more than once on the command line\&.
.RE
.PP
\fB\-\-register\fR
.RS 4
Register the project as part of creating it\&. This option takes no following argument and can only be specified once on the command line\&.
.RE
.PP
\fB\-N\fR \fI<pkg\-name>\fR
.RS 4
Specify the package name of the created project\&. The default is the
\fI<name>\fR
argument given after the
\fBcreate\fR
verb\&. This option can be specified only once on the command line\&.
.RE
.PP
\fB\-F\fR \fI<pkg\-prefix>\fR
.RS 4
Specify the package prefix of the created project\&. The default is
\fBlocal\fR
for projects\&. This option can only be specified once on the command line\&.
.RE
.PP
\fB\-K\fR \fI<pkg\-ID>\fR
.RS 4
Specify the package\-ID directly\&. The default is
\fI<package\-prefix>\fR\fB\&.\fR\fI<package\-name>\fR\&. This option can only be specified once on the command line\&.
.RE
.PP
\fB\-A\fR \fI<directory>\fR
.RS 4
Specify a directory to search for XML include files\&. This option can be specified more than once on the command line\&.
.RE
.PP
\fB\-y\fR \fI<component\-library>\fR
.RS 4
Specify a component library to search for workers, devices and/or specs that this project (or assets it contains) references\&. This option can be specified more than once on the command line\&.
.RE
.PP
\fB\-I\fR \fI<directory>\fR
.RS 4
Specify a directory to search for include files (C, C++, Verilog)\&. This option can be specified more than once on the command line\&.
.RE
.PP
\fB\-Y\fR \fI<primitive\-library>\fR
.RS 4
Specify a primitive library on which the project (or assets it contains) depends\&. This option can be specified more than once on the command line\&.
.RE
.PP
\fB\-T\fR \fI<target>\fR
.RS 4
Only build the project for the specified target\&. This option can be specified more than once on the command line\&.
.RE
.PP
\fB\-Z\fR \fI<target>\fR
.RS 4
Do not build the project for the specified target\&. This option can be specified more than once on the command line\&.
.RE
.PP
\fB\-G\fR \fI<platform>\fR
.RS 4
Only build the project for the specified platform\&. This option can be specified more than once on the command line\&.
.RE
.PP
\fB\-Q\fR \fI<platform>\fR
.RS 4
Do not build the project for the specified platform\&. This option can be specified more than once on the command line\&.
.RE
.SS "Options When Deleting Projects"
.PP
\fB\-f\fR
.RS 4
Force deletion: do not ask for confirmation when deleting an asset\&. Normally, you are asked to confirm a deletion\&. This option takes no following argument and can only be specified once on the command line\&.
.RE
.SS "Options When Building Projects"
.PP
\fB\-\-no\-assemblies\fR
.RS 4
Don\(cqt build the assemblies in the project\&. Building HDL assemblies (and their containers) can be slow\&. This option takes no following argument and can only be specified once on the command line\&.
.RE
.PP
\fB\-\-hdl\-assembly\fR \fI<hdl\-assembly>\fR
.RS 4
Limit the assemblies being built to the specified assembly\&. This option can also be used in the
\fBhdl/assemblies\fR
directory\&. This option can be specified more than once on the command line\&.
.RE
.PP
\fB\-\-rcc\fR
.RS 4
Limit the assets being built to RCC workers\&. This option takes no following argument and can only be specified once on the command line\&.
.RE
.PP
\fB\-\-hdl\fR
.RS 4
Limit the assets being built to HDL primitives, workers, platforms or assemblies\&. This option takes no following argument and can only be specified once on the command line\&.
.RE
.PP
\fB\-\-worker\fR \fI<worker>\fR
.RS 4
Limits the assets being built to the specified worker\&. This option can be specified more than once on the command line\&.
.RE
.PP
\fB\-\-rcc\-platform\fR \fI<platform>\fR
.RS 4
Build RCC/ACI assets for the specified RCC platform\&. If this option is not used (and
\fB\-\-hdl\-rcc\-platform\fR
\fI<platform>\fR
is also not used), the current development software platform is used as the single RCC platform used for building\&. This option can be specified more than once on the command line\&.
.RE
.PP
\fB\-\-hdl\-rcc\-platform\fR \fI<platform>\fR
.RS 4
Build RCC/ACI assets for the RCC platforms associated with the specified HDL platform\&. If this option is not used (and
\fB\-\-rcc\-platform\fR
\fI<platform>\fR
is also not used), the current development software platform is used as the single RCC platform used for building\&. This option can be specified more than once on the command line\&.
.RE
.PP
\fB\-\-hdl\-target\fR \fI<target>\fR
.RS 4
Build HDL assets for the specified HDL target\&. If only HDL targets are specified (and no HDL platforms), containers will not be built for assemblies or unit tests\&. This option can be specified more than one on the command line\&.
.RE
.PP
\fB\-\-hdl\-platform\fR \fI<hdl\-platform>\fR
.RS 4
Build HDL assets for the specified HDL platform\&. This option can be specified more than once on the command line\&.
.RE
.SS "Options When Cleaning Projects"
.PP
\fB\-\-no\-assemblies\fR
.RS 4
Don\(cqt clean the assemblies in the project\&. This option takes no following argument and can only be specified once on the command line\&.
.RE
.PP
\fB\-\-hdl\-assembly\fR \fI<hdl\-assembly>\fR
.RS 4
Limit the assemblies being cleaned to the specified assembly\&. This option can also be used in the
\fBhdl/assemblies\fR
directory\&. This option can be specified more than once on the command line\&.
.RE
.PP
\fB\-\-rcc\fR
.RS 4
Limit the assets being cleaned to RCC workers\&. This option takes no following argument and can only be specified once on the command line\&.
.RE
.PP
\fB\-\-hdl\fR
.RS 4
Limit the assets being cleaned to HDL primitives, workers, platforms or assemblies\&. This option takes no following argument and can only be specified once on the command line\&.
.RE
.PP
\fB\-\-worker\fR \fI<worker>\fR
.RS 4
Limits the assets being cleaned to the specified worker\&. This option can be specified more than once on the command line\&.
.RE
.SS "Options When Running Projects"
.sp
The options described here, when used in an "ocpidev run project" command, are applied as appropriate to all of the runnable assets (applications and unit tests) that reside in the project\&. Note that any application\-specific options supplied on the command line are only applied to XML applications and not to ACI applications\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBOptions That Apply to Applications and Unit Tests\fR
.RS 4
.PP
\fB\-\-rcc\-platform=\fR\fI<platform>\fR
.RS 4
Specify the RCC platform to use to build and generate the unit tests and build the ACI applications\&.
.RE
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBOptions That Apply to Applications Only\fR
.RS 4
.PP
\fB\-\-before\fR \fI<args>\fR
.RS 4
Specify the argument(s) to insert before the ACI executable or the
\fBocpirun\fR
command; for example, environment settings or prefix commands\&. This option can be specified more than once on the command line\&.
.RE
.PP
\fB\-\-after\fR \fI<args>\fR
.RS 4
Specify the argument(s) to insert at the end of the execution command line\&. This option can be specified more than once on the command line\&.
.RE
.PP
\fB\-\-run\-arg\fR \fI<args>\fR
.RS 4
Specify the argument(s) to insert immediately after the ACI executable or the
\fBocpirun\fR
command\&. This option can be specified more than once on the command line\&.
.RE
.sp
For details on how to use these options, see the section "Applications in Projects" in the \fIOpenCPI Application Development Guide\fR\&.
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBOptions That Apply to Unit Tests Only\fR
.RS 4
.PP
\fB\-\-keep\-simulations\fR
.RS 4
Keep HDL simulation files regardless of verification results\&. By default, simulation files are removed if the verification is successful\&. Warning: Simulation files can become large!
.RE
.PP
\fB\-\-accumulate\-errors\fR
.RS 4
Report execution or verification errors as they occur rather than ending the test on the first failure detected\&.
.RE
.PP
\fB\-\-only\-platform=\fR\fI<platform>\fR
.RS 4
Specify the runtime platform to use with a unit test\&. This options performs the same function as the
\fB\-G\fR
option\&.
.RE
.PP
\fB\-\-exclude\-platform=\fR\fI<platform>\fR
.RS 4
Specify the runtime platform to omit from a unit test\&. This option performs the same function as the
\fB\-Q\fR
option\&.
.RE
.PP
\fB\-\-mode=\fR\fI<mode>\fR
.RS 4
Specify which phase(s) of the unit test to execute\&. Valid modes are all, gen, gen_build, prep_run_verify, prep, run, prep_run, verify, view, clean_all, clean_run, clean_sim\&.
.RE
.PP
\fB\-\-remotes=\fR\fI<system>\fR
.RS 4
Specify the remote system to run the test(s) by setting the
\fBOCPI_REMOTE_TEST_SYS\fR
variable\&. See the section "OCPI_REMOTE_TEST_SYS" in the
\fIOpenCPI Component Development Guide\fR
for more information\&.
.RE
.PP
\fB\-\-view\fR
.RS 4
Run the view script (view\&.sh) for the test at the conclusion of the test\(cqs execution\&.
.RE
.PP
\fB\-\-hdl\-platform=\fR\fI<platform>\fR
.RS 4
Specify the HDL platform to use with the unit test\&. This option is only valid in generate and build phases\&.
.RE
.PP
\fB\-\-case=\fR\fI<case\-name>\fR
.RS 4
Specify the test case(s) to be run/verified\&.
\fI\&. If this option is not used, the default case run/verified is \fR\fI\fBcase00\fR\fR\fI\&. You can specify wildcards in \*(Aq<case\-name>\&. To specify a subcase, use the notation \*(Aq<case\-name>\fR\fB\&.\fR\fI<subcase\-number>\fR\&. Examples: case*\&., case0\&.0*, case00\&.01
.RE
.RE
.SS "Options When Showing Projects"
.PP
\fB\-\-table\fR
.RS 4
Display the output in an easy\-to\-read table\&. This is the default display format used if
\fB\-\-simple\fR
or
\fB\-\-json\fR
are not used\&.
.RE
.PP
\fB\-\-simple\fR
.RS 4
Format the output as simply as possible\&.
.RE
.PP
\fB\-\-json\fR
.RS 4
Format the output in json format, for integration with other software\&.
.RE
.PP
\fB\-\-global\-scope\fR
.RS 4
Show assets from all registered projects and the current project if applicable\&. This is the default scope used if
\fB\-local\-scope\fR
is not used\&.
.RE
.PP
\fB\-\-local\-scope\fR
.RS 4
Only show assets in the local project\&.
.RE
.PP
\fB\-\-very\-verbose\fR
.RS 4
Be very verbose with output\&.
.RE
.PP
\fB\-\-very\-very\-verbose\fR
.RS 4
Be very, very verbose with output\&.
.RE
.SS "Options When Using Utilization on Projects"
.PP
\fB\-\-format=\fR{\fBtable,latex\fR}
.RS 4
Specify the format in which to output the utilization information\&. Specifying
\fBlatex\fR
bypasses
\fBstdout\fR
and writes all output to
\fButilization\&.inc\fR
files in the directories for the assets acted on\&.
.RE
.PP
\fB\-\-hdl\-platform=\fR\fI<platform>\fR
.RS 4
Specify the buildable HDL platform for which to display utilization information\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Create a project with name
\fBmy\-project\fR\&. This project\(cqs package\-ID will be
\fBlocal\&.my\-project\fR:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev create project my\-project
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Create a project with package\-prefix
\fBorg\&.my_organization\fR
and name
\fBmy_project\fR\&. This project\(cqs package\-ID will be
\fBorg\&.my_organization\&.my_project\fR\&.
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev create project my\-project \-F org\&.my_organization
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Build the
\fBassets\fR
project for the
\fBzed\fR
HDL platform and
*`xilinx13_3* RCC platform\&. Omit the name
\fBassets\fR
if inside the
\fBassets\fR
project\&.
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev build project assets \-\-hdl\-platform zed
                             \-\-rcc\-platform xilinx13_3
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
TODO: Add example for clean project\&.
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev clean project assets
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 5.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  5." 4.2
.\}
Register the current project to its registry (or the default if it doesn\(cqt have one yet):
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev register project
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 6.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  6." 4.2
.\}
Unregister the current project:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev unregister project
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 7.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  7." 4.2
.\}
TODO: Add example for run project\&.
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev run project
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 8.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  8." 4.2
.\}
TODO: Add example for show project\&.
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev show project
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 9.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  9." 4.2
.\}
Show utilization for all supported assets in a project:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev utilization project
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'10.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "10." 4.2
.\}
Record utilization for all supported assets in a project in LaTeX format:
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev utilization project \-\-format=latex
.fi
.if n \{\
.RE
.\}
.RE
.SH "BUGS"
.sp
See https://www\&.opencpi\&.org/report\-defects
.SH "RESOURCES"
.sp
See the main web site: https://www\&.opencpi\&.org
.SH "SEE ALSO"
.sp
ocpidev\-build(1) ocpidev\-clean(1) ocpidev\-delete(1) ocpidev\-refresh(1) ocpidev\-run(1) ocpidev\-show(1) ocpidev\-[un]register(1) ocpidev\-[un]set(1)
.SH "COPYING"
.sp
Copyright (C) 2020 OpenCPI www\&.opencpi\&.org\&. OpenCPI is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
