.\"     Title: ocpidev-unset
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 05/28/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "OCPIDEV\-UNSET" "1" "05/28/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ocpidev-unset \- manually disassociate the current project from a registry\&.
.SH "SYNOPSIS"
.sp
\fBocpidev\fR [\fI<options>\fR] \fBunset registry\fR
.SH "DESCRIPTION"
.sp
Projects are automatically associated with the current registry when they are created or used\&. A project can be manually associated with or disassociated from a particular registry\&. Use the \fBocpidev unset registry\fR command to remove an association between the current project and a particular registry\&.
.sp
You must run this command from within a project\&.
.sp
Asset types to be specified in the \fI<noun>\fR argument are:
.PP
\fBregistry\fR
.RS 4
Unset the registry for the current project\&.
.RE
.SH "OPTIONS"
.sp
You can use the general\-purpose options \fB\-v\fR and \fB\-d\fR \fI<directory>\fR with this command\&. In particular, you can use the \fB\-d\fR \fI<directory>\fR option to specify the pathname of the registry being unset\&.
.sp
There are no verb\-specific options\&.
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Unset the current project\(cqs registry\&. The next time the project is built, the default registry will be used\&.
.sp
.if n \{\
.RS 4
.\}
.nf
ocpidev unset registry
.fi
.if n \{\
.RE
.\}
.RE
.SH "BUGS"
.sp
See https://www\&.opencpi\&.org/report\-defects
.SH "RESOURCES"
.sp
See the main web site: https://www\&.opencpi\&.org
.SH "SEE ALSO"
.sp
ocpidev(1) ocpidev\-build(1) ocpidev\-clean(1) ocpidev\-create(1) ocpidev\-delete(1) ocpidev\-refresh(1) ocpidev\-register(1) ocpidev\-run(1) ocpidev\-set(1) ocpidev\-show(1) ocpidev\-unregister(1) ocpidev\-unset(1) ocpidev\-utilization(1)
.SH "COPYING"
.sp
Copyright (C) 2020 OpenCPI www\&.opencpi\&.org\&. OpenCPI is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
